### ISSUE TITLE
[Quest] Finding the Survivors (H)

### ISSUE THREAD

**Issue by Midgie** [FeenixServerProject/Archangel_2.4.3_Bugtracker#1011]
Re-reported from #798, since the issue was closed and never fixed.

http://old.wowhead.com/quest=9948
Obtained in Nagrand at the Mag'hari Procession.

1) Does not give credit toward quest completion when you use the <a href="http://old.wowhead.com/item=25604">Warmaul Prison Key</a> to open the cages.

2) Some of the <a href="http://old.wowhead.com/npc=18428">Mag'har Prisoner</a>s do not despawn after being let out of their cages.

**Comment by devastator** [comment]
https://github.com/FeenixServerProject/Archangel_2.4.3_Bugtracker/issues/3785
