### ISSUE TITLE
[Quest][Blade's Edge Mountains] Planting the Banner

### ISSUE THREAD

**Issue by Sethzer** [FeenixServerProject/Archangel_2.4.3_Bugtracker#1065]
http://www.wowhead.com/quest=10518
http://db.hellground.pl/?quest=10518

The ogres that spawn after planting the banner do not run to the top of the tower and remain on the bottom.

Spawning rate of the waves of ogres seem to work fine

**Comment by devastator** [comment]
Fix went on live with Patch 12.0
