### ISSUE TITLE
Escort quests bugged!

### ISSUE THREAD

**Issue by ikana1** [FeenixServerProject/Archangel_2.4.3_Bugtracker#1265]
A small bug with escort quests is happening, You will start the quest, escort npc and then they will not despawn and respawn at the start point, you have to start the quest at the end point, which causes the npc to run back to the start point and then once they get there, run back to the end point, beginning the cycle all over again.
This seems to be an issue with most escorts in the game

**Comment by devastator** [comment]
https://github.com/FeenixServerProject/Archangel_2.4.3_Bugtracker/issues/3785
