### ISSUE TITLE
[Herbalism] Bloodmyst Isle

### ISSUE THREAD

**Issue by Groshar** [FeenixServerProject/Archangel_2.4.3_Bugtracker#1402]
There are simply no herbs to be found here.  I've been all around this zone on my draenei alt and have yet to find a single node.  Yes, I made SURE that Find Herbs was active.  Here is a list of herbs that can normally be found here:  http://www.wowwiki.com/Bloodmyst_Isle#Resources

**Comment by lajhar** [comment]
Already fixed on live
