### ISSUE TITLE
[Mage][Talent]Master of Elements

### ISSUE THREAD

**Issue by Fleischi** [FeenixServerProject/Archangel_2.4.3_Bugtracker#1533]
current situation:
Master of Elements returns 30% of the mana cost of a spell _per critical hit_, so that 4 crits with an aoe spell would result in an effective mana gain for a mage.

should be:
Master of Elements should return 30% of the mana cost of a spell if _at least one_ of the hits is critical.

From a [Wowhead comment](http://www.wowhead.com/spell=29075#comments:id=1117460):

> What happens if this gains more than one critical effect from an AoE? Will it be 30% BMCost \* critical hits?
> 
> > Critically hitting 10 mobs with one Flamestrike gives 30% mana back in total.

From [wowwiki](http://www.wowprovider.com/?talent=2438606_2_7v53051335d210252155105205r):
It[Master of Elements] restores up to 10/20/30% of the mana cost of a Fire or Frost spell that critically hits one or more targets.

**Comment by Asuschrist** [comment]
It works as intented now, google a bit and you'll realize that's how it worked on retail.
No matter how many crits you get from Flamestrike, you return 30% mana of the Flamestrike only.
