### ISSUE TITLE
Trinket not showing in combat log

### ISSUE THREAD

**Issue by Silfenix** [FeenixServerProject/Archangel_2.4.3_Bugtracker#1610]
[Medallion of the Alliance] and horde equivalent do not show in combat log after u use them. This particular bug is bad coz it makes addons such as gladdy/proximo not work.

How To reproduce: equip  [Medallion of the Alliance] on any ally char, use it and check combat log, not shown.

**Comment by Schaka** [comment]
By now, everyone uses an addon for trinket times and most widely spread TBC addons rely on GladdyTrinketUsed addon messages. It's been generally accepted by many servers and is "the old solution AT used".

I implemented this for TBC, if there was any interest, it could be used on Feenix fairly easily:
https://github.com/Looking4Group/L4G_Core/commit/f7859c0ab0a866ae1d94c1e6acfa6fe7d98bf3ee
