### ISSUE TITLE
[Paladin][Quest] The path of the adept.

### ISSUE THREAD

**Issue by albarozz** [FeenixServerProject/Archangel_2.4.3_Bugtracker#1611]
As I go to Deatholme (located in Ghostlands) to gather quest item "Blood Knight Insignia" thet should be looted from a body located in Deatholme the body isn't there so I cannot complete the quest.

Please fix this issue as the paladin quests are made so you get specific spells, mount, etc by doing them.

Thanks

-Albarozz

**Comment by HansoolooStyl** [comment]
Its been a year so i wanna give this a bump. I have been doing the quest at Deatholme for two days now. With titan bar and carbonite my mesh ordinates are [34, 81]. The body will not show up or spawn at this point. The enemy at the cauldron will fall under / in to it and get stuck if she is allowed to run while engaging. My character has all so been unable to loot chest, exit game, and log out while here. I am stuck in combat after every one is dead and I had to force quit WoW and resurrect at the location after logging back on. The combat bug has all so happened to my Paladin in Silvermoon while in resting xp state at the Undercity portal killing me when I force quit WoW after completing my mission.

**Comment by devastator** [comment]
Fixed. Soon on PTR

**Comment by devastator** [comment]
Applied to Live with patch 14.15
