### ISSUE TITLE
[Quest][Shadowmoon Valley] The Path of Conquest (H)

### ISSUE THREAD

**Issue by debix** [FeenixServerProject/Archangel_2.4.3_Bugtracker#162]
http://old.wowhead.com/quest=10750#comments

Flew all over the place above Path of Conquest and i still could not "explore" it for this quest (note, that quest exploration is not map area-unveiling/exploring). So Kor'kron Wind Rider can be summoned, but he still has grey question mark. 

Also, Flare gun http://old.wowhead.com/item=31108#comments summons desired NPC, but the NPC does not fly to you on wind rider or anything. He simply apprears at your location.

**Comment by devastator** [comment]
Added more points to complete the quest. Soon on PTR

**Comment by lajhar** [comment]
Fix confirmed on PTR.

**Comment by lajhar** [comment]
On live (15.8)
