### ISSUE TITLE
[Quest][Dustwallow Marsh] "What's Haunting Witch Hill?" objective bugged

### ISSUE THREAD

**Issue by mfbeary** [FeenixServerProject/Archangel_2.4.3_Bugtracker#1631]
Quest: [What's Haunting Witch Hill?](http://www.wowhead.com/quest=11180/whats-haunting-witch-hill)
NPC objective bugged: Talk to [Restless Apparition](http://www.wowhead.com/npc=23861)
current issue: can get credit for repeatedly talking the the same apparition
desired behavior: can only get credit once for each apparition
evidence: all the comments on the quest page referring to killing multiple of the mobs that spawn Apparitions when they die.

**Comment by devastator** [comment]
Fix went Live with patch 12.0
