### ISSUE TITLE
[Spells] [Priest] Holy Nova

### ISSUE THREAD

**Issue by Ryuugen** [FeenixServerProject/Archangel_2.4.3_Bugtracker#1734]
Date/Time: 13th august '12 / 21:43

Error Severity: Low

Error type:
Holy Nova produced threat getting me the aggro from mobs tanked by a paladin.

How it should work:
Holy Nova states that both, the damage and the healing component produce no threat.

Can the error be repeated? If so, what are the steps?:
Just let someone pull any mob, then spam Holy Nova to gain the aggro.

Character Race: Nightelf

**Comment by roblockster** [comment]
Fix denied on PTR 2/4, .debug threat shows threat generated in combat by casts of holy nova.

**Comment by devidao** [comment]
Re-fixed, fix coming soon on PTR

**Comment by Nzzoth** [comment]
Fix denied on PTR.

**Comment by Nzzoth** [comment]
Fix confirmed on PTR. The issue with combat state has also been checked and it works properly.

**Comment by Nzzoth** [comment]
Confirmed on PLTR.

**Comment by Forcy** [comment]
Fixed in patch 14.22
