### ISSUE TITLE
[Quest] Corruption - Master Swordsmith

### ISSUE THREAD

**Issue by malermartin** [FeenixServerProject/Archangel_2.4.3_Bugtracker#1742]
Hi, 

I've searched the bugtracker for similar topic - but couldn't find any.

I'm a Blacksmither - 375 wanting to train Master Swordsmith for the tanking weapon.
I took the Quest in Everlook, Winterspring: http://www.wowwiki.com/Quest:Corruption.
I've been in Stratholme with some mates trying to summon Black Guard Swordsmith needed for the Insignia.
Black Guard Swordsmith: http://www.wowwiki.com/Black_Guard_Swordsmith

The first time we tried to trigger him it failed - We went out the Back Door from Stratholme and reset.
Second time failed just as much as first.

I hoping you can assist me with this issue. 
If you've already helped someone out with this, please redirect me as I haven't found similar topics.

Thank you in advance.

// Merde

**Comment by Salce** [comment]
*Fix confirmed on PLTR*

**Comment by devastator** [comment]
Applied to Live with patch 11.10
