### ISSUE TITLE
[Warrior][Fear]Breaking on damage

### ISSUE THREAD

**Issue by warlee** [FeenixServerProject/Archangel_2.4.3_Bugtracker#2022]
Current situation: Warrior's fear doesnt break on damage instantly (warrior fear isnt same as others, it isnt even magic effect, there it should break on first damage taken/absorbed). 

VIDEO EXAMPLE FROM RETAIL: 
http://www.youtube.com/watch?v=c1-zvAxeJmw 
Go to 13:14. Warrior's fear breaks instantly on damage taken.

 Expected situation: Warrior's fear breaks INSTANTLY by any damage taken/absorbed (with a mana shield for example).

**Comment by Agarwenlol** [comment]
Hi
http://www.warcraftmovies.com/movieview.php?id=95023

42:12

full damage even with intercept on target with fear.

**Comment by teddys** [comment]
42:12 gforce targets totem and uses fear on the totem ---> shaman gets the other fear which ofc doesnt break instantly

2:40 swifty does the exact same thing... targets totem, uses fear on totem

pls did u even read what is reported here

**Comment by Zerixx** [comment]
As it seems, this issue has already been fixed. Tested on live, cannot replicate.
