### ISSUE TITLE
Shattrath Flasks

### ISSUE THREAD

**Issue by jakebob** [FeenixServerProject/Archangel_2.4.3_Bugtracker#2050]
Shattrath Flask of Blinding Light (35717), 
Shattrath Flask of Fortification (32898)
Shattrath Flask of Mighty Restoration (32899)
Shattrath Flask of Supreme Power (32900)
Shattrath Flask of Relentless Assault (32901)
Shattrath Flask of Pure Death (35716)

These flasks fade when you release and become a ghost. They should not fade at all, the effect is just supposed to be disabled.

**Comment by Nick91** [comment]
Regarding the abuse possible with Shattrath Flasks: http://www.wow-one.com/forum/topic/94267-aa-band-aid-fix-for-double-flasking
