### ISSUE TITLE
[Core][Movement][Critical] Visual positioning in player movement

### ISSUE THREAD

**Issue by Schaka** [FeenixServerProject/Archangel_2.4.3_Bugtracker#2059]
The communication between the client and server is flawed in a way that makes players appear elsewhere than they really are for other players.
A lot of the time, especially for players with higher latency, this causes some players being unable to attack others. 
This is also an issue for people trying to attack crowd controlled targets, especially feared targets, as the positioning is completely false and the crowd controlled player can either not be attacked at all ends up unattackable once he has been stunned during a crowd control (e.g. Charge, Intercept, Cheap shit, Hammer of Justice etc).

I found an explanation how this issue occurs and how it can be fixed here:
<b>Edit: Advertising other servers is not allowed on the tracker either </b>

**Comment by teddys** [comment]
#believe 2015

**Comment by Agarwenlol** [comment]
pls fix

**Comment by Nzzoth** [comment]
I would like to remind you that this is not a forum there's no use of bumping issues. Clearing useless comments.
