### ISSUE TITLE
[AOE vs OUT of line of sight mechanics][MAJOR]

### ISSUE THREAD

**Issue by deztbestsp** [FeenixServerProject/Archangel_2.4.3_Bugtracker#2073]
After the last 2 major patches we got the AOE/OUT of LOS mechanics broken:

1) Current Situation - You can cast and use AOE abilities in areas and ignoring pillars and line of sight. Examples - Blizzard, Mass Dispell, Concecration, Frost Trap, Every Totem. If you use any of those spells arround a pillar or other kind of object that obscures your line of sight it ignores it.

Repro guide:

For example you go to Arathi Basin (starting/buffing zone) and the gate ahead of you is closed.. You go as close as possible to it, while in the mean time you see behind it when you tilt your camera. At current time you can cast spells like Mass Dispell and Blizzard behind it  (on the other side of that wall) although that spot is not in your character's line of sight. Same principle applies to Arena pillars.

2) Desired situation: You can cast and use AOE abilities in area's ONLY line of sight to you. Examples - Blizzard, Mass Dispell, Frost Trap, Every Totem, Flare and every other AOE ability in general.

P.S. I repeat this report is about being able to place an AOE in area out of your line of sight, so dont comment cluelessly.

**Comment by warlee** [comment]
Issue is back once more after 2 years.

**Comment by takza** [comment]
Was the issue always here or was it fixed at one point?
