### ISSUE TITLE
[Shaman][Ability]Totems falling under the map and getting stuck into pillars

### ISSUE THREAD

**Issue by lolmacestun** [FeenixServerProject/Archangel_2.4.3_Bugtracker#2074]
1) Current Situation - At current times you can put your totems inside of pillars or forcing them to drop under the map, effectively making them ignore any kind of line of sight or object obscuring vision and allowing the shaman and his teammates be affected by the friendly totems on both sides of the pillar, while at the same time enemies are being slowed in the same manner. This is a huge abuse for the shaman and his teammates mainly their opponents are unable to destroy the totems. Effectively the friendlies to the shamans are able to break CC the whole arena game.

2) Desired Situation - Pillars, Walls and the Floor and supposed to be solid objects and abilities shouldn't be able to pierce through it and affect players on the other side, or for objects to fall through the ground. A totem should only affect players which are on the same side where it is and are inside of its effect range. Just as Consecration or Flare should only affect players which are on the side of the pillar which it is cast on and not ones on the other side. 

Video Proof: As you can see at 5:25 - the totems is a few yards away from him while being slightly out of LoS and Neilyo is free of the slow effect.
http://www.youtube.com/watch?v=fT_aZfg9AP0

**Comment by Tudi** [comment]
confirmed fix, could not bug it out in my tests
