### ISSUE TITLE
[Arena PvP Major] Pillars are not solid objects

### ISSUE THREAD

**Issue by lolmacestun** [FeenixServerProject/Archangel_2.4.3_Bugtracker#2076]
1) Current Situation - Area of Effect spells like Concecration, Frost Trap or Flare currently disregard the existance of pillars or objects in arena. For example using one of those spells on one side of the pillar will instantly affect players on the other side - getting them into combat or pulling them out of stealth. 

2) Desired Situation - Pillars are solid objects which obscure the vision of any kind of spells and such AOEs shouldn't affect enemies which are out of the line of sight of the caster at that moment.

**Comment by Forcy** [comment]
Confirmed by Involve
