### ISSUE TITLE
Shadow Labyrinth Mob Stun Bug

### ISSUE THREAD

**Issue by Filce** [FeenixServerProject/Archangel_2.4.3_Bugtracker#2179]
Report ID:

Reporter Name: Squic

Date/Time: 02:21 sunday /16/ december/2012

Error Severity: 

Zone/Instance: Shadow Labyrinth (Normal)

What type of error occurred?: Mob Glitch

What was the actual result vs. the expected result?:  
Expected result was that the mob desheeps but instead he started spaming murmur's sonic wave ability constantly with no damage only stun towards all group members .

Can the error be repeated? If so, what are the steps?: 
Dont know , i have seen this only once and never heard of this type of glitch 

Link to Video Evidence: no video only screen shot of the ocurance , down below

Comment : Hope you examen the mob and see what could have triggered the glitch and fix it 
wish you best of luck .

![WoWScrnShot_121612_022059](https://f.cloud.github.com/assets/3054120/15365/1c8bf2d2-4749-11e2-8fa5-b3103dfd0fa9.jpg)

**Comment by devastator** [comment]
Closing. Please comment here if the bug still occurs
