### ISSUE TITLE
[Paladin][Items][Spells]Enlightenment/Light's Grace

### ISSUE THREAD

**Issue by jakebob** [FeenixServerProject/Archangel_2.4.3_Bugtracker#2190]
Curent situation: Enlightenment (ID 43837) from Crystalforge Raiment 2/5 (Paladin T5) is overwriting the talent effect from Light's Grace (ID 31834)

Expected results: Both Enlightenment and Light's Grace should be able to be on the caster at the same time.

http://www.youtube.com/watch?v=5azvIG_IYBA&feature=youtu.be

Steps to reproduce:

Create Blood Elf Paladin:

.lvlup 69
.learn 750 (plate skill)
.additemset 627 (Crystalforge Raiment)
.add 18970 2 (Ring of Critical Testing 2)
.learn 27136 (Holy Light Rank 11)
.learn 31836 (Light's Grace Rank 3)
.mod mana 100000

Equip the items and cast holy light, it should be possible to have both 'Enlightenment' and Light's Grace up at the same time.

*Edited by Anelith 12/29*

**Comment by devidao** [comment]
Fixed, coming soon on PTR

**Comment by Nzzoth** [comment]
Fix confirmed on PTR.

**Comment by Nzzoth** [comment]
Fix confirmed on PLTR.

**Comment by Forcy** [comment]
Fixed in patch 14.22
