### ISSUE TITLE
[Instance][UBRS]Cleint crash upon engaging Blackhand Assassin

### ISSUE THREAD

**Issue by seventhguard** [FeenixServerProject/Archangel_2.4.3_Bugtracker#2310]
A firend (bloodelf hunter) and i (troll hunter) were running Upper Blackrock Spire and we repeatedly crashed (game not server) after engaging the Blackhand Assassin.  We attempted this pull 5 or 6 times before giving up and it crashed each time, and on a couple pulls it actually crashed twice if we managed to log back in before the character died or the npcs reset.  the error report stated:

ERROR #132 (0x85100084) Fatal Exception
Program:    C:\Program Files (x86)\World of Warcraft\wow.exe
Exception:  0xC0000005 (ACCESS_VIOLATION) at 0023:00466FE3

The instruction at "0x00466FE3" referenced memory at "0x0C22E20C".
The memory could not be "read".

Blackhand Assassin link: http://old.wowhead.com/npc=10318#comments

**Comment by roblockster** [comment]
Doesn't seem like this fix has gone live. I just did UBRS yesterday and the same issue occured.
