### ISSUE TITLE
[Game Objects][NPCs][Quests] Ethereum Prison Bugs

### ISSUE THREAD

**Issue by devastator** [FeenixServerProject/Archangel_2.4.3_Bugtracker#2350]
http://www.wowwiki.com/Ethereum_Prison

"When a Prison is opened, either a friendly mob will come out and give rep, or a level 71 non-elite hostile mob will come out."
## 

**[Fixed]** **Issue 1)** The Friendly mobs that come out of the prisons do not give reputation. Only the Cenarion Expedition Druid gives reputation as intended. 

Possible Friendly Mobs that may come out:
Rescued Cenarion Expedition Druid (ID: 22810) - gives 500 reputation towards Cenarion Expedition (faction ID: 942)
Rescued Lower City Brute (ID: 22811) - gives 500 reputation towards Lower City (faction ID: 1011)
Rescued Sha'tar Vindicator (ID: 22812) - gives 500 reputation towards The Sha'tar (faction ID: 935)
Rescued Consortium Dealer (ID: 22813) - gives 500 reputation towards The Consortium (faction ID: 933)
Rescued Sporeggar Scout (ID: 22814) - gives 500 reputation towards Sporeggar (faction ID: 970)
Rescued Keepers of Time Custodian (ID: 22815) - gives 500 reputation towards Keepers of Time (faction ID: 989)
## 

"The hostile mobs have a guaranteed drop of [Ethereum Prisoner I.D. Tag] which can be turned in as a repeatable quest for 250 rep. They also have a guaranteed drop of a uncommon (green-quality) or better item. The uncommon items are level 70 BoE's, however there is a chance of BoP rare (blue-quality) items."

**[Fixed]** **Issue 2)** The hostile mobs do not have guaranteed drop of uncommon or better item. They should drop either: Uncommon Level 70 BoE item or Rare item. The loot tables of the mobs should include: specific Rare item for each mob with ~10% drop rate, and shared Rare items that all the mobs can drop with ~1-2% drop rate for each shared item. The shared and specific items can be seen here: http://www.wowwiki.com/Ethereum_Prison. Item IDs for the shared items: 31925, 31926, 31927, 31928, 31929, 31935, 31936, 31937, 31938, 31939
At the moment the mobs are dropping only their specific Rare item, but they do not drop Uncommon items nor their shared Rare items.
Hostile Mobs:
Armbreaker Huffaz (ID: 20784)
Fel Tinkerer Zortan (ID: 20785)
Forgosh (ID: 20788)
Gul'bor (ID: 20786)
Malevus the Mad (ID: 20790)
Porfus the Gem Gorger (ID: 20783)
Wrathbringer Laz-tarash (ID: 20789)
## 

**[Fixed]** **Issue 3)** The Ethereum Prisons do not respawn. They spawn only on server restart.
Ethereum Prisons Game Object IDs:
184418, 184419, 184420, 184421, 184422, 184423, 184424, 184425, 184426, 184427, 184428, 184429, 184430, 184431
## 

**[Fixed]** **Issue 4)** Quest: Stasis Chambers of Bash'ir http://www.wowhead.com/quest=10974/stasis-chambers-of-bashir
The mob that spawns from Stasis Chamber Alpha - Thuk the Defiant ID: 22920 http://old.wowhead.com/npc=22920 is friendly. He should be hostile in order to be killable for receiving the quest item for the quest.
## 

**[Fixed]** **Issue 5)** Quest: The Mark of the Nexus-King http://www.wowhead.com/quest=10976 - same as 4 - the mobs that spawn from Stasis Chambers are friendly. They should be hostile.
Mobs that spawn from Stasis Chambers:
Matron Li-sahar (ID: 22825) http://old.wowhead.com/npc=22825
King Dorfbruiser (ID: 22826) http://old.wowhead.com/npc=22826
Gorgolon the All-seeing (ID: 22827) http://old.wowhead.com/npc=22827
Trelopades (ID: 22828) http://old.wowhead.com/npc=22828
Solus the Eternal (ID: 20888) http://old.wowhead.com/npc=20888
## 

**[Fixed]** **Issue 6)** Same as 3 - the Stasis Chambers do not respawn.
Stasis Chambers Game Object IDs:
184595, 185461, 185462, 185463, 185464, 185465, 185466, 185467
## 

**Issue 7)** Quest: Stasis Chambers of Mana-Tombs http://www.wowhead.com/quest=10977
The Stasis Chamber in Mana Tombs is completely missing.
Screenshots: http://www.atlasmod.com/phpBB3/download/file.php?id=124
http://www.atlasmod.com/phpBB3/download/file.php?id=123
Game object: Mana-Tombs Stasis Chamber ID: 185519 should be spawned at loc: xyz 8 -223 -1 inside Mana Tombs (heroic). Opening the chamber should spawn NPC, and complete the quest.
## 

**Issue 8)** Shaffar's Stasis Chamber is completely missing. Opening the Chamber should spawn Yor - optional boss in Mana Tombs (heroic) http://www.wowhead.com/npc=22930/yor
Video: http://www.youtube.com/watch?v=ztFkxu772is Yor @ 4:00
Game object: Shaffar's Stasis Chamber ID: 185522 should be spawned at loc: xyz -236 -15 17 inside Mana Tombs (heroic). Opening it should spawn Yor ID: 22930 (Optional Boss)

**Comment by Traiamakke** [comment]
jeah, confirm: 1 and 7 still not working!

**Comment by repae1f** [comment]
1 and 7 still not working!

**Comment by devastator** [comment]
Issue 1 Fixed. Soon on PTR

**Comment by lajhar** [comment]
Fix confirmed on PTR.

**Comment by lajhar** [comment]
Fix confirmed on PreLive

**Comment by lajhar** [comment]
On live as 15.9
