### ISSUE TITLE
[Quest][BEM] Ride The Lightning - Scalewing Serpent don't cast Lightning Strike

### ISSUE THREAD

**Issue by Tsuikana** [FeenixServerProject/Archangel_2.4.3_Bugtracker#2368]
Unable to complete the quest "Ride The Lightning" because the scalewing serpents don't cast lightning strike at all

**Comment by devastator** [comment]
Fixed. Soon on PTR

**Comment by lajhar** [comment]
Fix confirmed on PTR.

**Comment by lajhar** [comment]
On live as 16.0
