### ISSUE TITLE
[Priest][T5 Set] 2-piece bonus bugged

### ISSUE THREAD

**Issue by Fleischi** [FeenixServerProject/Archangel_2.4.3_Bugtracker#2391]
<b>Current situation:</b> Efficiency procs if you have a heal and an overheal component. It does not proc if you only have 100% overheal.

<b>Desired situation:</b> Efficiency should also proc on complete overheal. This means that Efficiency (id 37595) should also be triggered if the target is already at full hp (making you heal 0).

<b>How to reproduce:</b>
Create a Priest
.levelup 69
.learn 25213
.additemset 665
Equip two pieces of the set.
Heal yourself with any rank of Greater Heal.

Observe that Efficiency (id 37595) will never proc if you have full health. It should proc though.

<b>Sources:</b>
Sources can be found in the comments.

**Comment by Stoniz** [comment]
More to backup the bug
http://www.wowhead.com/spell=37594/heal-refund#comments:id=333634
http://www.wowhead.com/itemset=665/avatar-raiment#comments:id=20403:reply=24200

**Comment by Fleischi** [comment]
closing. works as intended now. thanks :)
