### ISSUE TITLE
[Quest=11007] Kael'Thas and the Verdant Sphere

### ISSUE THREAD

**Issue by devastator** [FeenixServerProject/Archangel_2.4.3_Bugtracker#2395]
http://www.wowhead.com/quest=11007

Current Situation: The cut scene when you complete the quest is not presented at all. 
Also Blessing of A'dal buff http://www.wowhead.com/spell=35076 is casted on A'dal himself instead of being casted on the players.

Expected Result:
Upon completing the quest, the following appears to everyone in Shattrath City:

(emote) Silence descends upon Shattrath. (emote)
(emote) A'dal's thoughts invade your mind. (emote)
A'dal yells: Kael'thas Sunstrider has been defeated by < name > and (his/her) allies 
A'dal yells: The time to strike at the remaining blood elves of Tempest Keep is now. Take arms and let A'dal's song of battle empower you! 

*At this point A'dal casts A'dal's Song of Battle http://www.wowhead.com/spell=39953 on all players in range for the spell*
*Kael'thas Sunstrider spawns http://old.wowhead.com/npc=23054/kaelthas-sunstrider*

Kael'thas Sunstrider yells: Your monkeys failed to finish the job, naaru! Beaten but alive... The same mistake was not made when we took command of your vessel. 
Kael'thas Sunstrider yells: All for what? Trinkets? You are too late. The preparations have already begun. Soon the master will make his return. 
Kael'thas Sunstrider yells: And there is nothing you or that fool, Illidan, can do to stop me! You have both served me in your own right - unwittingly. 
Kael'thas Sunstrider yells: Lay down your arms and succumb to the might of Kil'jaeden! 

*Kael'thas despawns*

http://www.wowwiki.com/Quest:Kael%27thas_and_the_Verdant_Sphere

**Comment by Forcy** [comment]
Applied to Live with Patch 12.0
