### ISSUE TITLE
[Paladin][Aura] Sanctity Aura and Seal Of Command

### ISSUE THREAD

**Issue by d1verse** [FeenixServerProject/Archangel_2.4.3_Bugtracker#2399]
Sanctity Aura doesn't increase the damage from seal and judgement of command.

**Comment by devidao** [comment]
Fixed, coming soon on PTR

**Comment by Nzzoth** [comment]
Fix denied on PTR.

**Comment by Nzzoth** [comment]
Fix denied on PTR.

**Comment by anaaz** [comment]
Fix confirmed and applied to live with Patch 15.2

**Comment by dangreenberggit** [comment]
This issue partially fixed in regards to Seal of Command, but issue still exists in regards to Seal of Blood #3483 (referencing both Seal of Command and Seal of Blood)
