### ISSUE TITLE
[Core] [Tier 4] [Gruul the Dragonkiller] - Cave In and Shatter

### ISSUE THREAD

**Issue by Triokon** [FeenixServerProject/Archangel_2.4.3_Bugtracker#2454]
## A. Cave in:

The damage increase for [Cave In](http://www.wowhead.com/spell=36240) is not calculated correctly.
As you know, Gruul grows from time to time, giving him a stacking buff that increases physical damage by 15%. "Growth also affects Cave In." ([wowwiki.com](http://www.wowwiki.com/Gruul_the_Dragonkiller#Abilities))
The problem is that the increasing damage is totally out of proportion for Cave In.

I did some testing. The inital damage of Cave In (0 Growths) should be 2700 physical damage every 3 seconds.
My character was naked and I had ~ 200 armor, and the first Cave In damage was 2665 damage. Therefore, this works fine.

Now a list for the recorded damage of Cave In with every stack of Growth.

0 Growths (0%): 2665
1 Growths (15%): missing data
2 Growths (30%): 4503 (69% increase)
3 Growths (45%): 5603 (110% increase)
4 Growths (60%): 6824 (156 % increase)
5 Growths (75%): 8162 (206 % increase)
6 Growths (90%): 9623 (261 % increase)
7 Growths (105%): 11201 (320% increase)
8 Growths (120%): 12901 (384% increase)
.....

As you can see, Cave In is out of proportion with the damage increase by Growth.
Cave In's damage should be increased by 15% for every stack of Growth applied on Gruul.
## B. Shatter:
- "Unfriendly"/"Invalid Target" problem is properly reported here: https://github.com/FeenixServerProject/Archangel_2.4.3_Bugtracker/issues/1557

**Comment by aleksandr073** [comment]
Shatter does not work again
