### ISSUE TITLE
[Addons][Arena] Optimizing Gladdy for Archangel 2.4.3

### ISSUE THREAD

**Issue by warlee** [FeenixServerProject/Archangel_2.4.3_Bugtracker#2646]
Download:
http://addons.iradei.eu/admin/data/files/others/gladdy.rar

Current situation: 
The addon doesnt show Trinket Cooldown/DR timers and enemy talents(spec).

Desired situation:
Addon should show Trinket Cooldown/DR timers and enemy talents(spec).

**Comment by Schaka** [comment]
By now, everyone uses an addon for trinket times and most widely spread TBC addons rely on GladdyTrinketUsed addon messages. It's been generally accepted by many servers and is "the old solution AT used".

I implemented this for TBC, if there was any interest, it could be used on Feenix fairly easily:
https://github.com/Looking4Group/L4G_Core/commit/f7859c0ab0a866ae1d94c1e6acfa6fe7d98bf3ee
