### ISSUE TITLE
[Shaman][Spell] Far Sight makes you unable to see npc's until relog

### ISSUE THREAD

**Issue by Greatless** [FeenixServerProject/Archangel_2.4.3_Bugtracker#2677]
After using Far Sight, when you move away from where you stood when you casted it, you will not be able to see any npc's or mobs or other players.
Casting it at your feet again will give you vision of nearby entities, but moving away from that spot will make you unable to see entities again.
Interactions with other players such as Trade won't work.

**Comment by devidao** [comment]
Could not reproduce
