### ISSUE TITLE
[Spells][Warrior] T5 TANK Warrior 4/5 Bonus not working as intended

### ISSUE THREAD

**Issue by jinchez** [FeenixServerProject/Archangel_2.4.3_Bugtracker#2695]
4 piece set bonus: You have a chance each time you are hit to gain 200 haste rating for 10 sec.

This is not working as intended, or at least how blizzard implemented this back in retail TBC. Meaning, You have no chance of getting the haste rating bonus on a block how it is now. You should have the equal chance on block to get the haste rating bonus as on another hit (ofc not on dodge/parry/miss). At the moment, tested for an evening, it only procs on non-blocks. I guess it's easy to see for people who are investigating this.. Also got confirmation on this from other tanking warriors having the 4 set bonus.

Maybe there is something wrong with the on-hit part, because I've heard the same story with the on-hit from the darkmoon card: vengeance card trinket.

**Comment by Tudi** [comment]
Rejected. Here is the proof that it does proc on partial blocked attacks : http://i.imgur.com/uQ7Jxmk.jpg
I added 2 GM commands to my local server to get 100 block chance and 100 chance to trigger "Destroyer Armor 4P Set bonus"

**Comment by devastator** [comment]
It indeed does proc on partially blocked attacks as intended
