### ISSUE TITLE
[Item Set] Shaman Tier 6 - Skyshatter Regalia

### ISSUE THREAD

**Issue by Doppelmoral** [FeenixServerProject/Archangel_2.4.3_Bugtracker#2753]
http://database.wow-one.com/index.php?itemset=684

**Definition:**
*2 pieces: Whenever you have an air totem, an earth totem, a fire totem, and a water totem active at the same time, you gain 15 mana per 5 sec, 35 spell critical strike rating, and up to 45 spell damage.*

**Current situation:** 
2/8 Skyshatter Regalia doesn't work at all.

**Expected situation:** 
Whenever the shaman does have *4 totems* up at a time Totemic Mastery (http://database.wow-one.com/index.php?spell=38443) becomes active.

**Comment by NipSie** [comment]
Xanis commented on 9 Aug 2014
Fixed, soon on PTR. ^

**Comment by Forcy** [comment]
Fix applied with patch 10.9
