### ISSUE TITLE
Stealth mechanics

### ISSUE THREAD

**Issue by teddys** [FeenixServerProject/Archangel_2.4.3_Bugtracker#2767]
Everything is wrong, perception is not working, eyes in arena are not working, vanish is not working

http://www.twitch.tv/sylvanaslolx/b/401819144
23:35

I don't know how to write a proper report about this.

**Comment by teddys** [comment]
still a thing...

**Comment by teddys** [comment]
Perception seems to be working at the moment. Rest is still bugged.

**Comment by teddys** [comment]
why is this closed, its not fixed.

**Comment by teddys** [comment]
I am getting found by druids, that are right in front of me and I do not see them untill they get me out :)))

**Comment by dudeks5** [comment]
still bugged you cant find druids in arena but they almost every time open you so something must be wrong .. rogues detection talents still doesnt work
