### ISSUE TITLE
Warrior Devastate ability is bugged.

### ISSUE THREAD

**Issue by coryletler** [FeenixServerProject/Archangel_2.4.3_Bugtracker#2813]
Devastate is kind of being divided into 2 separate actions; the damage and the sunder.  The damage is sometimes done and yet the sunder is "dodged".  I can't speak to the vice versa effect.  It may be that if the damage is dodged the sunder is automatically dodged as well, I haven't been able to ever detect the damage not being done and the sunder being applied.  

Hope this helps.

**Comment by Zerixx** [comment]
This is now actually working as intended. I was unable to replicate this issue on live.
