### ISSUE TITLE
Pet Disorientation

### ISSUE THREAD

**Issue by ohrerbohrer** [FeenixServerProject/Archangel_2.4.3_Bugtracker#2821]
Pet disorientation is to Long, a Wl could use sacrifice while summoning the fel hunter... disorientation should be 5 sec Long. Here u cannot sacrifice while summoning fel hunter cause it's too long

**Comment by devidao** [comment]
Issue not available on PTR, at least i could not reproduce it. Summoning Disorientation duration is 5 seconds and you can use Sacrifise just before new pet arrives.
