### ISSUE TITLE
Faerie Fire (feral) Bugged => Talent tree bug

### ISSUE THREAD

**Issue by Brucelats** [FeenixServerProject/Archangel_2.4.3_Bugtracker#2824]
When you take talent Faeire fire (feral) after you log out or dc, when you return to game it's no longer selected in Tree panel, but you have the skill, but problem is that skill no longer count as taken, so your overall feral talents are 1 less then it should be. Basicaly it is not much of a problem later on, but on start for example for mangle, you would need 1 level more to get if you take Faerie fire skill and log out.

**Comment by Forcy** [comment]
A fix for this has been applied to Live with Patch 12.0
