### ISSUE TITLE
[Core][Spell] Windfury Totem buff issue

### ISSUE THREAD

**Issue by boez** [FeenixServerProject/Archangel_2.4.3_Bugtracker#2865]
Current situation: When I drop a Windfury Totem I-V(http://database.wow-one.com/index.php?spell=25587) there is an issue on the proc of Windfury granted on my partners weapon. If Windfury procs on a white-hit the damage is instant and working as intended. However if Windfury procs on a special attack(Hamstring for example) you can see the swirls around the character telling you Windfury has procced, but the actual damage is stored and released on your next white-hit.

This opens up for abusing, since you can basically store a Windfury-proc and release it whenever you want.

Desired situation: When Windfury procs on a special-attack the extra swing granted by Windfury should proc right away together with the swirl-animation.

**Comment by Forcy** [comment]
Applied to Live with Patch 12.0

**Comment by Nick91** [comment]
This issue is closed but not fixed on the live server, please open the issue and re-evaluate the fix.
