### ISSUE TITLE
(ITEM) Force Reactive Disk

### ISSUE THREAD

**Issue by Ropeos** [FeenixServerProject/Archangel_2.4.3_Bugtracker#2870]
Reporter:Kravichka,lvl 70 Tauren Warrioir

This item is crafted from an engeneering recipe that drops in Molten Core.

External/Releated Links: http://www.wowhead.com/item=18168#created-by-spell
 
Date/Time:June 13th 17:37

Error Severity:great

Issue:The electrical charges dont proc usual from blocks as they should.Or they take a lot of time to proc and do any kind of dmg to an enemy player or creature.

Character:Kravichka,lvl 70,Tauren Warrior (Protection)

**Comment by devastator** [comment]
Works mostly as intended. The charges proc properly, they are doing AoE damage in 5 yards radius, if by any chance the target hitting is more than 5 yards away it wont take damage, but just visual effect. This is blizzlike, you can check wowhead comments.
However fixed an issue that the shield gets broken on any attacks, not just blocked ones. Soon on PTR.

**Comment by anaaz** [comment]
Fix applied to live with Patch 15.2
