### ISSUE TITLE
[PvP] Resilience not lowering Spell Critical Chance (Major)

### ISSUE THREAD

**Issue by Exodikai** [FeenixServerProject/Archangel_2.4.3_Bugtracker#2882]
I stumbled upon this issue while attempting to test various PvP related talents. I have NO idea how PvP casters, especially mages have not noticed this yet, and it is more likely that they have and have just chosen not to report it...

Issue: Resilience does NOT lower chance to be crit by spells.

Client One: .additem 18970 2 (Ring of +50% spell crit)
.learn 27209 (shadowbolt)

Client Two: Make macro .cast 46534
will add +35 resil every time you hit it. Spam until at 100% less chance to be crit, it is about 4,000 resilience.

On client one, spam shadow bolt on client two. Notice, every single spell crits, though there should be a 0% chance to crit because of resilience reduction.

As you can imagine this is major and game breaking, especially for mages. There is no way that a veteran mage of archangel has not noticed this yet. There really is no excuse for this to still be unreported at this point.

**Comment by Zerixx** [comment]
This has been fixed on 11/13/16.

**Comment by teddys** [comment]
there was nothing to fix ???
