### ISSUE TITLE
Lord Ahune

### ISSUE THREAD

**Issue by hellmann** [FeenixServerProject/Archangel_2.4.3_Bugtracker#2912]
Was trying to find the quest givers for Lord Ahuner so i can summon hin but can find them! Will they be added so i can kill Lord Ahuner?

**Comment by kildrazien** [comment]
Isle of Quel'Danas is now released on the server. Ahune should be as well.

**Comment by kildrazien** [comment]
The fire festival has begun, and Ahune should spawn in Slave pens now. Please look into this
