### ISSUE TITLE
[Quest][NPC][Westfall] The Defias Brotherhood - The Defias Traitor

### ISSUE THREAD

**Issue by Psykosa** [FeenixServerProject/Archangel_2.4.3_Bugtracker#2922]
The NPC www.wowhead.com/npc=467 for the quest www.wowhead.com/quest=155 takes far too long to despawn once he reaches the destination in Moonbrook.  After someone completes the quest, it takes over 45 minutes for him to despawn and respawn back at Sentinel Hill, that's when I logged out, so I don't know the actual timer.  
He also runs faster than he should, which runs the chance of him despawning and having to wait for him all over again.  The Defias Traitor is supposed to go at a brisk walking speed.

**Comment by devastator** [comment]
Couldn't reproduce the despawn issue - npc despawns properly. Fixed the run speed. Soon on PTR

**Comment by lajhar** [comment]
Fix confirmed on PTR.

**Comment by lajhar** [comment]
Live as 16.1
