### ISSUE TITLE
Login and realmlist

### ISSUE THREAD

**Issue by tiduspt89** [FeenixServerProject/Archangel_2.4.3_Bugtracker#2944]
There is an issue with login, If your suggested realm is indeed Archangel you can enter by clicking accept else on the click on view realm list all realms will appear as offline.
There's a lot of ppl affected by this problem, even if u can login with acc, the third image is what happens if your account is suggest to archangel u can get in, but if u go into realm list 3 pic is what happens.
This happened after last night "reboot" or something on the servers.

<a href='http://postimage.org/' target='_blank'><img src='http://s22.postimg.org/5pt1zfflt/lvl60.jpg' border='0' alt="lvl60" /></a><br /><a target='_blank' href='http://postimage.org/'>image hosting flickr</a><br /><br />

<a href='http://postimage.org/' target='_blank'><img src='http://s15.postimg.org/5fqsbkma3/realmlistafter.jpg' border='0' alt="realmlistafter" /></a><br /><a target='_blank' href='http://postimage.org/app.php'>lightshot free download</a><br /><br />

<a href='http://postimage.org/' target='_blank'><img src='http://s15.postimg.org/vyimbrzrf/archlogin.jpg' border='0' alt="archlogin" /></a><br /><a target='_blank' href='http://postimage.org/app.php'>screenshot windows 7</a><br /><br />

Thanks for your time

**Comment by devastator** [comment]
Outdated
