### ISSUE TITLE
[Druid] Main ActionBar bugged in Travel Form

### ISSUE THREAD

**Issue by ghost** [FeenixServerProject/Archangel_2.4.3_Bugtracker#2955]
Current Situation: The main ActionBar while in travel form uses the Bear Form[stance1] bar while showing the Caster form[nostance] bar.
Desired situation: Main ActionBar in travel form uses caster form bar aswell as showing caster form bar.

Note: It's only when using keybindings, when clicking, it works as intended.

**Comment by lajhar** [comment]
Cannot reproduce, probably client sided.
