### ISSUE TITLE
[RACIAL][PERCEPTION] Perception not granting enough stealth level

### ISSUE THREAD

**Issue by warlee** [FeenixServerProject/Archangel_2.4.3_Bugtracker#2961]
Current situation: Perception is not granting enough stealth detection
Desired situation: Perception should grant following stealth detection
Racial : PERCEPTION    +50 points of stealth detection, equivalent to 10 levels.

This issue is strongly connected to stealth mechanics which are broken in general
https://github.com/FeenixServerProject/Archangel_2.4.3_Bugtracker/issues/2767

**Comment by Forcy** [comment]
Confirmed by Involve

**Comment by teddys** [comment]
I played 10 arenas against alliance rogue and i got sapped by him having perception on in all of the 10 games --> idk what are you exactly confirming here.

The stealth on the other hand is approximately 10 times more broken than it was say 2 months ago. I get randomly faerie fired from stealth by druids that are 20 yards away from me all the time.

**Comment by Forcy** [comment]
Make a new report
