### ISSUE TITLE
[Druid][Spell] Nature's Grace is not reducing cyclone cast time.

### ISSUE THREAD

**Issue by derpfury** [FeenixServerProject/Archangel_2.4.3_Bugtracker#2964]
http://database.wow-one.com/index.php?spell=16880

If you have the balance talent Nature's Grace and you crit with a spell it should reduce the cast time of your next spell by 0.5 seconds. This should work for all spells but it does not reduce cyclone cast time.

**Comment by devidao** [comment]
Fixed, coming soon on PTR

**Comment by Nzzoth** [comment]
Fix confirmed on PTR.

**Comment by lajhar** [comment]
On live (15.6)
