### ISSUE TITLE
[Quests] UBRS Key quest: Seal of Ascension

### ISSUE THREAD

**Issue by Obiken** [FeenixServerProject/Archangel_2.4.3_Bugtracker#2967]
When attaining the quest Seal of Ascension (http://www.wowhead.com/quest=4743) you are provided with the container (http://www.wowhead.com/item=12339). This should contain 2 items Unadorned Seal of Ascension (http://www.wowhead.com/item=12323) and Orb of Draconic Energy (http://www.wowhead.com/item=12300).

When I attain the quest it does not contain the orb as per the screenshot included. It is therefore not possible to complete the quest which is required to get the key to UBRS. From scanning the forums it seems this has worked previously.

I have dropped and retaken quests numerous times, cleared cache and WTF folders.

![image](https://f.cloud.github.com/assets/5015915/800371/ec0df5d4-ed87-11e2-9839-6e8d8804d845.png)

**Comment by Forcy** [comment]
Applied to Live with patch 10.9
