### ISSUE TITLE
[Shaman][Arena][Enhancement]Weapon Imbues[Gamebreaker]

### ISSUE THREAD

**Issue by shazeface** [FeenixServerProject/Archangel_2.4.3_Bugtracker#2982]
Several bugs related to weapon imbues (windfury, frostbrand) etc. and arena. The ones I've encountered so far is:

- Weapon imbues need to be removed and re-applied upon entering arena or they will not work, albeit they show on your buff screen, your teammate will be able to inspect you and see that they arent up. Whether or not this is intended is something I cant remember, but imbues should always show if they are up or not on your buff screen, not make you ask your partner or guess.

- The most crucial one is how equipping another weapon in an arena game will remove the imbues originally on your weapons.

To give an example, a shaman enters arena with two merciless gladiator's cleavers. One with windfury, the other with frostbrand imbue. The shaman's hp drops and he decides to heal himself, he has macrod his healing wave or lhw with /equip macros, allowing him to equip healing mace+shield when healing, then having another macro to swap back to the 1h's. 

The result of this action is that the imbues dissappear from the weapons (still showing at your buff's however) and you now do not have the imbues anymore in the middle of an arena game.

Will update on the issue

Edit: After testing some arena games, it appears that the frostbrand does not suffer from the same bug when you replace weapons in arena. Needs to be confirmed

**Comment by Salce** [comment]
*Fix confirmed on PLTR*

**Comment by Rakanish** [comment]
Sorry to say this but this is still not fixed regardless of said fixes. Please look into this!

**Comment by teddys** [comment]
fixed long time ago
