### ISSUE TITLE
[Script] [Creatures] Fungal Giant  - Zangarmarsh

### ISSUE THREAD

**Issue by Clodagh** [FeenixServerProject/Archangel_2.4.3_Bugtracker#300]
Reporter Name: Clodagh and Glurf

External Link: http://www.wowhead.com/npc=19734#abilities

Date/Time: 07/02/2012

Error Severity: -

Zone/Instance: Quagg Ridge, Zangarmarsh

What type of error occurred?:

Fungal Giants did not spawn Unstable Mushroom Primer

What was the actual result vs. the expected result?:

We tested all the spawns and none of them summoned mushrooms.

Can the error be repeated? If so, what are the steps?: Engage in combat with a Fungal Giant at Quagg Ridge in Zangarmarsh

Are you able to provide visual evidence?:

http://i1154.photobucket.com/albums/p528/glurfnsozz/WoWScrnShot_020712_224401.jpg

Please detail your character’s race, class, and items (optional):

Tauren Druid and Orc Rogue

**Comment by devastator** [comment]
Fixed with patch 15.0
