### ISSUE TITLE
Instant abilities have a cast time

### ISSUE THREAD

**Issue by darth-zeke** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3038]
Instant abilities have a cast time which means no avoidance or block for a tank if they use abilities.  

Whenever a player uses an instant cast ability, it is considered them casting for a short period of time which causes a tank to lose their avoidance and block when they use almost any tank ability (doesn't include heroic strike or cleave).  This also means that even an uncrushable tank can still be crushed which makes tanking a lot more unstable than it should be.  

This has been tested on several occasions on a tank with 103% dodge, parry, miss, and block combined without the use of shield block.  I can tank hundreds of mobs and they can never hit me;  As soon as I use a single ability, even shield block, I would die instantly because I would get hit by several mobs that shouldn't have hit me.

**Comment by lajhar** [comment]
Not an issue anymore
