### ISSUE TITLE
Solanian's Belongings

### ISSUE THREAD

**Issue by Keencom** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3039]
I searched for the Post Found one but it was closed and it was said that it would work but it doesnt.

U can activate the looting on the Scroll of Scurge but there isnt anything to loot

**Comment by denith969** [comment]
I still cannot loot the quest item "Solanian's Scrying Orb" http://www.wowhead.com/search?q=Solanian%2527s+Scrying+Orb+(Item) for quest "Solanian's Belongings" http://www.wowhead.com/quest=8330/solanians-belongings

Without this quest completed, I can't pick up the quest from Outrunner Alarion in Dawning Lane as you leave the starting zone.
