### ISSUE TITLE
[NPC] [Nagrand] Mag'har Captive not reset after escort quest

### ISSUE THREAD

**Issue by neo2k12** [FeenixServerProject/Archangel_2.4.3_Bugtracker#304]
After finishing the Quest 'The Totem of Kar'dash', which involves escorting a captive out of Sunspring Post in Nagrand, he doesn't despawn. 

He just knees on the street:
http://www.abload.de/img/wowscrnshot_020812_03maxcm.jpg

This leads to the problem that he doesn't respawn in the hut for other players to take the quest:
http://www.abload.de/img/wowscrnshot_020812_033fb93.jpg

I suppose this happens with the Alliance version of this quest too.

**Comment by devastator** [comment]
https://github.com/FeenixServerProject/Archangel_2.4.3_Bugtracker/issues/3785
