### ISSUE TITLE
[Mage][Talents] Clearcasting Removed By Wand

### ISSUE THREAD

**Issue by gitScald** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3061]
After obtaining the Clearcasting buff from the Arcane Concentration talent, shooting a wand at a target will cause the mage to lose the Clearcasting buff.

What is supposed to happen: Clearcasting should not be removed by using a wand.

Steps to reproduce:
Create a mage, level him/her to 70, equip a wand a acquire the Arcane Concentration talent, and start shooting at a target until the Clearcasting buff is acquired. Another wand shot will take off the Clearcasting buff.

**Comment by Forcy** [comment]
Fix applied with patch 10.9
