### ISSUE TITLE
A Slow Death

### ISSUE THREAD

**Issue by Jubeithos** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3064]
The Fel Glands that are suposed to drop from Beasts around Shadowmoon Valley are not droping and the quest is not completeable.

http://www.wowhead.com/quest=11020/a-slow-death

This quest is a part of the Netherwing dailies and important : (

**Comment by ziliosa** [comment]
I found a problem pertaining to this same quest. I can loot it and feed the npcs, but after the npcs are fed, it crashes after a few seconds. I get credit and everything, it just crashes after that.
