### ISSUE TITLE
[Glitch] Shadowmoon Valley farming

### ISSUE THREAD

**Issue by fearoth** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3067]
Zone/Instance: Shadowmoon Valley, Ruins of Karabor

While at Ruins of Karabor, or similar places. You can just simple pull huge groups of mobs while standing on a hight the mobs can't reach. From there, they will just stand and watch you while you AOE them all.

Example: http://postimg.org/image/nooyw353d/

NOTE!! This is not an action of glitch abusing, just and act to show off the glitch :)

**Comment by lajhar** [comment]
Fixed on live
