### ISSUE TITLE
[CLASS][DRUID] T5 4-piece does not work for Alliance

### ISSUE THREAD

**Issue by Javastorm** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3079]
I received the fourth piece of the set yesterday and tested it immediately after, but it does not work at all. My damage is nearly the same as it was without the set bonus, as there is no 10% Starfire damage increase after casting Moonfire or Insect Swarm. The most I have noticed is 3-5% of a difference. This suggests it's partially working, which is strange. It was apparently fixed three months ago as shown here-> https://github.com/FeenixServerProject/Archangel_2.4.3_Bugtracker/issues/2661

Why doesn't this work properly? Is it because of a recent patch?

Current Situation: The Balance Druid Tier 5 four-piece bonus does not apply 10% damage to Starfire with a Moonfire or Insect Swarm application for Alliance Night Elf Druids. It seems to be working for Horde Tauren Druids.

Desired Situation: The Balance Druid Tier 5 four-piece bonus applies the correct 10% damage bonus to Starfire upon application of Moonfire or Insect Swarm for Alliance Night Elf Druids.

**Comment by alpheratzz** [comment]
Bump.
I obtained the 4th piece of the set a couple of days ago and tested it a bit on Orgrimmar dummies. The situation is exactly the same as the one described in the firt post, with exception of me being the Horde tauren druid. The damage increase of Starfire on targets affected by Insect Swarm or Moonfire isn't 10%, but is around 3-5%.
After a little testing without any gear but those four tier 5 pieces i've come to assumption that the 10% bonus might be applied to the base Starfire damage only; still, it's only an assumption.
Fix this issue, please.
Regards, Novick.

**Comment by Brucelats** [comment]
Dont get it how hard can it be to fix that god damn bug. Jesus christ!

2015-09-20 16:19 GMT+02:00 Blazhukas <notifications@github.com>:

**Comment by alpheratzz** [comment]
Bump.

**Comment by corcaroli** [comment]
Bump

**Comment by lajhar** [comment]
Fix confirmed on PTR.

**Comment by iluusj** [comment]
So when this will be fixed? Fix confirmed on PTR in august, but still no live. Will it ever be live? Or moonkin is hopeless?

**Comment by ghost** [comment]
@iluusj applied to Live today. Issue tracker being updated is just delayed.

**Comment by lajhar** [comment]
On live (15.8)
