### ISSUE TITLE
Cannon-type enemies can auto-attack

### ISSUE THREAD

**Issue by Kadoba** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3088]
Cannon-type enemies, such as fel cannons and crust busters, are suppose to remain stationary and only cast projectiles at the player. However, In between projectile casts they are able to get a free auto-attack off if the player is close enough. This behavior causes them to have substantially higher DPS than normal.

**Comment by devastator** [comment]
Issue will be fixed in multiple fixes conserning creature ai for specific tbc zones
