### ISSUE TITLE
Innervate - Cyclone

### ISSUE THREAD

**Issue by harbie** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3096]
Current Situation: Target casts innervate, druid cyclones the target and continues to Regen mana from innervate.

Desired Situation: Target casts innervate, druid cyclones the target and the druid should NOT regen mana from innervate.

**Comment by Rakanish** [comment]
This is just not true, I can clearly remember from my TBC days (as will any other druid who played back then) that Cyclone WILL stop mana regen from innervate. Open this back up!

**Comment by Rakanish** [comment]
Follow up: taken from this thread: http://www.arenajunkies.com/topic/5682-druid-warrior-2v2-a-comprehensive-guide/
"Cyclone the druid during innervate, it won't tick then."

**Comment by Rakanish** [comment]
Why is this closed?

**Comment by Rakanish** [comment]
bump....

**Comment by Lederi** [comment]
@Rakanish: from your own source http://www.arenajunkies.com/topic/5682-druid-warrior-2v2-a-comprehensive-guide/page__st__40#entry45685
> [quote name='Jaristus']Cyclone the druid during innervate, it won't tick then.[/QUOTE]
Wrong. 

so please do not reopen it.

**Comment by Rakanish** [comment]
It is hard for me to find any evidence, but theres a thread on arenajunkies (not actually written during TBC though), that backs up my claim.
http://www.arenajunkies.com/topic/218919-innervatecyclone-243/

would be nice if someone could come with supporting evidence.
