### ISSUE TITLE
Druid Vengful Gladiator dragonhide gloves maim skill null

### ISSUE THREAD

**Issue by keendream** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3119]
The "equip: Causes your maim ability to interrupt spellcasting and prevent any skills in that class from being casted for 3 seconds" does not work.

**Comment by Nzzoth** [comment]
Reproduction guide:
You need 2 characters.
On druid:
.gm off
.gm visible on
.t test
.learn all_myspells
.additem 33671 and equip it
// enter cat form and keybind 1: Mangle 2: main

On Shaman:
.gm off
.gm visible on
.t test
.learn all_myspells
// Keybind 1: Lightning bolt 2: Chain lightning

Duel (if same faction) and put 1 combo point on the shaman with your druid.
Tab to shaman and cast lightning bolt.
Quickly tab to druid and cast main (keybind 2)
Quickly tab to shaman and notice how Lightning bolt and chain lightning didn't go on a 3 second cooldown.

**Comment by devidao** [comment]
Fixed, coming soon on PTR

**Comment by Nzzoth** [comment]
Fix confirmed on PTR.

**Comment by lajhar** [comment]
On live (15.3)
