### ISSUE TITLE
Coilfang Elite (Lady Vashj encounter) don't cleave

### ISSUE THREAD

**Issue by tarnum** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3123]
Current situation: Coilfang Elites from the Lady Vashj encounter do not cleave, making their positioning absolutely trivial.
Desired situation: frontal arc cleave for over 7.5k on plate 
http://www.wowwiki.com/Lady_Vashj_%28tactics%29

**Comment by devastator** [comment]
Appears that the issue no longer exists
