### ISSUE TITLE
[PvE][BLACK TEMPLE] High Nethermancer Zerevor

### ISSUE THREAD

**Issue by warlee** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3130]
Current Situation: High Nethermancer Zerevor does not refresh his Dampen Magic debuff.
Desired Situation: High Nethermancer Zerevor should refresh his Dampen Magic debuff. 

Spell ID: http://www.wowhead.com/spell=41478

**Comment by Nzzoth** [comment]
Greetings,

Do NOT close issues on your own staff members will do that for you.

Kind regards, Nzzoth.

**Comment by warlee** [comment]
I am closing issue because it no longer exists...
