### ISSUE TITLE
Scrolls should not stack with buffs of the same type

### ISSUE THREAD

**Issue by Fleischi** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3134]
__Current:__
All Scrolls stack with every buff. The only exception I know of is the single target Arcane Intellect buff and the intelligence scroll.

__Desired:__
[Scroll of Stamina](http://database.wow-one.com/index.php?search=scroll+of+stam) should not stack with [Power Word: Fortitude](http://database.wow-one.com/index.php?search=power+word%3A+fort#spells) and [Prayer of Fortitude](http://database.wow-one.com/index.php?search=prayer+of+for#spells).
[Scroll of Intellect](http://database.wow-one.com/index.php?search=scroll+of+int) should not stack with [Arcane Intellect](http://database.wow-one.com/index.php?search=arcane+int#spells) and [Arcane Brilliance](http://database.wow-one.com/index.php?search=arcane+bri#spells).
[Scroll of Spirit](http://database.wow-one.com/index.php?search=scroll+of+spi) should not stack with [Divine Spirit](http://database.wow-one.com/index.php?search=divine+spi#spells) and [Prayer of Spirit](http://database.wow-one.com/index.php?search=prayer+of+spi#spells).
Scrolls should stack with everything else (like totems and whatever else). This is ok.

__References:__
From [wowwiki(18:19, October 25, 2007)](http://www.wowwiki.com/Scroll?oldid=939793):
>Scroll buffs do not stack with player buffs that effect the same stat.

From [wowhead(2007/09/21)](http://www.wowhead.com/item=27498#comments:id=156055):
>They stack with any and all buffs EXCEPT player given buffs that buff a single stat.
>So the intellect, spirit and stamina scrolls cannot stack with Arcane Intellect, Divine Spirit or Fortitude respectively.
>But you can have a Str, Agi and Armour scroll equipped without any regard to normal raid buffs, elixirs and flasks.

**Comment by Forcy** [comment]
Fixed live with patch 12.7
