### ISSUE TITLE
[Hunter][Ability] Steady Shot doesn't work properly.

### ISSUE THREAD

**Issue by Skyquake** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3170]
Greetings! As you know, Steady Shot should cause base weapon damage PLUS 508, and as i can see from my attacks, auto-shot does the same amount of damage as steady shot.Thing is, Steady Shot is one of hunter's main abilities and this bug decreases our dps by a lot.

**Comment by Cadwalader** [comment]
Steady shot says "Weapon damage + 595"  My average with Valenos Longbow (damage 130-242) is 510 (min 455 max 548)

How can the maximum damage be less that the modifier?
I do less damage as an almost purple hunter @ 70 that a level 67 Mage

The original post stated that auto shot does the same amount of damage as steady shot.  This is true. Steady shot has no value.
