### ISSUE TITLE
Druid Talent Celestial Focus

### ISSUE THREAD

**Issue by xSr** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3174]
Druid Talent Celestial Focus is occasionally causing the Druid to get "Starfire Stun" debuff while shapeshifting into Cat Form. Unfortunately I failed to reproduce the issue with specific conditions which are causing the issue. But I can confirm it only happens while switching into Cat Form and could be reproduced by switching into Cat Form Multiple times with 3/3 points on Celestial Focus.

![starfire stun](https://f.cloud.github.com/assets/2965844/1624118/4e620880-56bd-11e3-8a55-c132d6d611ee.jpg)

**Comment by devidao** [comment]
Could not reproduce on PTR.

**Comment by Nzzoth** [comment]
Unable to reproduce on PTR, if this is still the case please make a comment and post a proper reproduction.
