### ISSUE TITLE
Character auto rotation on channeled spells 

### ISSUE THREAD

**Issue by Asgerd** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3186]
Current situation: Character auto rotation on channeled spells like drain life and drain mana doesn't work. When you start channel spell enemy can just step a side and cancel your cast.
Desired situation: Character should always follow the enemy while casting channeled spells.

**Comment by teddys** [comment]
why are all these issues closed?
THIS IS NOT FIXED

**Comment by Nzzoth** [comment]
Hello Teddys, the following issues you're refering to are closed because they're duplicates of this issue.

**Comment by devidao** [comment]
works as intended

**Comment by teddys** [comment]
not anymore .. in fact it has been bugged again since like 2 months .. ill post a video tomorrow

**Comment by devidao** [comment]
I am waiting video

**Comment by teddys** [comment]
Sorry I forgot. It must have been issue on my part or it was just an issue that disappeared again. Tested it now again and it is working correctly. No idea what happened.

**Comment by Nzzoth** [comment]
Incase it reappears make sure to clear cache and retry it, incase after cache is cleared it doesn't work bump us here. For the time being closed.
