### ISSUE TITLE
AV buffs - the main reason why the battleground is so broken

### ISSUE THREAD

**Issue by faustrech** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3194]
Well those tower buffs that affect players make the matches very long and annoying, I looked into the issues of AV and I couldn't find this one hope the report is usefull.

Players get the buffs that only NPC's are supposed to take increasing health and dmg + 25% dmg. Makes ally bridge impossible to pass since avg defending player is like a raid boss and can solo 3 opposite members.

**Comment by bigeef** [comment]
Still going on. War masters and marshals buffs shouldn't affect players. This wouldn't be such a problem if it worked the same for both factions as a way of encouraging more defensive games. 

The horde war masters stand in the base next to Drek, as they should, de-spawn when their tower has been burned and never re-spawn.

For some reason the alliance marshals each stand inside their bunker (except for the stonehearth one which is in balinda's room) and re-spawn about 5 minutes after they die. They don't de-spawn when their bunker is burned.

It should be pretty easy to change the alliance marshals so they behave like the horde ones.

**Comment by devastator** [comment]
https://github.com/FeenixServerProject/Archangel_2.4.3_Bugtracker/issues/3743
