### ISSUE TITLE
[PRIEST][MASS DISPELL] Mass dispell dispelling more than one debuff.

### ISSUE THREAD

**Issue by warlee** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3197]
Current situation: Mass dispell dispells 2 debuffs.

![massdispell](https://f.cloud.github.com/assets/1371072/1753323/6a6b3862-663a-11e3-8e17-840aa79c89cf.jpg)
Desired situation: Mass dispell should dispell only 1 debuff.

Another issue is that even though I resisted dispell on Ice Block it still got removed.

**Comment by Nzzoth** [comment]
Greetings,

Do NOT close issues on your own staff members will do that for you.

Kind regards, Nzzoth.

**Comment by warlee** [comment]
Issue is fixed.
