### ISSUE TITLE
[PRIEST][PAIN SUPPRESSION] PS not granting enough dispell resistance.

### ISSUE THREAD

**Issue by warlee** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3198]
Current situation: Pain Suppression doesnt grant extra 65% chance to resist dispell.
Desired situation: Accordingly to the tooltip and database Pain Suppression should give extra 65% chance to resist.
http://database.wow-one.com/index.php?spell=33206

**Comment by Forcy** [comment]
Applied to Live with Patch 12.0
