### ISSUE TITLE
[ability]The Mortar: Reloaded

### ISSUE THREAD

**Issue by Lederi** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3238]
The Goblin Engineering ability The Mortar: Reloaded is not in game.

[wowwiki](http://www.wowwiki.com/The_Mortar:_Reloaded?oldid=1229023)

> This ability was taught by the Goblin Engineering Trainers, and was gained when the recipe for Goblin Mortar is learned.

**Comment by devastator** [comment]
Fixed. Soon on PTR

**Comment by lajhar** [comment]
On live (15.8)
