### ISSUE TITLE
Starshards spell coefficent 

### ISSUE THREAD

**Issue by nameuser11** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3241]
Starshards does not scale with your spell damage at all atm, it is supposed to receive 171% of your +spelldmg. I couldn't find anything on wowwiki but http://wow.allakhazam.com/forum.html?forum=243&mid=117856662766076986 just an example of people saying it's 171%.

**Comment by Tudi** [comment]
I can confirm that the fix from goran works ( if value is correct ). In my DB this fix was not applied by default
UPDATE spell_bonus_data SET direct_bonus = 0, dot_bonus = 0.3429 WHERE entry = 10797;

**Comment by devastator** [comment]
Fix went Live with patch 12.0
