### ISSUE TITLE
Beast-tamer shoulders doesn't work

### ISSUE THREAD

**Issue by MrRauff** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3264]
Item: http://database.wow-one.com/?item=30892
As hunter with Shoulders of the Hidden Predator (for same AP scaling to pet)
![normal shoulders](https://f.cloud.github.com/assets/2413671/2140356/597493da-934b-11e3-96df-805f63eb2985.jpg)

With beast-tamer's shoulders:
![beast tamer shoulders](https://f.cloud.github.com/assets/2413671/2140369/864ab196-934b-11e3-97bb-f418e7574b33.jpg)

Melee should be 3% higher. 
Crit should be 2% higher.
Nothing is changed by equipping beast-tamers shoulders.

**Comment by devidao** [comment]
Could not reproduce, maybe it has been fixed.

**Comment by MrRauff** [comment]
it was silently fixed over a year ago

**Comment by Nzzoth** [comment]
Closed.
