### ISSUE TITLE
False attempt to cast when using channeling spells

### ISSUE THREAD

**Issue by Involve** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3278]
**Current Situation:** 
As of now it occurs that channeling spells are falsely casted because the server considers them as casted in ALL scenarios, even if the player was on a global cooldown or, for AoE channeling spells, the area was not in range or line of sight.
It is noticeable that the "channeling"-animation of the character is working as intended, however there is no spell animation or damage dealt while the global cooldown is still getting triggered.

**Desired Situation:**
Channeling spells should not trigger the global cooldown if the player is unable to cast a spell. 

**Reproduction Guide:**
1.
Create a mage
.learn 27085 (Blizzard rank 7)
- attempt to cast the spell on an area which is out of range
- notice that even though the spell is not getting casted (which is correct), the global cooldown is still being triggered (which is not intended)

2.
Remain on the mage
.learn 38704 (Arcane Missiles rank 11)
.m mana 100000
- continuously spam the ability
- notice how "clipping" the channeling spell sometimes causes faulty skips where you still trigger the global cooldown while you are not casting.

See also: #3206

**Comment by Forcy** [comment]
Fixed with patch Patch 11.12. Closing

**Comment by teddys** [comment]
where is this fixed? its definetly not fixed on live
