### ISSUE TITLE
[Core][Spells] Band of the Eternal Defender

### ISSUE THREAD

**Issue by Anelith** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3283]
**Current situation:** The item proc spell=35078 *Band of the Eternal Defender* from the ring item=29297 *Band of the Eternal Defender* doesn't stack with the Priest talent *Inspiration*

**Expected results:** spell=35078 should stack with 14893/15357/15359 **Note:** 14893/15357/15359 **should not** stack with each other

**Create Undead Priest:**

.levelup 69
.learn 15363 (Inspiration rank 3)
.learn 34119 (Greater Heal Rank 7)
.add 18970 2 (Ring of Critical Testing 2 (for 100% Critical))
.add 29297
.mod hp 1000000
.mod mana 100000
.t sw

Engage the big three until you get Band of the Eternal Defender and cast Greater Heal right after on your self, observe that:
spell=35078 *Band of the Eternal Defender* gets overwritten by
spell=15359  *Inspiration*

**Or simply do the following:**
.cast 35078 with .cast any 14893/15357/15359 - Observe that both spells are replacing each other due to same icon

**Comment by xmontex** [comment]
buffs stack
