### ISSUE TITLE
Darkmoon Card: Vengeance effect not proccing correctly

### ISSUE THREAD

**Issue by diogofcosta** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3292]
Hi there,

I hope i'll be able to explain myself in a way that you'll understand perfectly the bug.

So the item Darkmoon Card: Vengeance (id: 31858) has the effect Aura of Vengeance (id:39444) which is supposed to have a 10% chance on physical or spell hit to return holy damage, according to my observations everything is working as intended except when the damage is blocked it won't proc the effect, which is not blizzlike, if you block the damage (partially or entirely) it SHOULD be able to proc the aura of vengeance returning the damage.

Hopefully this is an easy and quick fix.

Reproduction Guide:

Get a character to level 70, get the trinket, get blocking set and start tanking one mob or to see it better a lot of mobs, you'll see that despite being attacked the item won't proc unless you dont block it.

**Comment by devastator** [comment]
Fixed. Soon on PTR

**Comment by lajhar** [comment]
On live (15.3)
