### ISSUE TITLE
[Warrior][Tier 5 Set Bonus] Tier 5 2-set bonus gets overwritten by "Inspiration"

### ISSUE THREAD

**Issue by Kampvognen** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3298]
Hi!

As a protection warrior and main tank I'm healed a lot, and after getting 2 tier 5 pieces, I noticed (with the help from a priest healer from guild) that the "100 shield block value" overwrites the inspiration buff that comes from priest getting a critical hit on healing.

We tried it out in a raid, and out of raid.
Has been confirmed on other warriors.

Hope you can find it!

/kamp

**Comment by Forcy** [comment]
Appears to be fixed.
