### ISSUE TITLE
[Class][Mage][Priest] Spellsteal not affected by Pain Suppression

### ISSUE THREAD

**Issue by Involve** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3299]
**Current Situation:** 
The Mage ability Spellsteal (ID: 30449) is not affected by dispel mechanics like additional resist chances granted by Pain Suppression (ID: 33206)

**Desired Situation:**
The Mage ability Spellsteal (ID: 30449) should be affected by dispel mechanics just as all other dispel abilities, which include but aren't limited to Purge (Rank 2 ID: 8012), Dispel Magic (Rank 2 ID: 988) and Devour Magic (Rank 6 ID: 27496).

**Reproduction Guide:**
In order to reproduce the issue, you will need two clients.

Launch the first client and create a Priest.
.levelup 69
.t arena
.gm off
.gm visible on
.learn 33206 (Pain Suppression)
.m mana 10000

Launch the second client and create a Mage.
.levelup 69
.t arena
.gm off
.gm visible on
.learn 30449
.m mana 10000

Tab to the first client and cast Pain Suppression onto yourself. Now switch to the second client and attempt to spellsteal the buff. Notice how it requires very little effort to spellsteal the buff, while Pain Suppression should grant the target a 65% chance to resist Dispels.
With the command .cooldown you can reset all cooldowns of your abilities. Make use of this to reset the cooldown of Pain Suppression and repeat the scenario a couple of times. It becomes very clear that the high success rate of the spellsteal ability is not a coincidence, but rather unintended.

I haven't had the chance to figure out whether the issue lies within Pain Suppression or rather Spellsteal, as my sample is limited to those two spells only and i did not test Spellsteal on any other abilities with empowering dispel protection or the like.

**Comment by Forcy** [comment]
Applied to Live with Patch 12.0
