### ISSUE TITLE
[Item][Stratholme] Scarlet Cannonball

### ISSUE THREAD

**Issue by Nihilia** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3300]
**Issue:**
Scarlet Cannonball [Item ID: 12973] in Stratholme drop with very high rates from several types of mobs (notably Skeletal Berserker [ID:10391] which has like 100% drop) and annoys the looting process since its unique item and you can only carry one at a time. 

**How it should be:**
Scarlet Cannonball shall only be acquirable by looting Cannonball Stack [Object ID: 176215] in Stratholme, which is right near the cannon it should be used for.

**Comment by devastator** [comment]
Fix went Live with patch 12.0
