### ISSUE TITLE
[Mage][Spell] Conjure Food Rank 7

### ISSUE THREAD

**Issue by Nihilia** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3320]
**Issue:**

[Conjure Food [Rank 7]](http://database.wow-one.com/index.php?spell=28612) adds 20 cinnamon rolls instead of intended 10.

**Comment by warlee** [comment]
Really?

**Comment by warlee** [comment]
Revision as of 01:10, December 25, 2007 by Foxbot
This item is conjured by mages using the rank 7 spell Conjure Food. A level 60 mage will create 10 charges per cast, the number of charges increases by 2 each level up to a maximum of 20 (at level 65).
