### ISSUE TITLE
[PVE] Expertise against Bosses

### ISSUE THREAD

**Issue by Lederi** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3344]
**Issue:** 
The Expertise CAP against Bosses is 20 .

**How it should be:**
The Expertise CAP against Bosses should be 26.

Reference [WoWWiki:](http://www.wowwiki.com/Formulas:Expertise?oldid=1300554) 
>Introduced in patch 2.3 to replace Weapon Skill, each point of expertise will reduce the chance that a mob will dodge or parry your attack by 0.25%.
>...
>Expertise against Bosses
The dodge and parry chances for boss-mobs is currently disputed, but combat parses tend to point at around 6.5% dodge and as high as 12-15% parry.[citation needed] Assuming 6.5% dodge and 15% parry, a player would need 26 expertise (about 104 expertise rating) to negate a boss' dodge chance, and 60 expertise (roughly 236 expertise rating) to prevent parries.

**Comment by devastator** [comment]
https://github.com/FeenixServerProject/Archangel_2.4.3_Bugtracker/issues/3384
