### ISSUE TITLE
Blood Furnace Normal - Gate @ 2nd Boss

### ISSUE THREAD

**Issue by Srodri** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3351]
Hello,

Bug:
After killing the second boss (Broggok) in Blood Furnace Normal, the gate on the back side of that room remains closed.

The "back side" is the one where you originally enter the room.

Fix:
After killing the boss, the gate should reopen.

Screenshot:
http://s28.postimg.org/k5djqmcr1/Wo_WScrn_Shot_050414_162602.jpg

2nd Boss:
http://www.wowhead.com/npc=17380

**Comment by devidao** [comment]
atm there is no gates at all

**Comment by devastator** [comment]
Fixed. Soon on PTR

**Comment by lajhar** [comment]
Fix confirmed on PTR.

**Comment by lajhar** [comment]
Fix confirmed on PreLive

**Comment by lajhar** [comment]
On live as 15.9
