### ISSUE TITLE
Simultaneous usage of non-stackable cooldowns

### ISSUE THREAD

**Issue by Involve** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3363]
***Current Situation:***
As of now, cooldowns such as Haste Potions (ID: 22838), Destruction Potions (ID: 22839) or Insane Strength Potions (ID: 22828) can be used at the same time when involving the components in a macro.
***This also applies to all other sorts of Potions as well as Conjured Managems or Healthstones!***

***Desired Situation:***
It should not be possible to use the named items at the same time, as they are supposed to share a two minute cooldown within their respective group (Potions and Conjured Items incl. Dark Runes and Demonic Runes).
Please note that the cooldown of two minutes does correctly trigger if you simply use one of the items - merely the instantaneous usage of several ones is the issue here.

***Reproduction Guide:***
In order to reproduce this issue you will require one client

Client A
Create any class
.gm off
.gm visible on
.add 22838 20 (Haste Potion)
.add 22839 20 (Destruction Potion)
.add 22828 20 (Insane Strength Potion)

Make a macro with the following content:

/use Haste Potion
/use Destruction Potion
/use Insane Strength Potion

now bind the macro to any action bar and press it once. Notice that instead of using only the Haste Potion, which would be the desired effect as it is named first in the list, you instead use all three of them.

For a better illustration of the issue please check following clip:
https://www.youtube.com/watch?v=2dHdpv88lfg

**Comment by Forcy** [comment]
Fixed Live with patch 12.7
