### ISSUE TITLE
[Engineering] Wrong skill requirements for Hardened Adamantite Tube, Felsteel Stabilizer and Khorium Power Core

### ISSUE THREAD

**Issue by wlfbck** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3381]
All 3 of these should require engineering 340 to learn, not 350 as it is currently. First link is a comment from wowhead saying that they changed it with 2.3, second link is a screenshot from atlasloot. The other 3 show all of them being 340 right now on the live-servers (which ofcourse could've changed later, but i doubt it and it coincides with the other two things).

http://www.wowhead.com/spell=30309#comments:id=186526
http://i.imgur.com/tM1O2Eq.jpg
http://www.wowhead.com/item=23785#created-by-spell
http://www.wowhead.com/spell=30309#recipes
http://www.wowhead.com/item=23786#created-by-spell

**Comment by Salce** [comment]
*Fix confirmed on PLTR*

**Comment by devastator** [comment]
Fix went Live with patch 11.10
