### ISSUE TITLE
Darkwater crocolisk empty skinning 

### ISSUE THREAD

**Issue by powme56** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3386]
When you skin Darkwater crocolisk in black morass 3/4 of the time you wont get anything and the corpse just vanish, it's annoying when you know it's the best spot to farm knothide leather

**Comment by Salce** [comment]
*Fix confirmed on PLTR*

**Comment by devastator** [comment]
Fix went live with patch 11.10
