### ISSUE TITLE
[Dungeon][Tempest Keep][Al'ar] Al'ar flame buffeting during Quill phase

### ISSUE THREAD

**Issue by Arastrus** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3396]
I know there are issues related but as I was encouraged to open new issues for the new developer team and this contains new information I open a new issue.

Basically what happens is the following: When flying upwards to his Quill phase he sometimes flame buffets the whole raid over and over again.
This is caused by his aggro reset and then someone overaggroing him, making Al'ar targeting a different target than his previous tank. A workaround is to not apply dots (-> no thread produced while tank can't produce aggro) and immediately stop casts when Al'ar is flying up (-> you will have a bad time if you see a shadowbolt flying after him!).

Expected behaviour: Al'ar is not using Flame Buffet during Quill phase.
Observed behaviour: Al'ar is using Flame Buffet during Quill phase in case someone else than the previous tank reaches #1 on the threat table.

Can be fixed by excluding flame buffet during Quill phase or wiping thread when Al'ar flies down, not when he flies up.

Kind regards,
Shariva

**Comment by devidao** [comment]
Could not reproduce, i think it is already fixed

**Comment by Arastrus** [comment]
Can confirm, fix is live since about 9 months. Your predecessor didn't like
github :P
Am 03.04.2016 11:13 schrieb "Deividas" <notifications@github.com>:
