### ISSUE TITLE
[Dungeon][Black Temple][Trash] Trash ring drop rates non-blizzlike (especially caster rings)

### ISSUE THREAD

**Issue by Arastrus** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3403]
Overall: While melee rings drop very often, healer rings in a somehwat blizzlike amount caster rings are very rare drops on Black Temple trash. With the increased drop chance on Bonechewer Shield Disciples you could somewhat compensate it but with the recent hotfix this is gone.

If you compare the drop rates (http://www.wowhead.com/item=32527#dropped-by to http://database.wow-one.com/?item=32527#dropped-by, second not adjusted to the hotfix yet) you can only question what is going on there.

Expected behaviour: Caster rings from Black Temple trash have a somewhat blizzlike drop rate, leading to 1-2, sometimes 3 caster rings per dungeon clear.
Observed behaviour: While missing a drop rate on 10 types of trash mobs completely (dropped by 45 different mob types on Archangel compared to 55 on retail) the drop rates on the other mob types are too low, leading to guilds experiencing up to 8-10 dungeon clears without a single caster ring.

Thanks for having a look at it,
Shariva

**Comment by Salce** [comment]
**Fix confirmed on PLTR**

**Comment by devastator** [comment]
Fix went Live with patch 11.12
