### ISSUE TITLE
Hunter Steady Shot DMG

### ISSUE THREAD

**Issue by Alowen** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3405]
As far as I have noticed Steady Shot doesn't work well. As Steady Shot description says it does weapon BASE DAMAGE (which is around 270 in my case) PLUS 593, which is around ~750. And I don't think that Steady Shot is doing Base DMG+593, instead just 593, cause numbers I have seen so far are not even close to ~750 even on target with very low armor, besides my AP. Had chat with guild hunters as well, and some other people that play hunters, they seem to think the same.

Wowwiki/Wowhead:
"Base weapon damage is a weapon's inherent damage, displayed in the weapon's tooltip."
"A steady shot that causes base weapon damage plus 593. Causes an additional 175 against Dazed targets."

**Comment by devastator** [comment]
Seems to work properly when tested. Try switching two bows with big difference in the base damage, you will notice the difference.
