### ISSUE TITLE
[Quest] The Missing Diplomat

### ISSUE THREAD

**Issue by Blackpearl1** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3414]
The Quest "The MIssing Diplomat" can't be finished because the NPC "Tapoke "Slim" Jahn" is not despawning/he stays in the rear of the Menethil Stronghold.
But he must stay/respawn in the Menethil Tavern.

**Comment by celyse** [comment]
This issue is happening for me as well, Tapoke never spawns at the inn. No new info but the reason I'm posting is because there is a changelog post from January 13 stating that this quest can now be completed, but it is most definitely still bugged.

**Comment by Paraffine** [comment]
Just to let you guys know that Tapoke "Slim" Jahn is still bugged. He still stays in the rear of the Menethil Stronghold and there's no way of interacting or beating him to continue the quest.
