### ISSUE TITLE
[Warrior] [Spell Reflection] 

### ISSUE THREAD

**Issue by Piratelol** [FeenixServerProject/Archangel_2.4.3_Bugtracker#342]
Now time to update this Thread!
1st (in continuation of warlee's post): 
- Warriors are now available to reflect AoE spells, such as Frost Nova and Cone of Cold. 
- Warriors are now available to reflect single target on-hit-effects, such as Mace Stun (don't know if it is from Deep Thunder or Talent Tree mace spec) and various poisons from Rogues, e.g. crippling poison, deadly poison etc. etc.
  2nd:
- The prioritizing of spells (talking of multiple casters) to spell reflect is bugged, badly. Let me give you an example: I am against a frost mage, his pet and himself are casting frost bolts, and in this instance, i am casting Spell Reflection (even before the spells are casted), and neither of the frost mage's or the frost pet's frost bolt is getting reflected, only the Ice Lance, which he casts afterwards is getting reflected.
- Another example: same scenario, 2-3 casters are casting spells at you, a rogue is on you, and instead of reflecting the 2k crit damage fireball, a cripling poison is getting reflected. These examples are just to show how frustrating this bug can be :)
  3rd, and last:
- While you sit in a frost nova or a frostbite, and a frostmage casts a ice lance at you, it most likely will crit and deal massive damage. When you then spell reflect the ice lance, in this given situation, you also reflects the massive damage, and the crit, but as far as i remember, the massive damage and crit is only being handed out to players sitting in a frost nova/frostbite, and therefore the mage shouldn't be hurt a truckload? I actually have no clue of how spell reflection works in patch 2.4.3, but i experienced on the private server Arena Tournament, that the ice lances you reflect there, while sitting in a frost nova, only deals 200-300 damage to the mage himself. I don't know if Spell Reflection is ignoring all talent effects and such, and just reflects the intended damage which was intended to hurt the warrior, for example ~2k dmg ice lances, or to measure talents within the Spell Reflection, and just hit the mages for 200-300 damage with ice lances.

To sum up: 
- The problem with Spell Reflection, is that it locks itself onto a specific spell, that is being casted (or character, i don't know), and ignores all other spells. This way you still can't reflect spells mid-air, obviously, since Spell Reflection decides, during the spellcasting, which spell to reflect etc. etc. 
- An idea to fix this: This sounds pretty simple in my head, but i have no idea if it is hard in the "scripting-world". It could be made the way, that it ignores all casters/players/mobs, and only focuses on incomming spells, and reflects the first spell after Spell Reflection is casted, just like the frost/fire/shadow-reflection trinkets on the 1.12 realms? - Just like the way, when you can pop your frost-reflection trinket and walk over a Freezing Trap, and it gets reflected instantly?

I don't know if i covered every single "bug" of the Spell Reflection spell, so please comment if you had any other experiences with Spell Reflection, which wasn't intended. Also - If anyone have any knowledge about the above problems, please comment and show the staff of feenix what to fix in the upcoming changes, and please let us know where you have this knowledge from, so it's not random gibberish.

**Comment by 5ubzer0** [comment]
So apparently one of the bugs listed here slipped through the cracks :P. To be more exact, I'm talking about this one: Warrior is in frost nova -> He casts spell reflect -> Mage casts Ice Lance to fade it off -> Mage gets hit for ~2k, as if he was in nova as well (instead of getting hit for 200-300). I'm bumping this as it proves to be rather game-breaking in certain occasions.
