### ISSUE TITLE
[Core][Spell][Warlock] Soul Stone

### ISSUE THREAD

**Issue by Arastrus** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3423]
I am not 100% sure if this was possible on retail and if it is a flaw/abuse so please provide your feedback and please give an answer dear developers <3

Situation: After logging out and back in (intentional or not) you can reuse your soulstone. Even if it should not be possible I think it's minor as you could just port someone to a major city, soulstoning him with a warlock alt, and resummon him for the same effect.

Please help on this/provide info/make a statemtn dear devs.

Thank you,
Shariva

**Comment by devidao** [comment]
Looks like it is already fixed

**Comment by repae1f** [comment]
fixed one year ago

**Comment by Arastrus** [comment]
fixed
