### ISSUE TITLE
Ravenholdt reputation quest "Junkboxes Needed" missing

### ISSUE THREAD

**Issue by boksanns94** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3451]
Reporter Name: boksanns94
Reporter Character Name: Jebikres
Realm: Archangel 2.4.3
Date/Time: 11. August 2014. 19:14
Error Severity: Low
Zone: Alterac Mountains

What type of error occurred?:
The repeatable quest "Junkboxes Needed" is missing. The NPC "Fahrad" is still present, but he does not offer any quests. It is the only known way of gaining Ravenholdt reputation above Honored, and without it, no rep gain is possible beyond Honored.

What was the actual result vs. the expected result?:
I expected that a blue question mark would be floating atop of "Fahrad", but it wasnt there, and the quest was missing as well.

Link to Screenshot:
http://imgbox.com/RbbPtgT0

Please detail your character’s race, class, and items (optional):
Jebikres, Level 70 Undead Rogue, Combat talent tree

Message me ingame, or via e-mail "bigboks1@gmail.com", for any aditional information!

**Comment by devastator** [comment]
Fix went Live with patch 12.0
