### ISSUE TITLE
NPC casting-Iceblock interaction

### ISSUE THREAD

**Issue by mordero** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3452]
I recall quite intimately from an old farming route that caster mobs would close to melee range after casting into an iceblock (the result being immunity)

This does not seem to be the case, as I've recently tried to pick up an old farming route and this bug has left me kind of stranded, is this intended? 
NPCS include:
Ravaged Cadaver
Mangled Cadaver
among others near the service entrance of stratholme.

They just continue casting in to iceblock and/or attacking my water elemental (set to passive) that should not be on their threat table.

**Comment by devidao** [comment]
need reproduction guide of this
