### ISSUE TITLE
MAGE FROST [Talent Shatter] No 50% critical on frozen target

### ISSUE THREAD

**Issue by fpaolucci** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3455]
Hi all, 
I made a test run to verify the SHATTER critical chance on freezed target.
The target was every time freezed when hitted by frostbolt.

Talent shatter: Increases critical spell chance of all your spells against a frozen target

The research data are:
on 50 Frostbolt
33 Hits (66%)
13 Crits (26%)
4 Resist (8% too high with 3/3 Precision?!)

Char kknd (in the test naked):
crit rating: 0 
crit chance: 3.50
(seescreenshots for talent tree and char info)

Target: bonecracker (screenshot)
resilience: 344
crit reduction: 8.73

Making a short calculation should be:
3.50 +50.0 -8.73= 44.77

44.77 (teoric) vs 26 (real) !!! 
This is a huge bug that wastes pvp and arena for frost mages.
Please check this post and make a fix as soon as possible.

Thanks a lot.
![feenix archangel frost shatter bug target enemy resilience](https://cloud.githubusercontent.com/assets/5734746/3912550/43de0ff8-232c-11e4-9d73-03fc1f9e9e0b.jpg)
![feenix archangel frost shatter bug 1](https://cloud.githubusercontent.com/assets/5734746/3912553/43e49864-232c-11e4-96a4-ac7315a8149f.jpg)
![feenix archangel frost shatter bug 2](https://cloud.githubusercontent.com/assets/5734746/3912549/43dc8cd2-232c-11e4-9350-7a6317894362.jpg)
![feenix archangel frost shatter bug 3](https://cloud.githubusercontent.com/assets/5734746/3912548/43db41a6-232c-11e4-879c-a4b6e4c3bfed.jpg)
![feenix archangel frost shatter bug 4](https://cloud.githubusercontent.com/assets/5734746/3912551/43de4bd0-232c-11e4-9142-1fa7f05c9265.jpg)
![feenix archangel frost shatter bug 5](https://cloud.githubusercontent.com/assets/5734746/3912552/43e08f30-232c-11e4-88a4-5a0acf2faa2f.jpg)
![feenix archangel frost shatter bug 6](https://cloud.githubusercontent.com/assets/5734746/3912554/43f1ca5c-232c-11e4-907f-b6978265ed1d.jpg)

**Comment by Kaiitothewai** [comment]
Shatter is working fine.
