### ISSUE TITLE
[Warlock][Pet]Voidwalker-Suffering PvP

### ISSUE THREAD

**Issue by Johanes022** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3456]
Current situation:Voidwalker Suffering does not work in PvP.As tooltip says it should reduce enemy chance to hit by 10% (13% with talents) but it does nothing except applying debuff on the target(Taunting part of the tooltip works).

Desired situation:Suffering spell should reduce enemy chance to hit in PvP.

http://www.wowwiki.com/Voidwalker_%28warlock_minion%29
"Torment and Suffering have very limited use in PvP combat, but a Voidwalker isn't entirely useless.Suffering is not of significant use until level 63, when it reduces hit chances temporarily and could seriously hinder a rogue or other melee class trying to lock you or your allies down."

**Comment by devastator** [comment]
Could not reproduce the issue, appears to work properly, please provide more evidence
