### ISSUE TITLE
[Paladin][Item] Band of the Eternal Sage has a 0% proc rate for Paladin offensive spells

### ISSUE THREAD

**Issue by roblockster** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3463]
After testing Band of the Eternal Sage on a Paladin, I've noticed that Paladin offensive spells generally do not proc the ring effect. Below is information that the proc rate should be 10% on offensive spells (instead of ~0%).

Wowhead Band of the Eternal Sage proc info: http://www.wowhead.com/spell=35083
Elitist Jerks info: http://forums.elitistjerks.com/topic/16654-help-me-please/page-19#entry580326

After casting some spells hundreds of times, I've only been able to get the ring to proc from Exorcism casts, with the proc rate far less than what it is supposed to be. (Because seals are melee-based damage and are buffs rather than offensive casts I'm not including them in the numbers). Here is some of the information of my testing (all spells are spells that have hit). I'm also basing off of hit due to indications that it procs off of hits rather than casts (Wowhead comment: "Multiple hits with aoe spells such as Arcane Blast will have a chance to proc the spell with each HIT, which means that hitting 5 targets increases the chance to proc by 5 times."

Judgment: 150 hits - 0 procs (~0% proc rate)
Consecration: Over 6k ticks - 0 procs (~0% proc rate)
Enduring Judgment (Ashtongue Talisman of Zeal proc): Over 110 initial hits - 0 procs (~0% proc rate)
Exorcism: 40 hits - 2 procs (5% proc rate)
Hammer of Wrath: 30 hits - 0 procs (~0% proc rate)

While longer cooldowns made them difficult to test, the ring also has not procced yet for Holy Wrath or Hammer of Justice.

The end result is that for a Paladin casting as many offensive spells as possible to maximize Band of the Eternal Sage uptime, the uptime is about 0.2% against Demons/Undead targets, and 0% against other targets. Comparatively, most casters who have LESS offensive casts per minute on single targets demonstrate an uptime of about 15%. A figure of 15-25% is apparent upon looking at most sources including Elitist Jerks and Wowhead.

Here is a screenshot of recount and my proc-counting addon when the ring finally procced off of an Exorcism:

![image](https://cloud.githubusercontent.com/assets/7952671/4016285/9df65a74-2a32-11e4-99e2-975b62d291f2.png)

**Comment by roblockster** [comment]
This is probably the same issue as #1478

**Comment by devidao** [comment]
Fixed, coming soon on PTR.

**Comment by lajhar** [comment]
Fix confirmed on PTR.

**Comment by lajhar** [comment]
Fix confirmed on PreLive

**Comment by lajhar** [comment]
On live as 15.9
