### ISSUE TITLE
[Quest] Raene's Cleansing cannot be completed

### ISSUE THREAD

**Issue by wormrunner** [FeenixServerProject/Archangel_2.4.3_Bugtracker#347]
Reporter: Flore

The 4th part of the Raene's Cleansing quest chain (to create Dartol's Rod of Transformation) cannot be completed.

http://old.wowhead.com/quest=1026

In this part, you are supposed to get a wooden key (http://old.wowhead.com/item=5475/wooden-key) from the crazed or withered ancients in the part of ashenvale just next to felwood.  The key unlocks a worn chest at 54,35 which contains an iron shaft (http://old.wowhead.com/item=5464) which will become part of Dartol's Rod later in the quest sequence.  The wooden key is obtainable at about the right drop rate, but when you use it to unlock the chest, the action seems to go fine, but the chest does not open.  The key gets used up, but you do not get the iron shaft.  It is perfectly possible to go get another key, which then does exactly the same thing.

This is a very cool quest chain, since the rod allows you to transform into a furbolg and it would be great for it to work.

**Comment by Myzandria** [comment]
The above worked for me. The only problem I encountered during this quest was Ran Bloodtooth's Skull, which wasn't dropped first time I killed him (only the actual kill is needed to turn in that part of the quest), *however* the skull is needed for the follow-up (to report back to Raene Wolfrunner), so I had to go back and kill Ran Bloodtooth again - it did drop that time though :)

**Comment by devidao** [comment]
Fixed, coming soon on PTR.
