### ISSUE TITLE
In Search of Thaelrid - Incorrect level requirement.

### ISSUE THREAD

**Issue by adz0z** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3472]
Archangel 2.4.3 Error Report Form

Report ID: Adz0z

Reporter Name: Adam

Date/Time: 3:23am 2/09/2014 server time

Error Severity: minimal

Zone/Instance: Darnassus/BFD

What type of error occurred?: Quest with the wrong level requirements, In Search of Thaelrid from Dawnwatcher Shaedlass in darnassus.

What was the actual result vs. the expected result?: Unable to attain the quest: In search of thaelrid at level 19. The link to wowwiki shows the rewards from this small quest chain are available to twinks.

Can the error be repeated? If so, what are the steps?: Attempt to attain this quest below lvl 20.

Link to Video Evidence:

External/Related Links: http://www.wowwiki.com/Arctic_Buckler

Please detail your character’s race, class, and items (optional): Demius - lvl 19 twink in the making. Human Warlock.

**Comment by devastator** [comment]
Fix went Live with patch 12.0
