### ISSUE TITLE
Darkmoon Card: Crusade spell damage stacks (Part III)

### ISSUE THREAD

**Issue by roblockster** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3485]
Dear sirs:

One of the two issues referenced in #2433 unfortunately remains.

AOE spells still do not proc a stack per target affected. For example, a Consecration affecting two targets should proc two card stacks.

http://maintankadin.failsafedesign.com/forum/viewtopic.php?p=72336#p72336

TY kindly gentlemen

**Comment by devidao** [comment]
Works as intended
