### ISSUE TITLE
Ghost Sabers don't spawn

### ISSUE THREAD

**Issue by zoroasterisk** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3490]
http://www.wowwiki.com/Ghost_Saber

In the Ruins of Mathystra, Darkshore, there are cat figurines that are supposed to spawn a Ghost Saber when looted. I've looted 40+ of the things now, and none have spawned. I was able to get 2 to spawn for a different character, about 2 weeks ago, so I know it must've been something relatively recent that made it this way. Then, I only had to loot less than 20 to get the first one to spawn, so I don't think it's a matter of the RNG screwing me.

**Comment by devastator** [comment]
Yes, there is one spawning the Saber, requires more info if it was randomly spawning on retail or there were specific statues spawning the saber always.

**Comment by zoroasterisk** [comment]
Every statue should have a chance to spawn them. Looking up wowhead on
Internet Archive, you won't see anything about only one statue spawning
them.

You shouldn't close tickets without actually fixing the bugs that
necessitated them.

**Comment by devastator** [comment]
Im not saying that only one should spawn it. The possibilities are - every statue has chance to spawn it, OR there are spawned certain amount of statues that dont spawn and certain amount of statues that spawn the creature. Given that there is no positive answer on which one of the two possibilities it is, it is also likely that the current state is blizzlike, just there are statues that are missing, but again there is no information on the spawn points of the missing statues.

**Comment by zoroasterisk** [comment]
You're right that there's no way to know whether or not they should all be
spawning them. That being said, there's still no evidence that any of the
figurines would spawn without themselves spawning a Ghost Saber. The
likelihood of the current state being blizzlike or not is therefore
entirely subjective.

In my view, it's better to have every spawning figurine spawn a Night Saber
than to have about 5 spawn, with only one actually working as one would
expect to be intended.
