### ISSUE TITLE
[Bug] Pendant of the Violet Eye still not proccing from certain spells

### ISSUE THREAD

**Issue by gotmilk0112** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3493]
The USE effect on Pendant of the Violet Eye states "each spell cast", meaning that any spell should proc it, but there are a number of spells that don't.

-Renew
-Holy Nova

don't proc it, to name a couple.

I reported this issue months ago, back in July/August, and it's still not fixed. Please fix...

**Comment by devastator** [comment]
Please dont post multiple times same issue
https://github.com/FeenixServerProject/Archangel_2.4.3_Bugtracker/issues/3468
