### ISSUE TITLE
Lady Vashj - several bugs

### ISSUE THREAD

**Issue by Sherhi** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3494]
elemental adds in phase 2: have over 20k hp which is like +200% HP more than they should have (they should have around 7,8-8k hp)

Shock blast: apart from grounding totem being kind of unreliable, there is also lot of weird stuff happening with aggro - even some melee dps standing idle away from her sometimes gets aggro and boss kills him/her, or holy paladin in first seconds just running to his spot gets aggro (even though 2 tanks have made alot of threat already and healer just ran pass the boss doing nothing)

Coilfang Strider: currently immune to stun (it should be stunnable), i think they are also immune to taunt which should not be the case (i have to test this more)

Root&Shoot: when she roots the melee and moves away to start multishooting even if she is picked up by a tank and taunted she sometimes wont move, we usually use second tank to taunt her and then again the first tank to taunt once again until she follows the tank (really annoying)

**Comment by warlee** [comment]
Hello, please submit seperate reports for each issue.
