### ISSUE TITLE
[Mage] Mana shield

### ISSUE THREAD

**Issue by nameuser11** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3499]
Mana shield rank 1 and rank 2 gives you [Spellsurge] 100 spelldmg for 15 sec when you (fully) absorb physical dmg with it. Its the same proc from the Incanter's 4 set bonus.

**Comment by warlee** [comment]
Please provide sufficient proof. I cant seem to see the bug myself.

**Comment by devastator** [comment]
Fixed. Soon on PTR

**Comment by anaaz** [comment]
Fix applied on live with Patch 15.2
