### ISSUE TITLE
Shaman Talent "Elemental Weapons" Does Not Work

### ISSUE THREAD

**Issue by roblockster** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3500]
Current Situation: Shaman Enhancement talent Elemental Weapons (29080) does not affect damage from weapons imbued with Flametongue Weapon. The talent appears to work properly for Windfury Weapon and Frostbrand Weapon.

Desired Situation: Shaman Enhancement talent Elemental Weapons multiplies damage done by weapons imbued with Flametongue Weapon by 5% per talent point (15% total with 3/3).

To duplicate:
create shaman
.add 944
.cast 25489
attack target, observe FT damage

.learn 29080 or manually learn Elemental Weapons 3/3
.cast 25489
attack target, observe FT damage

The damage caused by Flametongue hits will stay the same.

**Comment by devastator** [comment]
Fixed. Soon on PTR

**Comment by anaaz** [comment]
Fix denied on PLTR

**Comment by lajhar** [comment]
On live (15.3)
