### ISSUE TITLE
Priest's consume magic

### ISSUE THREAD

**Issue by Nzzoth** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3507]
Consume magic(ID:32676) does not consume a priest buff on use.
**How to reproduce:**
Create a blood elf priest
.learn 32676
.learn 14752 (you can talent it aswell discipline tree)
Cast divine spirit on yourself then cast consume magic.
**How it works:**
Consume magic gives you mana but it does not devour one of your priest buffs.
**How it should work:**
When casted it should devour one of your priest buffs and give you mana in return.
Note: You can't cast devour magic if you have no priest buffs to devour.

**Comment by devidao** [comment]
Fixed

**Comment by Nzzoth** [comment]
Live as of patch 14.17, closed.
