### ISSUE TITLE
[Warrior] spell reflection

### ISSUE THREAD

**Issue by ladnopivo** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3508]
Spell reflection doesnt work properly. Currently situation when you want to reflect some spell by your enemy, you need to cast it before enemy cast his ability insted of before that ability landing you.So for example if caster land his attack ability to you and you try to reflect it just before missile hit you - you cant reflect it

**Comment by ladnopivo** [comment]
also check this video https://www.youtube.com/watch?v=Eh2JvonoUlg , you will see how he reflected all in that 5 sec reflect buff (buff still exist full time of 5s), atm situation on feenix u can reflect only 1 spell

**Comment by ladnopivo** [comment]
any news about this? do you guys even take a look on Archangel issuse tracker or your main focus is only warsong and ED?

**Comment by Slyd** [comment]
a) You shouldn't be able to reflect missile that is already hitting you. Spell reflect should be cast before your opponent finishes his cast. You can't reflect something mid-flight as you can with CoS for example.
b) "Something less known about Spell Reflection is its ability to reflect multiple spells if they are both cast while the buff is still active (i.e. leave the caster's hand). This makes it very useful when coupled with a charge, as it allows the warrior to reflect the initial spell from each casting mob simultaneously if their casts have the same length and start at the same time." (с) wowwiki
So its should not work for full reflect duration. But instead should reflect all spells that were travelling when 1st spell was reflected.

**Comment by ladnopivo** [comment]
you are wrong, I guess you didnt even checked linked youtube video from post above..

**Comment by Forcy** [comment]
Thanks for joining

**Comment by ladnopivo** [comment]
did you watch the video above? https://www.youtube.com/watch?v=Eh2JvonoUlg.. this is not good evidence?

**Comment by Nzzoth** [comment]
I looked at the video evidence you presented and it proves that it works exactly how it should. Pause the video at 8 seconds and you'll see that not a single missile is flying and he cast spell reflect.

Issue remains closed.

**Comment by ladnopivo** [comment]
well look where is buff place on top right, spell reflect buff ticking away 3,2,1 sec and till naturaly goes even if he reflected this spells buff didnt removed instantly after those hits

**Comment by ladnopivo** [comment]
try to remake this on feenix server and u will see buff will instatly removed after first spell hit u...

**Comment by Nzzoth** [comment]
The spell tooltip itself says " Next spell cast on you", therefor this really doesn't need any evidence what so ever. Issue is closed and it stays closed as the spell is working properly and blizzlike.

Kind regards, Nzzoth.

**Comment by griesakanik** [comment]
uhm why is this closed ? https://www.youtube.com/watch?v=SEkyQMIe8Qo  ... just type any tbc arena video in youtube ..

**Comment by griesakanik** [comment]
uhm, why exactly is this closed? warriors should be able to reflect mid air spells, they should be reclected the same way as instant spells , such as fireblast etc. 
it should be possible to reflect a pom pyro bolt, death coil etc aswell as a casted frostbolt mid air

https://www.youtube.com/watch?v=VZk1NJXHUqk 1:10
https://www.youtube.com/watch?v=Eh2JvonoUlg

.........
