### ISSUE TITLE
griftah's chat messages with $c instead of character name, $r instead of race

### ISSUE THREAD

**Issue by mfbeary** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3510]
in Shattrath, when [Griftah](http://www.wowhead.com/npc=19227/griftah) calls out to you, he uses $c instead of your character name when trying to hustle his soap-on-a-rope, and uses $r instead of (I presume) race for his amulets.

**Comment by devastator** [comment]
Fixed. Soon on PTR

**Comment by anaaz** [comment]
Fix applied to Live with Patch 15.2
