### ISSUE TITLE
Bug with Faeri Fire (Rank1)

### ISSUE THREAD

**Issue by takza** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3511]
The Rogue ability "Cloak of Shadows" doesn't remove Faeri Fire (Rank1). It is supposed to remove ALL harmful magic effects.

This is being abused by druids in arena.

**Comment by warlee** [comment]
Please provide sufficient proof with fraps.

**Comment by devidao** [comment]
Could not reproduce on PTR.

**Comment by Tudi** [comment]
could not reproduce with any of the Faeri Fire ranks

**Comment by Nzzoth** [comment]
If you come with proper evidence the issue will be reopen. For now closed.
