### ISSUE TITLE
[quest][NPC] Jailor Marlgen in a wall

### ISSUE THREAD

**Issue by mfbeary** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3513]
[Jailor Marlgen](http://www.wowwiki.com/Jailor_Marlgen) is trapped inside a wall on the side of the mountain, and cannot be attacked ("target not in line of sight").  This renders the quest [The Rescue] (http://www.wowwiki.com/Quest:The_Rescue) impossible.

He is close enough to target, but his health bar can only be seen if you are behind the castle, at (79.0, 37.8)

**Comment by devastator** [comment]
The NPC is in correct position, should be fine after server restart. Or you can ask for assistance from a GM to respawn it
