### ISSUE TITLE
Changing camera view with the mouse causes screen to spin everywhere

### ISSUE THREAD

**Issue by Drendetta** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3518]
When I try to look around by left-clicking the screen and dragging the mouse in a direction, the camera spins out of control and takes a mind of its own, ending up in some new, random view. The same issue occurs if I try to move my character by holding down both the left and right mouse keys at the same time. 

My mouse's sensitivity seems to be fine, since I have no problem dragging it across my screen to target mobs, etc. (I feel comfortable with the sensitivity in and out of the game). As for my camera settings, I messed around with those in the interface for a bit and I am currently at "Never" for the smart pivot, and I configured the other settings to lower levels. (At the time of writing this the server is down or I'd be more specific).

If this is a cache issue as mentioned in the "Before reporting any issue:" section, I apologize, but I'm unsure how to clear the WTF folder.

Thank you in advance.

**Comment by wlfbck** [comment]
This is not a server issue. And i guess you are using the mac client? I remember reading this before in relation with using a mac (although i can't remember if it was an emulator or client error).

**Comment by Drendetta** [comment]
I am using Windows actually. Below is a screenshot of my camera and mouse settings.
![wowscrnshot_010815_023902](https://cloud.githubusercontent.com/assets/10406774/5659465/a567e41a-96e0-11e4-9226-b05a54b26eb4.jpg)
![wowscrnshot_010815_024559](https://cloud.githubusercontent.com/assets/10406774/5659466/a56c1c2e-96e0-11e4-9f37-1d5ef298fa39.jpg)
