### ISSUE TITLE
[Quest][Horde]Artisan First Aid quest: Triage

### ISSUE THREAD

**Issue by Thordin88** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3519]
The Artisan First Aid quest Triage that sends you to Hammerfall, Arathi to Doctor Gregory Victor makes you save 15  Critically Injured Soldiers, Badly Injured Soldiers and Injured Soldiers (http://www.wowwiki.com/Quest:Triage_(Horde)). However, the time that is required to save even the injured ones is too low and the speed of death is incredibly fast. I barely managed to save 1 or 2 injured ones but the Critical and badly injured ones are impossible to cure since they die in 7 seconds or less and the trial bandages take about 10 seconds to cast. Needless to say I couldn't complete the quest. The bug seems to be in the timer for the patients - way too fast.
Pics:
![wowscrnshot_011015_162141](https://cloud.githubusercontent.com/assets/10476595/5691947/cea59ecc-98e7-11e4-85df-d48167d81854.jpg)
![wowscrnshot_011015_162149](https://cloud.githubusercontent.com/assets/10476595/5691948/e5b63a54-98e7-11e4-8e63-5ec3ec0231b6.jpg)
![wowscrnshot_011015_162159](https://cloud.githubusercontent.com/assets/10476595/5691949/ea038fc6-98e7-11e4-8b93-bee7e3c7116b.jpg)
![wowscrnshot_011015_162232](https://cloud.githubusercontent.com/assets/10476595/5691950/ec78c83e-98e7-11e4-8f44-b906ad12dd4a.jpg)
![wowscrnshot_011015_162255](https://cloud.githubusercontent.com/assets/10476595/5691954/f01eab0c-98e7-11e4-9741-fcd0de514385.jpg)

This is how the quest should go down:
https://www.youtube.com/watch?v=6cc5Lc54eMs

As you can see this quest is bugged and impossible to complete. Please fix this quest asap as it is very important in the leveling of characters on the realm.

**Comment by smspf** [comment]
i did it on my druid a week or two ago by putting it on a hotbar and enabling health bars, then targeting the critical ones as soon as they spawn and using it
so either they fixed it or i somehow beat the timer

**Comment by devastator** [comment]
https://github.com/FeenixServerProject/Archangel_2.4.3_Bugtracker/issues/3583
