### ISSUE TITLE
[MAJOR][Priest] Mind Control unusable

### ISSUE THREAD

**Issue by takza** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3521]
If you cast Mind Control, you get kicked from anticheat.

It's completely broken and has been like that for quite some time now.

**Comment by gotmilk0112** [comment]
Weird, I've never gotten kicked from using MC.

**Comment by takza** [comment]
Try it on players in a duel or so.

**Comment by warlee** [comment]
Making additional report for this.
