### ISSUE TITLE
Combat issue.

### ISSUE THREAD

**Issue by Nzzoth** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3522]
http://www.wow-one.com/forum/topic/91330-combat-bug/

**Comment by devidao** [comment]
Fixed, coming soon on PTR. If one of quest objectives item is equipped and player is in combat then he can not be rewarded by quest

**Comment by Nzzoth** [comment]
Fix confirmed on PTR.

**Comment by Nzzoth** [comment]
Confirmed on PLTR.

**Comment by Nzzoth** [comment]
Live as of patch 15.
