### ISSUE TITLE
Arhimonde Doomfire

### ISSUE THREAD

**Issue by ovpavel** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3523]
Doomfire occurs in the player.

http://www.wowwiki.com/Archimonde_(tactics)

Doomfire: A trail of fire moving on the ground away from Archimonde. Players entering it get a non-dispellable debuff which deals initially 2400 fire damage every 3 seconds, which is reduced by 150 per tick. As long as the player remains in the trail of fire, the debuff is renewed, and ticks for the full 2400 fire damage every second. Can be removed with Cloak of Shadows.

**Comment by ovpavel** [comment]
Fire occurs in any player, but it is necessary to Archimonde.

**Comment by Dorakrab** [comment]
What he meant to say is that doomfire spawns directly inside a player, instantly leaving the fire DoT on him, while he should only spawn doomfires beside his feet and then they should follow players around. Current situation makes doomfire unavoidable.

**Comment by ovpavel** [comment]
http://www.wowhead.com/npc=17968/archimonde#comments

As of 2.4.2 his doomfires can now path randomly, ramping up the difficulty of the fight hugely, it's also now possible for air bursts to be targetted on the maintank.

The fires change has increased the difficulty of this fight an exorbitant amount, with melee previously dominating the fight, it's a lot harder for them to avoid fires now.

from 2.4.2 patchnotes

Raids & Dungeons
Hyjal Summit - Archimonde (Possibly bugged)

* Fire will now spawn -much- closer to Archimonde, and the pathing is entirely random.
* Fire can target and chase Melee. Never possible pre 2.4.2.
* Archimonde's hit box size has been increased
* MT's are now able to be targetted by Air Burst

**Comment by ovpavel** [comment]
2.4.2 Undocumented changes, Blue posts

**Comment by Forcy** [comment]
This is intended on our realms. (Stay away from Fire)
