### ISSUE TITLE
Illidan Flame Crash, Demonically, Does Double Damage Over a Stupidly Huge Area

### ISSUE THREAD

**Issue by roblockster** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3524]
Illidan's Flame Crash double-ticks for 5k every 2 seconds, thereby doing 10k damage (double). Moreover, the area of effect of the damage reaches a few yards beyond the fire animation. If there is the slightest server lag this is 20k damage. Moreover, the area of effect of the spell is a few yards from the edge of the animation, making it essentially invisible death fire. Please fix. I want to raid.

![image](https://cloud.githubusercontent.com/assets/7952671/5772393/3bfcaee0-9d0f-11e4-8582-2e099bd99415.png)

WowWiki: Flame Crash: 1.5 sec cast, 10 yard AoE dealing 5k fire damage per tick for 2 minutes centered on the ground at Illidans current target
http://www.wowwiki.com/Illidan_Stormrage_(tactics)

**Comment by Forcy** [comment]
This is intended on our realms. (Stay away from Fire)
