### ISSUE TITLE
[Shaman] Windfury OH Damage

### ISSUE THREAD

**Issue by HCGWill** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3525]
Not sure how nobody has caught this already. Windfury (http://database.wow-one.com/index.php?spell=25505) offhand damage is lower than it should be. The AP bonus from WF should not be getting the 50% Dual Wield penalty. The current formula is something like:
(weapon damage + ( ( ( AP + windfury bonus ) / 14 ) * weapon speed )) * 0.5
While it should be:
weapon damage * 0.5 + ( ( ( AP + windfury bonus ) / 14 ) * weapon speed )

With similar weapon damage, OH procs should never be doing half the damage of MH procs. Here are two sources which specifically mention the AP bonus not being affected by DW penalty:

http://web.archive.org/web/20080204142249/http://elitistjerks.com/f31/t13297-enhance_shaman_collected_works_theorycraft_vol_i/
http://web.archive.org/web/20080207011157/http://forums.worldofwarcraft.com/thread.html?topicId=79203452&sid=1

This also explains why FT and FB tend to parse higher than WF/WF, since the offhand is eating WF procs with minimal output.

**Comment by roblockster** [comment]
WoW Patch 2.1: Windfury Weapon: A bug with this spell was making off-hand procs receive less bonus damage than intended. It is now fixed.
http://us.battle.net/wow/en/game/patch-notes/2-1-0

From OP's EJ thread: "OffHand Windfury (2.1 patch mechanic)
((<Weapon Damage>+AP/14*<Weapon Speed>)/2+(WindfuryAP + <Totem of the Astral Winds>)/14 * <Weapon Speed>)) * 1.10 * 1.40"

**Comment by Nifire** [comment]
How is this comming along? See you found the correct formula

**Comment by Nifire** [comment]
Been doing some Homework on this here are my findings:

 

https://docs.google.com/spreadsheets/d/1k3xYw4JtqLPzndLRhwzXq5w83h7uYWzgNLBIVdB_12I/edit?usp=sharing

 

Damage is raw dmg not factoring in crits or damage reduction from e.g armor.

 

Would love some feedback on this

**Comment by anaaz** [comment]
#3730 
Fixed, coming soon on PTR
