### ISSUE TITLE
Hunter and Warlock pets not losing preparation buff in arena after it starts.

### ISSUE THREAD

**Issue by Nzzoth** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3530]
How to reproduce:
Create 1 hunter 1 warlock:
on both
.levelup 69
On hunter:
.go c ravager (target creature Ravager)
.npc tame
.go c bindo
.debug arena
On warlock:
.learn 7763
summon your demon.

Queue with both hunter and warlock for Arena skirmish, wait for the game to start and observe that the Ravager and warlock pet will keep their "Preparation" aura.

Desired: Preparation should fall off any players or pets after game starts

**Comment by Forcy** [comment]
Fixed and applied to Live
