### ISSUE TITLE
Resil not reducing crit dmg

### ISSUE THREAD

**Issue by ohrerbohrer** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3531]
Resilience doesn't reduce the crit dmg! You can easily test it, hitting a full geared pvp char with around 450 resilience and noting the height of the crits. Then take away the pvp parts without armor, so trinket, necklace, rings... so you have lower resilience but not lower armor. Then duel again and compare the crit height!
You will see the crit height does not Change! That's the Point why melee dmg feels so insanely high.
Regards

**Comment by Forcy** [comment]
Unable to reproduce, please provide screenshot/video data. And open a new issue.

**Comment by Involve** [comment]
Report denied. Resilience is mitigating melee critical hits just as it is supposed to. 
![edit](https://cloud.githubusercontent.com/assets/6666211/6011220/b13f3c94-ab39-11e4-873b-9cab7d050c0b.jpg)

**Comment by Zerixx** [comment]
This has been fixed on 11/13/16.
