### ISSUE TITLE
Bugged Quest: To Skettis!

### ISSUE THREAD

**Issue by sladeslade** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3535]
Link: http://www.wowwiki.com/Quest:To_Skettis!

I've deleted the quest item by mistake. Then abandoned the quest, but the NPC, which gives the quest did not give the item again. Tested three times, deleted cache, WTF folders but this did not resolve the problem I experience.

**Account information removed by Nzzoth.**

I hope that the issue will be resolved in short term. 

Best Regards,
James

**Comment by Nzzoth** [comment]
Greetings,

You should contact a GM regarding a refund via ingame ticket or our forums www.wow-one.com .

Kind regards, Nzzoth.
