### ISSUE TITLE
[quest] Battle of the Crimson Watch

### ISSUE THREAD

**Issue by Domizze** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3536]
Battle of the Crimson Watch is the quest witch rewards you one of the illidari tabard(http://www.wow-one.com/database/?item=31408)

The pre-quest works fine, you kill the guys that drop the item(The Journal of Val'zareq - http://www.wow-one.com/database/?item=31345) that starts the chain. After you turn in the 1st quest you can start the 2nd quest "Battle of the Crimson Watch". 

When you start "Battle of the Crimson Watch" waves of elite mobs should spawn(https://www.youtube.com/watch?v=bsPv1UuwK40)

What actualy happens is only the first wave of demobs spawn and thats it...after you kill the 1st wave no more mobs will spawn. 

What is starange is that when i abandon the quest and retake it again from the Crystal Prison(http://www.wow-one.com/database/?object=185126) not even the 1st wave spawn. I believe that the 1st wave spawn only the 1st time someone tries to do this quest after a server restart.

I know that this quest used to work previously since there are many players that have the tabard.

Please fix this, thank you in advance.

**Comment by Domizze** [comment]
Im just curious, is thee any way to get the tabard at the moment ? or do i have to wait for a fix ?

**Comment by kykyhungie** [comment]
People have said that the quest only works after the server has been reset, whether that is true or not, i have no idea. but only explanation i have heard

**Comment by devidao** [comment]
Fixed, coming soon on PTR.

**Comment by Nzzoth** [comment]
Fix confirmed on PTR.

**Comment by Nzzoth** [comment]
Confirmed on PLTR.

**Comment by Forcy** [comment]
Fixed in patch 14.22
