### ISSUE TITLE
Conjure manna biscuit issue

### ISSUE THREAD

**Issue by Nzzoth** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3538]
Conjure manna biscuit (ID:34062) doesn't provide both drinking but only eating.

**Comment by Salce** [comment]
http://www.wow-one.com/database/index.php?item=19301

**Comment by kykyhungie** [comment]
http://www.wow-one.com/database/index.php?item=34062

**Comment by devidao** [comment]
Fixed, coming soon on PTR.

**Comment by Nzzoth** [comment]
Live and working as intended.
