### ISSUE TITLE
LBRS crash

### ISSUE THREAD

**Issue by aangx** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3539]
Attacking trolls in lower blackrock spire causes client crash.

I suppose this bug may be similar to this earlier one as crashing is tied to being in combat with mobs of certain type: https://github.com/FeenixServerProject/Archangel_2.4.3_Bugtracker/issues/2310 

WowError report:
This application has encountered a critical error:

ERROR #132 (0x85100084) Fatal Exception
Program:	D:\Games\Feenix 2.4.3 client\Wow.exe
Exception:	0xC0000005 (ACCESS_VIOLATION) at 0023:00466FE3

The instruction at "0x00466FE3" referenced memory at "0x0A2F6208".
The memory could not be "read".

WoWBuild: 8606
Realm: Archangel [14x] Blizzlike [178.33.225.161:8996]
Local Zone: Blackrock Spire
Local Player: Aus, 0000000000135262, (-91.9098,-476.354,24.2458)
Attacking Target: Shadow Hunter Vosh'gajin, F13000241400AA02, (-94.0091,-473.332,24.2494)
Locked Target: Shadow Hunter Vosh'gajin, F13000241400AA02, (-94.0091,-473.332,24.2494)
Last Enemy Target: Shadow Hunter Vosh'gajin, F13000241400AA02, (-94.0091,-473.332,24.2494)

**Comment by warlee** [comment]
Couldnt reproduce
