### ISSUE TITLE
Mark of the Wild and his Talent that decrease instead increase

### ISSUE THREAD

**Issue by alevitta** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3544]
Hi i need ur help about "mark of the wild" and his talent, i have mark of the wild rank 7 and i should have 344 armor and etc and i should have an "increase" because of the talent of 21%, but i think that talent do the opposite, so it decrease of 21% because when i put "mark of the wild" i have 285 armor instead 344, can u help me?

**Comment by Nzzoth** [comment]
Greetings,

The issue has been tested and denied, the talent works perfectly on all ranks of Mark of the wild. However what the issue is the tooltip on the buff shows untalented stats while on the spell the tooltip shows correct stats and provides correct stats.

Kind regards, Nzzoth.
