### ISSUE TITLE
Hunter talent entrapment

### ISSUE THREAD

**Issue by ladnopivo** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3547]
Entrapment
Rank 3
Instant.
Gives your Immolation Trap, Frost Trap, Explosive Trap, and Snake Trap a 25% chance to entrap the target, preventing them from moving for 4 sec.

Talent from survival column completly dont works

**Comment by warlee** [comment]
The talent Entrapment( http://www.wow-one.com/database/index.php?spell=19388 ) should proc (http://www.wow-one.com/database/index.php?spell=19185).

To reproduce this issue you will need 2 clients:
Create Orc Hunter:
.levelup 69
.learn 13809 (http://www.wow-one.com/database/index.php?spell=13809)
Level up talents in Survival school until Entrapment talent.
.t arena

Create Gnome Rogue
.levelup 69
.t arena

Step 1: Hunter client-  cast Frost Trap on the ground(.cast 13809).
Step 2: Rogue client - run across the frost trap. 

Current results: Nothing but slow is happening.

Expected results: The trap should have 25% proc on you Entrapment (http://www.wow-one.com/database/index.php?spell=19185). 
This doesnt work only for Frost trap(13809) but also for Immolation Trap, Explosive Trap, and Snake Trap.

IMPORTANT NOTE: The Entrapment effect should be DRed in PvP and be set to category 'Random Roots' (example same as Frostbite).

**Comment by Nzzoth** [comment]
#3160

**Comment by devidao** [comment]
Fixed, coming soon on PTR.

**Comment by nurmi90** [comment]
While having Entrapment 3/3 and trying to slow Botanica enemies immune for slow effect, combat log said Entrapment resisted, although it doesn't show Entrapment otherwise at all? So here is something to check if there is actually two Entrapments at the game, and the whole issue simply is a naming conflcit.

**Comment by Nzzoth** [comment]
This went live with patch 14.12 , closed.
