### ISSUE TITLE
[rogue] [shadowstep dmg buff]

### ISSUE THREAD

**Issue by teddys** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3548]
Current situation : Shadoswtep 20% dmg buff does not increase the damage of next abillity by 20% and the buff itself lasts for full duration.

Expected : shadowstep 20% dmg buff increases the damage of next abillity by 20% and then disappears from ur buffs.

**Comment by Nzzoth** [comment]
For reasons why I'm denying this please read #3332 

Closed.
