### ISSUE TITLE
Warrior Whirlwind range bug

### ISSUE THREAD

**Issue by Vinxhe** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3549]
There's an issue with the range of Whirlwind (or the hitboxes) on a few bosses. I've noticed it yet on Kaz'rogal and Lurker.

I was on max. melee range (autohitting and using abilities) on both bosses, but my Whirlwind wouldn't hit unless I would move in closer (which isnt really a possibility on lurker).

**Comment by Blaqwar** [comment]
This is an issue with boss melee range hitboxes being too big rather than the WW range being too small as far as I know.

**Comment by lajhar** [comment]
#3906 
/close
