### ISSUE TITLE
[Quest] Getting the Bladespire tanked is not working

### ISSUE THREAD

**Issue by Roeled** [FeenixServerProject/Archangel_2.4.3_Bugtracker#355]
Place: Blade's Edge Mountains/Sylvanaar
Side: Ally

Quest: Getting the Bladespire Tanked

Problem: Normally u have to place quest item (keg http://old.wowhead.com/item=30353 or http://old.wowhead.com/item=29443) near ogres and they come and drink it, after drinking they get stunned and got yellow (not agressive) nameplate average 10 seconds(cant proof it now). Range where ogres see keg is bigger then aggro range. 
If i place keg nothing happens.
And yes im in the right camp.
Impossibility of making this quest makes impossible to complete The Trappings of a Vindicator (http://www.wowhead.com/quest=10516) because of 2 elite ogres which normally can be crossed off with brew.

I apologise for my english skills. :)

**Comment by devidao** [comment]
Fixed, coming soon on PTR
