### ISSUE TITLE
[character quest] druid swift flight form chain quest gone

### ISSUE THREAD

**Issue by Foxtrotswift** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3555]
during the third animal statue on this chain quest, the quest and needed whistle from my inventory were both removed, I didn't abandon, fail or complete the quest, so I don't have it, neither can I retake it or complete it. any info would help.

**Comment by Foxtrotswift** [comment]
would deleting that characters variable cache , layout cache or other variables help?

**Comment by warlee** [comment]
Please make request on forums.
