### ISSUE TITLE
[Hunter] missing spell (Dismiss pet)

### ISSUE THREAD

**Issue by andris92** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3556]
I have a lvl 41 night elf hunter. The hunter trainers do not have the spell Dismiss pet, so i can not learn that. I would be happy, if i have this spell. Could you help me? 
Thanks.

**Comment by wlfbck** [comment]
Pretty sure you get one via quest.

**Comment by smspf** [comment]
You have to complete the level 10 hunter quest (pretty sure it's called "Taming the Beast" or something), that teaches tame beast/feed pet/dismiss pet/etc.
The quest itself is bugged in that if you run out of range and your guardian pet despawns before you can dismiss it in-between parts, you have to wait like 15 minutes for it to automatically despawn so you can do the next part, but that's a slightly unrelated issue.

**Comment by warlee** [comment]
Closing then.
