### ISSUE TITLE
[rogue] [puncturing wounds]

### ISSUE THREAD

**Issue by teddys** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3557]
Puncturing wounds does not grant 15% bonus crit chance to mutilate, but only like 10%
The backstab part works fine.
http://i162.photobucket.com/albums/t243/teddy-s/mutilate_zps0kcmgowt.jpg
should be a bit more than 40% cause of mongoose procs

**Comment by teddys** [comment]
current situation : puncturing wounds 3/3 does not increase crit chance of mutilate by 15%
expected situation : puncturing wounds 3/3 does increase crit chance of mutilate by 15%

How to reproduce:
You need 2 clients, on one create an undead rogue
.levelup 69
.learn 1329 (Mutilate)
.learn 674 (Dual wield)
.add 32471 (Shard of azzinoth)
.add 33801 (Vglad mutilator)
spec 3/3 puncturing wounds
.t test
On the other one create a draenei priest
.levelup 69
.mod hp 1000000000
.t test

Use rogue to cast mutilate on priest thousand times and observe that puncturing wounds does not increase mutilate's crit chance by 15%.


http://i162.photobucket.com/albums/t243/teddy-s/mutilate_zpsqyfqz6fc.jpg
The crit chance of mutilate should be alot higher ( i had agi totem up 99% of the time = +2% crit + mongoose procs )

**Comment by devidao** [comment]
Fixed. coming soon on PTR

**Comment by Nzzoth** [comment]
Fix confirmed on PTR.

**Comment by Nzzoth** [comment]
Fix confirmed on PTR.

**Comment by lajhar** [comment]
On live (15.4)
