### ISSUE TITLE
Hunter season 4 gloves rating requirement

### ISSUE THREAD

**Issue by Dzuvpacabra** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3560]
http://imgur.com/3z4400H

It shouldnt require any rating

I cleared my cache folder and still same issue, I logged my priest and mage, and on those chars there is no rating requirement for gloves. Issue is only on hunter.

edit: other hunters confirmed bug too

**Comment by devastator** [comment]
Hotfixed
