### ISSUE TITLE
season 2 gloves [all classes]

### ISSUE THREAD

**Issue by teddys** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3561]
current situation : all of the season 2 gloves ( http://www.wowhead.com/items=4?filter=qu=4;sl=10;na=merciless ) cost 20 alterac valley marks of honor

expected situation : all of the season 2 gloves (http://www.wowhead.com/items=4?filter=qu=4;sl=10;na=merciless ) cost 20 arathi basin marks of honor

**Comment by devastator** [comment]
http://www.wowwiki.com/Season_2_Arena_rewards
