### ISSUE TITLE
[warrior] spell reflect

### ISSUE THREAD

**Issue by griesakanik** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3563]
### ATM
 spell reflect has to be casted before enemy spell completion

### intended
spell reflect reflects any spell for the duration of spell reflect. 

warriors should be able to reflect mid air spells, they should be reclected the same way as instant spells , such as fireblast etc. 
it should be possible to reflect a pom pyro bolt, death coil etc aswell as a casted frostbolt mid air

https://www.youtube.com/watch?v=VZk1NJXHUqk 1:10
https://www.youtube.com/watch?v=Eh2JvonoUlg

.........

**Comment by Nzzoth** [comment]
#3508 
Issue closed.

**Comment by griesakanik** [comment]
are you kidding me i presented you vids that state the opposite of your claim

**Comment by griesakanik** [comment]
http://www.wowwiki.com/Spell_Reflection?oldid=984503
>Something less known about Spell Reflection is it's ability to reflect multiple spells (bug? glitch abuse?) if they land on the warrior inside a very very short periode of time. For exemple, in Hellfire Ramparts, on the way to Omor there is 2 Bleeding Hollow Darkcasters that have a Scorch spell. I charged in, activated Spell Reflection right away and both Scorch we're reflected. An other more visible exemple is Swifty's second pvp video, where in the intro he reflects six Frostbolts from mages. 

also it should be possible to reflect frostbolt + icelance combo Becasue they are nearly impacting the target at the same time.

**Comment by Nzzoth** [comment]
Greetings,

This is not a joke and I'm not sure how you got an impression that I'm joking. There was a very serious discussion regarding this. The issue remains closed.

Kind regards, Nzzoth.

**Comment by griesakanik** [comment]
alright nzzoth
i made a mistake, i can clearly remember it otherwise since i played tbc arena s1 and quit wow at around this time. report is closed correctly   just some evidence for record  if someone else makes claims. 


> that was maybe pre S2 tbc
https://www.youtube.com/watch?v=qN8LBYi0f64   00:8  he casts Spellreflect while shadowbolt is midair
https://www.youtube.com/watch?v=IJ2BzfjXq8I       00:17 argueably at the same time 

> spell reflect around WotlK
https://www.youtube.com/watch?v=TsvxzRSe-p4  - there is a discussion in youtube that spell reflect has had some changes during s2- s3 tbc that were not written down. unfortunately this is for the worse

**Comment by Nzzoth** [comment]
Don't let it beat you down, we all make mistakes, I'm glad you understand why I closed it. Thanks for your contribution nontheless.

Kind regards, Nzzoth.
