### ISSUE TITLE
[Rogue][Talent] Sword Specialization

### ISSUE THREAD

**Issue by paaske** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3564]
Sword Specialization is unable to proc of special attacks (sample Sinister strike)

Tested on target dummy using both only Sinister strike and MH white hits + sinister strike.

Screenshot of data isn't really feastable, and is easy to replicate. To only use Sinister Strike and no auto attacks you have to use the edge of the angle of attack.

**Comment by Nzzoth** [comment]
Greetings,

It indeed does proc from special attacks, the issue with sword specialization is that the proc is triggered on next attack which you haven't done with your testing. The issue you made will be resolved as a side-effect of another fix therefor I'm closing this. Thank you for your support.

Kind regards, Nzzoth.
