### ISSUE TITLE
Imbued Unstable Diamond

### ISSUE THREAD

**Issue by ohrerbohrer** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3566]
As the Assault on Bashir Landing Event doesn't work, there is no way to acchieve the Meta Gem "Imbued Unstable Diamond" which is the best PvP Meta for some classes. I would suggest to make it viable for Spirit Shards or vote Points.
When you try to start the Event there are no Attackers you can defeat, so the Vendors won't spawn -.-

**Comment by warlee** [comment]
Aware of the issue, will bring it up to server managment.
