### ISSUE TITLE
Npc Bug, Inside Cavern of Time (Steward of Time)

### ISSUE THREAD

**Issue by Raynez** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3569]
Archangel 2.4.3 Error Report Form

Report ID: Raynez123

Reporter Name: Raynez

Date/Time: 04-12-2015 14:15 GMT+1

Error Severity: Not very much, but an annoying bug.

Zone/Instance: Cavern of Time

What type of error occurred?: NPC bug (Steward of Time)

What was the actual result vs. the expected result?:

You should be able to use the npc to fly down the cave if you have taken his quest and completed it. 

Can the error be repeated? If so, what are the steps?: well, it happened after the faction change.

Are you able to provide visual evidence?:

http://imgur.com/MrtX8c4
As you can see, i am exalted with both Mount hyjal and revered with Keepers of time, which means i have completed all the quests in the cave, and yet i cant use the npc to fly down.

Can you provide links to the objects, creatures, or abilities in question?:

http://www.wowwiki.com/Steward_of_Time

**Comment by devidao** [comment]
Fixed, coming soon on PTR.

**Comment by lajhar** [comment]
On live (15.8)
