### ISSUE TITLE
[Shaman] Totem Of Ancestral Guidance, not adding any damage. Video Proof

### ISSUE THREAD

**Issue by scootypuff** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3570]
Report ID: Scootypuff001

Reporter Name: Scootypuff		

Date/Time: 4/14/2015 3pm server		

Error Severity: 100% not working

Zone/Instance: Anywhere/Everywhere/@ training dummies

What type of error occurred?: The totem of ancestral guidance doesn’t add any bonus damage whatsoever, it’s as if one isn’t even wearing a totem. When compared to totem of the void, which works properly, see video evidence.

What was the actual result vs. the expected result?: The actual result yielded no bonus damage, the expected result was to see my lightning bolts of max rank having some additional damage, not losing some in comparison to my previous totem.

Can the error be repeated? If so, what are the steps?: Aboslutely, equip the totem anywhere and test it with any rank of lightning bolt vs any mob, if you use the totem of the void before or afterwards, you will certainly see the error in damage calculations.

Link to Video Evidence:https://vid.me/stVC

External/Related Links: None available, but the developers on tbc tournament.com (which is now offline and dead) i am not advertising, seemed to fix it in a matter of minutes! I can’t imagine it’s too grand a task.

Please detail your character’s race, class, and items (optional):
Scootypuff, orc shaman, naked in testing.

**Comment by Nzzoth** [comment]
#3246 
Duplicate, closed.
Thanks you for the report nontheless.

Kind regards, Nzzoth.
