### ISSUE TITLE
Intervene Not Transferring Non-damaging Abilities

### ISSUE THREAD

**Issue by DeadlyMemory** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3571]
When intervene is cast on a friendly target in PvP and an opposing team member uses Sap or blind (maybe other abilities. Untested beyond this) the debuff isn't consumed and the ability isn't transferred to the warrior.

Expected: Warrior receives the ability that was cast on friendly target with intervene debuff being consumed.

**Comment by warlee** [comment]
Cant reproduce.

**Comment by teddys** [comment]
Tested it and it correctly transfers blind/sap to the warrior.
