### ISSUE TITLE
[Mage][Talent] Shatter does not increase Frostbolt critical hit chance by the expected amount on geared PvP targets

### ISSUE THREAD

**Issue by Avathea** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3574]
Shatter does not increase the crit chance of Frostbolt by the expected amount on pvp targets with Resilience.
Shatter does however seem to work fine with Ice Lance.

Proof:
Expected Frostbolt critical hit chance:
+Empowered Frostbolt: (5%)
+Critical Hit Chance from Gear: (14.55%)
+Shatter: (50%)
-Resilience (10%)
=Expected Crit Chance on Frozen Targets (59.45%)

Observed Frostoblt critical hit chance (n=100) = 30%
![frostbolt](https://cloud.githubusercontent.com/assets/11630281/7219051/4b4434ea-e68e-11e4-91cf-f93e291e0c03.png)
![icelance](https://cloud.githubusercontent.com/assets/11630281/7219082/6295138e-e68f-11e4-8aae-4571e065806c.png)
![talents](https://cloud.githubusercontent.com/assets/11630281/7219145/8d68dffc-e692-11e4-8bfa-60b1cc9c5792.png)

![gear](https://cloud.githubusercontent.com/assets/11630281/7219053/50eef6e6-e68e-11e4-8100-2351b5abd093.png)

The huge disparity beetween expected crit chance and observed crit chance (60% vs 30%) leave no doubt that the talent is indeed bugged. This issue might affect shatter vs pve mobs aswell, however i have only noticed it against pvp geared players.

How to replicate:

Have a lvl 70 mage shoot Frostbolt (rank 13) into full pvp geared targets and observe a lower crit chance than what you would expect!

Hope this issue will be fixed soon!

**Comment by warlee** [comment]
Will add my results soon.

**Comment by warlee** [comment]
Information for testers: 
The situation should be tested with various spells, to have the more or less accurate number, need 500 of each situation and always 3% PvP hit cap. 
Frost nova
1) Frost nova + Ice Lance (taken by Wrl)
2) Frost nova + Frostbolt
3) Frost nova + fire Blast

Freeze
1) Freeze + Ice Lance
2) Freeze + Frostbolt
3) Freeze + Fire Blast

Frostbite
1) Frostbite + Ice Lance
2) Frostbite + Frostbolt
3) Frostbite+ Fire blast

You can also test other spells but take these as priority
