### ISSUE TITLE
Imbued Unstable Diamond

### ISSUE THREAD

**Issue by Stoniz** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3575]
As this is the last season it's would be nice to have this gem,The metagem should be available by completing the event Bash'ir Landing(http://www.wowhead.com/quest=11119/assault-on-bashir-landing) Which is not working therefore we request an alternative (Adding to vote shop or something)
http://www.wowwiki.com/Imbued_Unstable_Diamond
http://www.wowhead.com/item=32641/imbued-unstable-diamond#comments

**Comment by warlee** [comment]
Hello, the issue has been already mentioned 
https://github.com/FeenixServerProject/Archangel_2.4.3_Bugtracker/issues/3566
and server staff is working on solving the gem problem by other alternatives than bugged quest. If you wish to report not working quest then please make seperated report.
