### ISSUE TITLE
Shaman Stormstrike and Lightning Shield

### ISSUE THREAD

**Issue by endemol88** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3579]
If target been with Stormstrike Debuff, then targen receives +20% damage from Chain Lightning,  Lightning Bolt,     Lightning Shield, Earth Shock or any direct Nature damage. This damage will expend one of the two charges, but now on feenix damage from Lightning Shield increased by 20% on target with SS debuff, but charges are not consumed

**Comment by teddys** [comment]
How to reproduce:
You need 2 clients, on one create an orc shaman
.levelup 70
.learn 32176 (Stormstrike)
.learn 674 (Dual wield)
.learn 1180 (Daggers)
.learn 25472 (Lightning shield)
.add 32471 (Shard of azzinoth)
.add 33801 (Vglad mutilator)
.t test
On the other one create a draenei priest
.levelup 70
.mod hp 1000000000
.t test

With shaman, cast stormstrike on priest and then cast lightning shield on yourself. With priest melee attack the shaman and observe.
Current situation :lightning shield does increased damage to the priest, but the charge of stormstrike´s bonus isn´t removed

Expected : LIghtning shield damage consumes stormstrike charge on the priest.

**Comment by devidao** [comment]
Fixed, coming soon on PTR

**Comment by Nzzoth** [comment]
Fix confirmed on PTR.

**Comment by Nzzoth** [comment]
Confirmed on PLTR.
