### ISSUE TITLE
Mage Clearcasting and channeling spell

### ISSUE THREAD

**Issue by endemol88** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3580]
When mages obtain Clearcasting they can cast all 15 sec free (no mana cost) channeling spells: Blizzard and  Arcane Missiles, but Clearcasting must disappear after using a spell that requires mana, including Blizzard and  Arcane Missiles.
This bug mostly abused in PvP, when mage get Clearcasting  by rank 1 Blizzard (320 mana) and after this he cast 2-3 max rank (1645 mana) and even more if interrupt and change location of AOE.

**Comment by teddys** [comment]
let me make it simple for you
aoe spell mana cost is taken off of mage mana at the start of the cast, its not progressively taken off as you damage

**Comment by griesakanik** [comment]
i don's speak clingon that well but i think what he means is that blizzard/AM/firenova etc all aoe instant spells and channelling spells should only procc on the first damaged target ( 10% ?) all other hits of the spell should not be considerd proccs, so basically what happens on 1.12 realms is that mage casts blizzard and gets 24/7 clearcasting effect what should not happen... dunno whats on 243 realms

**Comment by teddys** [comment]
aha! (did u find that in his post? cause i didnt :D)
Can u link any relevant source, that clearcasting should proc only on 1st damage of blizzard?

**Comment by griesakanik** [comment]
there is a tread about it in 1.12 tracker, very easy to find. 
(and that mechanic is just private server stuff)

**Comment by endemol88** [comment]
Clearcasting must disappear when u start channeling AM/Blizzard

**Comment by griesakanik** [comment]
clearcast hast alot of bugs and this is one of them endemol : )

**Comment by teddys** [comment]
lol what, it was not like this 1 week ago for sure

How to reproduce:  https://youtu.be/H8wwr7xfX70
or
You need 2 clients, on one create an undead mage
.levelup 70
.learn 27085 (blizzard)
spec 5/5 arcane concentration
.t test
On the other one create a draenei priest
.levelup 70
.mod hp 1000000000
.t test

With mage, cast blizzard on priest and wait for clearcasting proc. 
current situation : Then cast blizzard several times and notice, that it costs no mana and clearcasting buff is not consumed.

Expected : Clearcasting is consumed on spell cast.

**Comment by warlee** [comment]
"there is a tread about it in 1.12 tracker, very easy to find."

I am going to change your world here, but 1.12 is not 2.4.3, clearcasting should be able to proc on each tick of chan spell in 2.4.3

**Comment by warlee** [comment]
https://github.com/FeenixServerProject/Archangel_2.4.3_Bugtracker/issues/2993

**Comment by endemol88** [comment]
still not fixed

**Comment by Tudi** [comment]
rejected. This issue is a duplicate for #2993. #2993 fix should be live on PTR right now

**Comment by Nzzoth** [comment]
Closing this as it's a duplicate.
