### ISSUE TITLE
Improved Power Word: Shield not scaling properly

### ISSUE THREAD

**Issue by Involve** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3586]
***Current Situation:***
The Priest Talent Improved Power Word: Shield does not scale with Bonus Healing, but instead is applied to the base absorption only.

***Desired Situation:***
The Talent should consider Bonus Healing and thus scale with gear.

***Reproduction Guide:***
You will need two Clients in order to reproduce this issue.

Client A
Create any Class
.gm off
.gm visible on
.levelup 69
.t test
.learn 26029 (Dark Glare)

Client B
Create a Priest
.gm off
.gm visible on
.leveup 69
.t test
.add 33743 (Vengeful Gladiator's Salvation)
.learn 25218 (Power Word: Shield)
.m hp 1000000

Start a Duel. Equip the Mace and Shield yourself on Client B. Tab to Client A and Dark Glare the Priest. Notice the amount of damage absorbed is 1404.

Tab back to Client B.

.learn 14769 (Improved Power Word Shield (Rank 3))

Repeat the Duel and notice now that the absorbed amount increased to 1593.

***Math:***
Power Word: Shield benefits from 30% of your Bonus Healing.
The Base Absorption of Power Word: Shield is 1265 at level 70.

The current formula used to calculate the absorption with three points in the Improved Power Word: Shield Talent is the following:

[(BASE * 1.15) + BONUSHEALING * 0.30] = ABSORB

With our numbers

[(1265 * 1.15) + 464 * 0.30] = 1593.2 ~ 1593

Instead, the formula that should be utilised is the following:

[(BASE + (BONUSHEALING * 0.30)] * 1.15 = ABSORB

With the same numbers, this leads to:

[(1265 + (464 * 0.30)] * 1.15 = 1614.83 ~ 1615

The difference between the two values increases the more Bonus Healing the Priest has when utilising the second formula. As mentioned before, Gear doesn't affect the talent whatsoever in the first formula.

I have based this off of the following thread:
http://www.arenajunkies.com/topic/8885-improved-power-word-shield-question/

It quickly becomes clear that both opinions are stated, however the vast majority of Priests on Retail only managed to make the absorption values explicable by putting the numbers into the second formula, which suggests that this is how it did work on Retail.

**Comment by devidao** [comment]
Fixed, coming soon on PTR.

**Comment by Nzzoth** [comment]
Fix denied on PTR.

**Comment by Nzzoth** [comment]
Fix confirmed on PTR.

**Comment by Nzzoth** [comment]
Fix confirmed on PLTR.

**Comment by Nzzoth** [comment]
Live as of patch 15.
