### ISSUE TITLE
Summoning new pet does not reset its cds.

### ISSUE THREAD

**Issue by teddys** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3587]
How to reproduce:
You need 2 clients, on one create an orc warlock
.levelup 70
.learn 691 (Stummon felhunter)
.add 16389 (Grimoire of spell lock)
spec into fel domination (does not matter which talents you choose in order to get fel domination)
.t test
On the other one create a draenei priest
.levelup 70
.mod hp 1000000000
.t test

With warlock, use the grimoire to teach your pet spell lock. Cast spell lock on the priest and follow it by resummoning a new felhunter using fel domination. Try to spell lock after new pet is summoned.

Current situation : After resumonning a pet, cd of its abillities ( devour magic, spell lock etc ) does not reset.
Expected : After resumonning a pet, all of its cooldowns are reset.

This works fine for mages.

**Comment by Involve** [comment]
As far as i remember the cooldowns of the pet should only reset if you dismiss your current before resummoning a new one (possible via command). Most likely same thing goes for hunters.
However, this is not resetting the cooldowns on feenix either so your point is still valid. Correct me if I'm wrong please.

**Comment by teddys** [comment]
no longer an issue
