### ISSUE TITLE
Food does not buff

### ISSUE THREAD

**Issue by ovpavel** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3589]
Food does not buff after the patch Project Archangel 2.4.3 - Patch 13.8

**Comment by warlee** [comment]
Which food precisely do you have on mind?...

**Comment by Yiemeh** [comment]
In my case it was ravager dog. The buff is applied after 10 seconds of eating, but as soon as my character stands up the buff is lost.

**Comment by warlee** [comment]
Issue confirmed, after eating food that gives additional buff, as soon as you stop eating the buff goes away.
Repro:

.add 27665 10 (Poached Bluefish)
Eat the food, wait 10 seconds. Right click off the 'eating' icon or stand up.
Notice that the spell power/spirit buff goes away.

**Comment by Forcy** [comment]
Good job boyz
