### ISSUE TITLE
Force Reactive Disk 

### ISSUE THREAD

**Issue by Salce** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3595]
http://www.wow-one.com/forum/topic/96504-force-reactive-disk/

**Comment by roblockster** [comment]
Support:

http://www.wowwiki.com/Patch_1.9.0

"The Force Reactive Disk's and Cloak of Fire's effects will no longer gain a benefit from effects that increase spell damage."

**Comment by Forcy** [comment]
It looks like it has 100% chance to trigger, it has no ICD and it also reflects damage back to all enemies rather then only the one that have blocked an attack. On my list

**Comment by Thetruecrow** [comment]
Edit : Thank you

**Comment by Involve** [comment]
Edit : Thank you

**Comment by Thetruecrow** [comment]
Edit : You're welcome.
