### ISSUE TITLE
Druid Talent - Heart of the Wild 

### ISSUE THREAD

**Issue by Craybear** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3598]
I noticed an issue with one of the Feral spec. talents today. 

Heart of the Wild:
Increases your Intellect by 20%. In addition, while in Bear or Dire Bear form your Stamina is increased by 20% and while in Cat form your attack power is increased by 10%.

20% Stamina in Bear Form or Dire Bear Form is not working. The Talent gives the intellect it is supposed to, and the attack power in Cat Form.

**Comment by Nzzoth** [comment]
Talent works almost fine.
If you learn the talent while in bear form it will only increase your intellect. However if you leave bear form and cast it again you will see the stamina increase.
Issue closed.
