### ISSUE TITLE
[Quests] An Apexis Relic

### ISSUE THREAD

**Issue by Virsaitis** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3601]
None of the Ogri'la quests are working at the moment. It was like this from the start of the server.

An Apexis Relic

http://www.wowhead.com/quest=11058/an-apexis-relic#comments

This quest leads to daily quest http://www.wowhead.com/quest=11080/the-relics-emanation

The script starting the even is not implemented into the shards. 

Script for these quests is the same. In this video the whole process of qeust is shown. https://www.youtube.com/watch?v=DuWzl5HbtiI

**Comment by devastator** [comment]
https://github.com/FeenixServerProject/Archangel_2.4.3_Bugtracker/issues/1304
