### ISSUE TITLE
Blood Furnace trash mobs hitting multiple times

### ISSUE THREAD

**Issue by gotmilk0112** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3603]
It seems that some mobs in Blood Furnace (Not sure if it's just on Heroic or not) are somehow getting multiple melee hits in a short amount of time.

In specific, the Adepts seem to do it most often. I was once hit by three melee attacks in less than 1 second, from a single Adept, doing almost 5,000 damage in 1 second.

It doesn't seem to be an ability, because all three of the hits were marked as regular melee attacks, so I can only assume that this is some kind of bug causing the Adept to hit 3 times in under a second.

**Comment by gotmilk0112** [comment]
Managed to screenshot a couple instances of it happening:

http://i.imgur.com/i0cwjAU.jpg
-Blocked attack
-Blocked attack
-Unblocked attack

All within half a second.

http://i.imgur.com/QZZnoFP.jpg
-Blocked attack
-Blocked attack
-Parried attack

All within half a second.

What's going on here?

**Comment by roblockster** [comment]
Thrash: chance for 2 extra attacks (1+2=3)

https://www.wow-one.com/database/index.php?spell=3391

"I aggro'ed these two guys and had to vanish in like 1s. I check combat log? 4.8k x 3 - wtf?"

http://www.wowhead.com/npc=17397/shadowmoon-adept#comments

**Comment by gotmilk0112** [comment]
Well, shit. That's obnoxious. Getting melee'd for almost 5k in 1 attack by a trash mob seems really excessive.

**Comment by devastator** [comment]
Yes, they have Thrash ability
