### ISSUE TITLE
Quest buged Theramore, Alliance: The end of the deserters

### ISSUE THREAD

**Issue by gussah** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3604]
The quest "the end of the deserters" is (probably) the last quest in the chain regarding the deserters in Theramore. You're suppose to swim out to a small island 'south east of the docks' and it is indeed there, quite near the docks, an abanded ship is nearby.  The red tagged NPC that you engage to attack, to get low health is suppose to turn green tagged and say something like 'sorry we made a bad choice' and then you're supposed to get 'Completed' but that doesn't happen. The NPC acts properly, as in regenates/evades and turns green tagged but one does not get it completed. 
I am farming SW rep and this maybe set me back. Thanks in advance.
http://www.wowhead.com/quest=11134/the-end-of-the-deserters
(info/map loc)

**Comment by devastator** [comment]
https://github.com/FeenixServerProject/Archangel_2.4.3_Bugtracker/issues/1497
