### ISSUE TITLE
[Night Elves][Death bugged][PTR only] Ghost debuff does not apply

### ISSUE THREAD

**Issue by Kujiamini** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3608]
**Current situation on PTR only (not PLTR nor live)**
When you die as a Night Elf, and release spirit, you get the message "A more powerfull spell is active" and won't get the ghost debuff. Instead, this will happen: http://i.imgur.com/N8pgMHk.jpg?1
When you relog, you're alive in Wisp form instead of the night elf form.
http://db.hellground.net/?spell=20584

**Reproduction**
Create a Night Elf rogue
.levelup 69
.damage 4404 on yourself

1. Release spirit. You'll be teleported to the nearest GY, and be in the NE ghost form. But instead of having the ghost debuff, you'll have the message "A more powerfull spell is active". You won't be able to spirit ress or to corpse run. 
2. Try to talk to Conservator Ilthalaine, near the GY. Try to accept the quest, and see that it won't be in your quest log.
3. Try to use Sinister Strike on any beast around you. Observe that you won't be able to, but that no message appears on screen.
4. Try to eat Tough Gunk of Bread, and see the message "You can't do that while you're dead".
5. Relog, and see that you are alive again, but in Wisp Form.

**Comment by devidao** [comment]
Could not reproduce on PTR

**Comment by devastator** [comment]
Could not reproduce either. Seems to work properly
