### ISSUE TITLE
[Priest][Talent] Shadowform cooldown bug

### ISSUE THREAD

**Issue by paaske** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3609]
After the new patch added today I am unable to enter shadowform a 2nd time after logging in on my character. I get the error "Spell is not ready". It happens again upon relog, enter shadowform but can't a 2nd time.

**Comment by Kujiamini** [comment]
Reproduction:
Create a Priest
.levelup 69
.learn 15473 (shadowform)

Use shadowform, exit shadowform, wait for the cooldown to be ready. Observe that you can't use shadowform anymore..

**Comment by Psynic** [comment]
the Bug appears all the time, even if I wait for the global cooldown, i have to wait 2-3 seconds before i use shadowform after healing... that makes the shadow totally crap in pvp. Please fix this.
Only a relogg helps.

**Comment by Kaiitothewai** [comment]
This should be fixed on Live
