### ISSUE TITLE
[Shaman] Two-Handed Skill from Weapon Master isn't right

### ISSUE THREAD

**Issue by kremfaen** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3610]
The two-handed axe skill can be learned from weapon masters, but is only supposed to be learned through talents.

**Comment by Nick91** [comment]
Maybe you posted this on the wrong tracker (this is 2.4.3, not 1.12.1).

http://wow.gamepedia.com/Patch_2.3#Shaman
> Two-Handed Axes and Two-Handed Maces are now trainable by all Shaman at the appropriate weapon masters. The Enhancement talent has been replaced by Shamanistic Focus.

**Comment by Nzzoth** [comment]
He has, thanks and closed.
