### ISSUE TITLE
Rocket boots Xtreme Lite Bugged

### ISSUE THREAD

**Issue by druidenmin** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3611]
Hey Dev team, id like to report that the Engeneering item " Rocket boots Xtreme Lite" does not work. when i use the item i just goes on cooldown without taking effect, please do something about this issue, i belive loads of people are complaining about it and want it fixed. 

Thanks

**Comment by Nzzoth** [comment]
Hello Druidenmin, we're aware of the issue and it will get hotfixed as soon as possible.
I'm not denying this issue but I'm closing it as developers are aware and there's no need for this issue to be open.

Kind regards.
