### ISSUE TITLE
Cant use abillities with cooldown in arena

### ISSUE THREAD

**Issue by teddys** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3613]
after your 

 "Player spell cooldown handling has been rewritten. This solves issues with spells incorrectly being unavailable and fixes #3538 [rev5358][rev5364][rev5365][rev5370][rev5371]"

arenas are completely fucked up. First 2v2 game I played today I could not use sprint, next game it was pvp trinket + sprint and next game it was evasion, sprint, ghostly strike, pvp trinket and vanish.
reproduction guide : join arena and try to use your spells :)))))))))))))))))))))))))))))))))))))))))

revert this idiotic fix please

thx

**Comment by Nzzoth** [comment]
A hotfix has been applied, incase this is still an issue please comment here.

Closed.
