### ISSUE TITLE
[Quests] bug "The Missing Diplomat"

### ISSUE THREAD

**Issue by gussah** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3615]
Quest bug: "The Missing Diplomat"

The part when you talk with Mikhail in Wetlands inn, he asks you to confront Tapoke Jahn.
The funny part is that I saw Tapoke inside the inn and as I take the quest to then talk to him (inside OR outside(as he is supposed to run out, I guess)) but he simply disappears from existence. 

One time I saw him outside but I couldn't talk to him there either.
Thanks.

**Comment by Nzzoth** [comment]
#3414 
Duplicate closed.
