### ISSUE TITLE
[Warrior] Whirlwind hits with only one Weapon

### ISSUE THREAD

**Issue by Centan** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3617]
Happened with Patch 13.11.1, 13.11.2 or 14
Whirlwind bugs now when dualwielding weapons. This makes the Fury-PvE warrior incredibly bad since its one of the main DPS abilies.

How it should be: Whirlwind hits with both weapons dealing Weapondmg from each weapon

How it is: Whirlwind only hits with the main weapon

Video evidence:
https://youtu.be/46loeQweoWk

**Comment by Centan** [comment]
just got fixed with recent patch

**Comment by Nzzoth** [comment]
Glad to hear closing the issue, if it reappears feel free to comment and I will review it and reopen it.
