### ISSUE TITLE
Shattered Hand Assassin crash bug

### ISSUE THREAD

**Issue by gotmilk0112** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3623]
In Shattered Halls, there is something highly bugged with the rogue enemies, Shattered Hand Assassin.

For some reason, these mobs randomly cause peoples' clients to get errors, causing the client to crash. I see someone else opened an issue about this:

https://github.com/FeenixServerProject/Archangel_2.4.3_Bugtracker/issues/3594

and the admin said the bug was hotfixed, but it's still happening.

**Comment by Nzzoth** [comment]
Closing this due to being a duplicate. Feel free to comment on the other issue.
