### ISSUE TITLE
[Item] Thunderfury slowing effect removes itself.

### ISSUE THREAD

**Issue by Jandis** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3626]
The 20% attack speed debuff component of Thunderfury proc currently removes itself when it procs with the debuff already applied. It will then no longer be successfully applied to the target upon proc while the 25 nature resistance debuff is still active.

This can be confirmed with the use of   /run message(UnitAttackSpeed("target"))

Expected behavior: Both the slowing effect and nature debuff should refresh upon proc.

**Comment by devidao** [comment]
Fixed, coming soon on PTR.

**Comment by Nzzoth** [comment]
Fix confirmed on PTR.

**Comment by anaaz** [comment]
Fix denied on PLTR. 
When it procs it refreshes the 25 nature resistance reduction debuff, however it overwrites and removes the attack speed slow

**Comment by lajhar** [comment]
On live (15.6)
