### ISSUE TITLE
Unleashed Hellion's Rain of Fire Ability

### ISSUE THREAD

**Issue by Involve** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3628]
The Creature Entry: 25002 is casting Rain of Fire (SpellID: 20754). For unknown reasons, the ability is doing way more damage than intended. (~12.000/Tick).

**Comment by GitHubReporting** [comment]
Screenshot to prove it.

![wowscrnshot_062715_184249](https://cloud.githubusercontent.com/assets/13081867/8394511/d0fe7034-1d00-11e5-9113-12855ceeab1a.jpg)

**Comment by GitHubReporting** [comment]
Screenshot taken June 27, 2015

![hellfire death](https://cloud.githubusercontent.com/assets/13081867/8394529/9c7a0138-1d01-11e5-8670-bed5bb9ebf71.jpg)
