### ISSUE TITLE
Wind Stones in Silithus not functioning on Archangel

### ISSUE THREAD

**Issue by neyen** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3631]
As a level 60 NE druid, wearing all three pieces of the Twilight Trappings, the wind stones simply give me a greeting when I right click them. This is the case for all three types of wind stone (lesser, normal, greater) and happens with or without my having the quest Abyssal Contacts, which I thought might be relevant but appears to have no effect on my inability to summon via the wind stones.

**Comment by Hypnotizer** [comment]
#1192 and #1469

**Comment by neyen** [comment]
Right. I see you provided a reference to a post from 2012. Being that this is 2015, and no actual response has been made to that post, are you simply suggesting that we never speak of this matter again? Please forgive my lack of experience on this website. Thank you.

**Comment by Nzzoth** [comment]
Closed due to being a duplicate.
