### ISSUE TITLE
Recipe: Transmute Primal Earth to Water can't be learned

### ISSUE THREAD

**Issue by exestar** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3632]
Can't Learn this recipe ( http://www.wow-one.com/database/?item=22916 ). Deleting cache and wtf didn't give any result. As you can see, i am revered with Sporeggar and i have enough skill to learn it. Every time i use recipe - it shows that "Spell is not ready yet".
![wowscrnshot_060915_185446](https://cloud.githubusercontent.com/assets/12816542/8062653/e39faadc-0ee1-11e5-86ba-b68689f36627.jpg)

**Comment by devastator** [comment]
Could not reproduce the issue. Please comment if the issue still exists
