### ISSUE TITLE
[Quest] "Teleport This!" uncompletable

### ISSUE THREAD

**Issue by gotmilk0112** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3635]
The quest "Teleport This!" in Netherstorm is impossible to complete because of some kind of bug with the quest item.

You're supposed to use the provided quest item (Mental Interference Rod) on the mob "Cyber-Rage Forgelord", which mind controls it and then you use one of the mob's abilities near the teleporter.

However...whenever I try to use the quest item on that mob, it keeps saying "Immune" and nothing happens.

Enslave Demon doesn't seem to work either, also giving "Immune".

So...what's going on? I had heard a while ago that Archangel disabled all mind control effects to prevent abuse, so I'm assuming that this is a result of that change?

**Comment by devastator** [comment]
https://github.com/FeenixServerProject/Archangel_2.4.3_Bugtracker/issues/605
