### ISSUE TITLE
10 Spell Crit Gem dosen't work so well :D

### ISSUE THREAD

**Issue by Datbase** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3640]
Report ID: 3640

Reporter Name: Frostboltlol

Date/Time: 00:49 CET 22.06.15

Error Severity: High

Zone/Instance: Everywhere

What type of error occurred?: Scaling

What was the actual result vs. the expected result?:

If you sockel 10 Spell Crit you only get 4 Crit value.

External/Related Links:

Crit Value with Haste Socket:
http://www.bilder-upload.eu/show.php?file=3680c4-1434927714.jpg

T6 Chest with Crit Socket:
http://www.bilder-upload.eu/show.php?file=22dc7d-1434927815.jpg

Crit Value with Crit Socket:
http://www.bilder-upload.eu/show.php?file=3a7df4-1434927820.jpg

**Comment by Hypnotizer** [comment]
The gem works properly according to PLTR and PTR.
Gleaming Lionseye(+10 Spell critical rating gives its propper 0.45% spell crit per gem)
Tested on several items.

So not sure where your issue lays at.

**Source**
Gleaming Lionseye was renamed to Smooth Lionseye in 4.0.1
http://wow.gamepedia.com/Design:_Gleaming_Lionseye_(Shattered_Sun_Offensive)

http://www.wowhead.com/item=32207/smooth-lionseye#comments
http://www.wowhead.com/item=32205/smooth-lionseye#comments

**Comment by Doppelmoral** [comment]
I'm not sure how to interpret your screenshots, but maybe your 10crit gem gives only 4 spellcrit because it is a 4crit gem ? Please don't tell me you gemmed a vendor gem in that T6 chest, failed to notice (even while screenshotting it) and made that report ?

**Comment by Doppelmoral** [comment]
What happened to the 6 spirit and 9mp5 in the last screenshot though ?
