### ISSUE TITLE
Archimonde [Doomfire]

### ISSUE THREAD

**Issue by Stoniz** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3641]
**Current situation**: Only the initial dmg of doomfire is being absorbed by damage absorbing mechanics.

**Expected results**: Damage absorbing mechanics should work on the rest of the damage/ticks as well.

**Description**: Damage absorbing mechanics are only working on the first tick when you get doomfire debuff,For example Casting (fireward/Powerword:Shield) after you already got hit by doomfire will not absorb anydmg.

To test this issue you will need 1 client:
Create any class you want.

1. .levelup 70
2. .modify hp 200000
3. .cast self 27128 (Fireward) OR .cast self 25218 (Power word: shield)
4. Wait for weakened soul debuff to go off so you can refresh the shield immediately after the first one goes off.
5. .cast self 31944 (Doomfire)
6. .cooldown
7. .cast self 27128 (Fireward) OR .cast self 25218 (Power word: shield)

Watch the rest of the dmg ticks not getting absorbed.

Screenshots: 
![test](https://cloud.githubusercontent.com/assets/12039540/8289466/7e92eee6-1914-11e5-94bd-9db4c93faf51.png)

**Comment by devidao** [comment]
Fixed, coming soon on PTR

**Comment by Nzzoth** [comment]
Fix confirmed on PTR.

**Comment by anaaz** [comment]
Fix applied to live with Patch 15.2
