### ISSUE TITLE
Shadowstep underwater

### ISSUE THREAD

**Issue by teddys** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3646]
How to reproduce:
You need 2 clients, on one create an orc warrior
.mod hp 1000000000
On the other one create a human rogue
.levelup 70
.learn 36554 ( step )

With both characters teleport to any kind of are with water and then with rogue use shadowstep on the warrior.

Current situation : using shadowstep underwater teleports you to the bottom of the sea instead of behind your target

Expected : using shadowstep underwater teleports you behind your target

Most likely related to the movement issue because using shadowstep normally on a moving target does not teleport u anywhere near the actual position of the target.

/e same thing happens when u try to shadowstep to someone in the air .. u will get teleported to the ground

**Comment by devidao** [comment]
Fixed, coming soon on PTR

**Comment by Nzzoth** [comment]
Fix denied on PTR.

**Comment by devidao** [comment]
It was my foolish fix mistake, fixed again.

**Comment by Nzzoth** [comment]
Fix confirmed on PTR.

**Comment by Nzzoth** [comment]
Fix confirmed on PLTR.

**Comment by Kaiitothewai** [comment]
When will this finally hit Live?
