### ISSUE TITLE
Transmute recipe cant be learned (skyfire diamond)

### ISSUE THREAD

**Issue by Donoven** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3652]
hey there
ive reached honored with thrallamar and bought the recipe, i have the required skill lvl, but i cant learn it. i get an error massage saying "spell is not ready yet", my charecter does the animation but the recipe does not get learned.
thanks in advance to anyone who can help me :)

**Comment by devastator** [comment]
https://github.com/FeenixServerProject/Archangel_2.4.3_Bugtracker/issues/3632
