### ISSUE TITLE
Item : [Wolfshead Helm] Not working.

### ISSUE THREAD

**Issue by Stoniz** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3656]
Link to item 
Wowhead: http://www.wowhead.com/item=8345/wolfshead-helm
Feenix database: https://www.wow-one.com/database/index.php?item=8345
**Current situation**: 
 When shape shifting into Cat form/Bear form the druid is not gaining 20 energy/5 rage.

**Expected results**:
 When shape shifting into Cat form the Druid gains 20 energy, when shape shifting into Bear form the Druid gains 5 rage.

To test this issue you will need 1 client 
Create a druid.

1. .levelup 70
2. .add 8345
3. .learn all_myclass or (.learn 768) (.learn 5487)
4. .gm off
5. .gm visible on
6. Wear the helm obviously
7. Shape shift into cat form (Notice how you don't get the 20 energy from the helm)
8. Shape shift into bear form (Notice how you don't get the 5 rage from the helm)

**Proof**
http://www.wowhead.com/item=8345/wolfshead-helm#comments:id=12322
http://www.wowhead.com/item=8345/wolfshead-helm#comments:id=628392 (Stats confirmation)

**Comment by devastator** [comment]
https://github.com/FeenixServerProject/Archangel_2.4.3_Bugtracker/issues/2610
