### ISSUE TITLE
[Warrior] Spell reflect 

### ISSUE THREAD

**Issue by Stoniz** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3657]
Even if warriors in most situations don't need to spell reflect fear it is still very crucial when you don't have enrage/death wish.
Another thing is casting spell steal while warrior have spell reflect up.

**Current situation**: 
- If a mage cast spell steal on you while having Spell reflect up it will consume spell relfection without making the mage lose one of his Buffs.
- Spell reflecting fear on a target with Fear ward will not consume Fear ward
  Example : If a warlock casts fear on you and you end up spell reflecting it he will be immune Due to fear ward effect but Fear ward will not be consumed.

**Expected results**:
- If a mage cast spell steal on you while having Spell reflect up it will consume spell reflection and make the mage lose one of his Buffs.
- Spell reflecting fear on a target with Fear ward should consume fear ward.

To test this issue you will need 2 clients .
#### Preparing characters phase.

**On first client :**

Create a warrior
1. .add  32375 (bulwark for lulz and equip it!)
2. .learn 23920 (Spell reflection)
3. .gm off
4. .gm visible on
5. .modify rage 9999999

**On second client :**

Create a mage/warlock  (Mage on same faction as warrior so you can buff yourself and the warrior, Warlock on opposite faction so you don't have to /duel to test)

**For Mage :**
1. .l 30449 (Spellsteal)
2. .l 1459 ( Arcane intellect Buff the warrior and yourself)
3. .gm off
4. .gm visible on
5. .modify mana 6666
6. .go "warrior char name" (without The " ")

**For warlock :**
1. .l 6215 (Fear)
2. .l 6346 (Fear ward so you don't have to make a priest to buff it,and cast it on yourself also make sure it's up all the time)
3. .gm off
4. .gm visible on
5. .modify mana 6666
6. .go "warrior char name" (without The " ")
#### Testing issues phase :

**Reflecting fear issue**
1. Duel the warrior and accept
2. Cast spell reflect with your warrior.
3. Cast Fear on the warrior (Make sure you cast fear before Spell reflection effect runs out)
4. Notice how Fear ward does not get consumed when you spell reflect fear.

**Reflecting spell steal issue**

1.Make sure both the mage and warrior are buffed with arcane intellect or any other spell that is considered magic effect and can be spell stolen
2.Duel the warrior and accept
3.Cast spell reflect with your warrior.
4.Cast spell steal on the warrior with your mage (Make sure you cast spell steal before Spell reflection effect runs out)
5.Notice how spell reflect gets consumed but the mage does not lose the buff.

Repeat the mage spell steal issue to make sure it's not resist or something.

**Proof**
- For the fear ward issue i don't think a proof needs to be provided but if it's requested i'll try to find and bring it up.
- For the spell steal issue
  http://www.wowhead.com/spell=23920/spell-reflection#comments:id=291275
  http://www.wowhead.com/spell=30449/spellsteal#comments:id=291276

.

**Comment by devidao** [comment]
Fixed, coming soon on PTR

**Comment by Nzzoth** [comment]
Fix denied on PTR.

**Comment by Nzzoth** [comment]
Fix denied on PTR.

**Comment by Nzzoth** [comment]
Fix confirmed on PTR.

**Comment by lajhar** [comment]
On live (15.4)
