### ISSUE TITLE
[Mage] Spell steal issue.

### ISSUE THREAD

**Issue by Stoniz** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3658]
##### Important notes and examples that you need to read before claiming anything
- Spell stealing a buff that has over 2 mins duration will give you a buff that has a 2 mins duration
  - Example : Spell stealing Power word : Fortitude which as 30 mins duration will give you a   Power word : Fortitude buff with 2 mins duration
- Spell stealing a buff that has under 2 mins duration will give you a buff with it's current duration (While it was on the target)
  - Example : Spell stealing Power word : Shield which has 5 secs duration will give you a Power word : Shield buff that has 5 secs duration.

http://wowwiki.wikia.com/Spellsteal

**Current situation**: 
- Spell stealing a buff that you already  have and has lower duration than your current buff will replace it's duration.

**Expected results**:
- Spell stealing a buff that you have and has lower duration than your current buff should not replace your current buff duration

To test this issue you will need 2 clients .
#### Preparing characters phase.

**On first client :**

Create a mage
1. .l 30449 (Spell steal)
2. .l 27126 (Arcane intellect)
3. .l 33405 (Ice barrier)
4. .gm off
5. .gm visible on

**On second client :**

Create another mage!
1. .l 30449 (Spell steal)
2. .l 27126 (Arcane intellect)
3. .l 33405 (Ice barrier)
4. .gm off
5. .gm visible on
6. .go "first mage character name"
#### Testing issues phase
1. Buff the first mage with arcane intellect then wait till the buff has less than 30 mins duration (Wait 1 min or 2 mins to easily see the issue)
2. Buff the 2nd mage with arcane intellect make sure it has longer duration than the first mage's arcane intellect.
3. Set up a duel.
4. With your 2nd mage (The one that has longer buff duration) cast spell steal on the other mage (**NOTICE** : your arcane intellect gets replaced with 2 mins duration).
5. Cast Ice barrier with your first mage then wait 20sec.
6. Cast ice barrier with your 2nd mage then cast spell steal immediately on the first mage (**NOTICE** :  your fresh ice barrier duration gets replaced with the spell stolen ice barrior duration even thou they have the same damage absorb (None of them is powerful than the other)
#### Proof

> - Spellsteal will no longer overwrite a longer duration buff.
> 
> http://wowwiki.wikia.com/Patch_2.4.0

**Comment by hestefinger** [comment]
eatleast yours work.. sometimes i gotta cast it 3 times, where it actully lands on target, and nothing happens except i loose mana, and its no resist or something like that, it just doesnt steal spell..

**Comment by devidao** [comment]
it was fixed on https://github.com/FeenixServerProject/Archangel_2.4.3_Bugtracker/issues/3657

**Comment by lajhar** [comment]
On live (15.4)
