### ISSUE TITLE
Elemental Sharpening Stone

### ISSUE THREAD

**Issue by Arma777** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3660]
Current:
When you use a Elemental Sharpening Stone (http://database.wow-one.com/?spell=22757) in your weapon, stats don't change.
Desired:
When you use a Elemental Sharpening Stone in your weapon, stats changed and Elemental Sharpening Stone worked.

**Comment by Arma777** [comment]
Please note

**Comment by devastator** [comment]
https://github.com/FeenixServerProject/Archangel_2.4.3_Bugtracker/issues/3465
