### ISSUE TITLE
[MAJOR][Shaman][Core] Windfury Shared Internal Cooldown

### ISSUE THREAD

**Issue by braide** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3662]
Windfury weapon imbue does not have shared internal cooldown on the procs. It is suppose to have 3 seconds shared internal cooldown for all weapon imbued with Windfury. Meaning you can only proc at maximum 1 Windfury per 3 seconds, no matter how many weapons you have equipped (dual-wielding etc) or if you just swapped to a new weapon imbued with WF. Only 1 WF proc per 3 seconds. 

Currently on Archangel shamans can proc many windfury procs instantly and after each other, which is completely broken especially in PvP. 

Sources:
http://web.archive.org/web/20080204142249/http://elitistjerks.com/f31/t13297-enhance_shaman_collected_works_theorycraft_vol_i/

and you scroll down to IV. Windfury Mechanics

 "Many shaman will correctly use a slow MH weapon but use a fast OH such as a dagger, generally because its easier to find fast OHs than slow ones. This combination however means that your OH is much more likely to be the first one to hit outside of a WF cooldown and will "steal" the potential chance to proc, placing your main hand on lockdown. In order to maximize the potential for MH procs the OH needs to be as slow as possible."

http://wowwiki.wikia.com/Enhancement_gear_BC
"Weapons for an Enhancement Shaman should be as slow as you can get. 2.6-2.8 is generally the slowest speed of single-handed weapon available. This speed also applies to the shaman's off-hand because if you have a fast off-hand it will get the windfury proc more often than your main hand, and it does half the damage of the main hand." 
Meaning off hand eating Main hand procs.

http://wowwiki.wikia.com/Windfury_Weapon
"It is suggested to have Windfury enchanted for mainhand and another enchant (like [Flametongue Weapon]) on the off-hand. This is because if Windfury procs on one weapon, it will not proc off the other at the same time, potentially "wasting" proc opportunities. Slower weapons are preferred."

and patch notes:
"Patch 2.1.0 (22-May-2007): Mixing two different ranks of "Windfury Weapon" while dual-wielding will no longer increase the number of "Windfury Weapon" procs."
Referring to that different ranks of windfury had separate internal cooldown, which was unintended. 

I can probably find more sources since I know this was the case (played enhancement shaman during retail). You can also look at any old enhancer clip from retail and see that they never proc windfury more than once every 3 seconds.

**Comment by teddys** [comment]
how about u provide evidence of such claim
i myself tested this about 3-4 months back and the 3sec internal cd was working correctly

**Comment by braide** [comment]
the evidence of that it does not work on feenix or the evidence that it should be 3 sec internal?
I did see a change today where the off hand imbue can no longer proc the main hand. That might resolve the matter if they actually had internal cd imeplemented before. I will have to test this again after today.

**Comment by braide** [comment]
Okay. It seems to be working. This topic can be closed, not sure if I can remove/close the topic myself. The RNG seed inside arena seems ridiculus though (as in the number of wf procs or the proc %), really ridiculus actually. Might look into that.

**Comment by teddys** [comment]
i asked for evidence because i specifically tested the 3 sec internal cd around 3 months ago and it was working correctly
