### ISSUE TITLE
Ashtongue Talisman of Vision Enhance Proc Rate is Incorrect

### ISSUE THREAD

**Issue by roblockster** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3663]
Current Situation: With Ashtongue Talisman of Vision (32491) equipped, Stormstrike (17364) has about a 90% chance of proccing Power Surge (40466), a 275 AP buff.

Desired Situation: With Ashtongue Talisman of Vision equipped, Stormstrike should have a 50% chance of proccing Power Surge.

Reproduction:
Create a Shaman
.levelup 69
.learn 17364
.modify rep 1012 42000
.add 32491

Attack a target (like Org dummy) and cast Stormstrike. About 9/10 times this will activate Power Surge.

**Comment by devidao** [comment]
Fixed, coming soon on PTR

**Comment by Nzzoth** [comment]
Fix confirmed on PTR.

**Comment by lajhar** [comment]
On live (15.3)
