### ISSUE TITLE
[Item] Timbal's Focusing Crystal

### ISSUE THREAD

**Issue by Hypnotizer** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3664]
**Current Situation:**
Timbal's Focusing Crystal has a chance to cast an instant shadowbolt.
When you are casting Hellfire will you get backfired with shadowbolt meanwhile casting it, taking more damage back than you should.

**Expected Result:**
Should not take damage/self harm back from Timbal's Focusing Crystal shadowbolt when casting Hellfire.

**How to reproduce:**
1. .levelup 70
2. .additem 34470 (Timbal's Focusing Crystal)
3. .l 27213 (Hellfire Rank 3)
4. .m hp 2000000
5. Use spell Hellfire and read in combat log (like listed under and you'll see that you take damage back from Hellfire)

**Screenshot:**
![shadowbolt test](https://cloud.githubusercontent.com/assets/6118472/8721432/e08fc066-2bba-11e5-9df1-befa1358eac8.png)

**Comment by devidao** [comment]
Fixed

**Comment by Nzzoth** [comment]
Fix denied on PTR.

**Comment by devidao** [comment]
Resolved server crash issue

**Comment by Nzzoth** [comment]
Fix denied on PTR.

**Comment by devidao** [comment]
Re-fixed

**Comment by Nzzoth** [comment]
Fix confirmed on PTR.

**Comment by Nzzoth** [comment]
Fix confirmed on PLTR.

**Comment by Nzzoth** [comment]
Live as of patch 15.
