### ISSUE TITLE
ferals and warriors gets rage from dodged and parried attacks

### ISSUE THREAD

**Issue by repae1f** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3667]
fix plz
or give rogues same ability gets energy from dodged and parried attacks

**Comment by luftkaffe** [comment]
This makes dodge stacking warriors OP

**Comment by Lederi** [comment]
## Current situation
Druids and warriors get rage before a damage mitigation and  avoidance
 
## How it should be
Druids and warriors should get rage after damage mitigation, avoidance,  resistance and absorption. Only the incoming damage should generate rage, not the possible damage.

[bluepost](https://web.archive.org/web/20080624041006/http://forums.wow-europe.com/thread.html?topicId=83678537&sid=1&pageNo=1#16)
>For Taking Damage (both pre and post expansion): 
Rage Gained = (Damage Taken) / (Rage Conversion at Your Level) * 2.5 

>Rage Conversion at level 70: 274.7 

## Example
You are a warrior with 50% Armor. A level 70 mob attack you with a 10.000 damage ability
* **Current situation:** you get **10000/274.7 x 2.5 rage = 91 rage*, no matter if you dodge or resist or whatever
* **How it should be:**
	- if you dodge/parry you should get: *0 rage*
	- if you getting hitted you get minus armor: *10000 x (100%-50%)/274.7 x 2.5 rage = 46 rage*
	- if you getting hitted you get minus armor and block 500 damage: *(10000 x (100%-50%) -500)/274.7 x 2.5 rage = 41 rage*
	- if you getting hitted you get minus armor and block 500 damage and absorb 2000, like [Power Word: Shield]: *(10000 x (100%-50%) -500 -2000)/274.7 x 2.5 rage = 23 rage*
	- if you resist a the spell to 75% you get: *10000 x (100%-75%)/274.7 x 2.5 rage = 23 rage*

**Comment by Dorakrab** [comment]
video proof : 
https://youtu.be/9oJbEhGBkwQ?t=2m58s

**Comment by devidao** [comment]
Fixed that from dodged/parried/missed attacks rage is no increased

**Comment by Kaiitothewai** [comment]
Any ETA for testing?

**Comment by lajhar** [comment]
On live (15.3)

**Comment by repae1f** [comment]
http://www.wow-one.com/forum/topic/108525-tanking-after-rage-fix/?page=2#comment-777410

**Comment by repae1f** [comment]
reopen plz

**Comment by Zerixx** [comment]
I fixed this unintentionally with my spell & stats reworking. As of, https://github.com/ServerProject/TBC-Core/commit/8ac26c0a9729a834f17500ce58dab359c19c4166 this doesn't happen anymore.
