### ISSUE TITLE
Restro Druid Lifebloom does not stack properly.

### ISSUE THREAD

**Issue by schoems** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3668]
Lifebloom is a healing spell of the restro druid, wich heals over time and has a bonus heal when the spell expires or is clerified.
You can stack this spell up to 3 times, where the healing effects are doubled or trippled.
So normaly you should get an increasing HoT and an incresing healing amount at the end.
At this server only the HoT is increasing with the stacks and the healing amount at the end stays always the same.

**Comment by Lederi** [comment]
[wowwiki Revision as of 16:59, September 4, 2007](http://wowwiki.wikia.com/Lifebloom?oldid=861391)
> Notes
- This spell was introduced in The Burning Crusade.
- Only the HoTs stack, not the end heals.

**Comment by Nzzoth** [comment]
Rejected and closed.
