### ISSUE TITLE
[Quest] Tower of Althalaxx part 4, not scripted.

### ISSUE THREAD

**Issue by wormrunner** [FeenixServerProject/Archangel_2.4.3_Bugtracker#367]
This is not a hindrance to getting the next part of the chain, but when turning in the soul gem in the fourth part of the Tower of Althalaxx quest chain, Delgren is supposed to break the gem, which releases an old soul who talks about the next step in the chain.  I have copied from a comment on the quest in http://www.wowhead.com/quest=970#comments:40

---------------

Upon completion Delgren the Purifier will smash the soulstone and a night elf spirit in a red kilt named Sargath will appear. This dialogue will follow:

Delgren the Purifier says: A simple enough task to break this soulstone!

Glowing Soulgem bursts open!

Sargath says: In the throes of the Sundering, Ameth'aran was at the whim of the terror that gripped the land. There was little hope for survival.
Sargath says: Athrikus came to us. He told us that he could save us from harm. He cast a spell upon us to protect us from harm.
Sargath says: When the shaking stopped, his true motives were revealed. We were trapped, and he was slowly draining our powers.
Sargath says: There were hundreds imprisoned by his spell. Now only a few remain in their prisons. He would speak to us sometimes.
Sargath says: He worried that his power weakened, that soon even we last of his precious soulgems would fade and die.

Delgren the Purifier says: Then we must put an end to Athrikus Narassin. Tell me, spirit, where might we find the other soulgems, to undo his magic?

Sargath says: His lieutenant, Ilkrud Magthrull possesses a tome which might indicate the location of the remaining soulgems.

Sargath fades into the mist...

**Comment by devastator** [comment]
Applied to Live with patch 12.0
