### ISSUE TITLE
 [Wrangle Some Aether Rays!] 

### ISSUE THREAD

**Issue by valeriu28** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3671]
You're supposed to use the quest item on a Aether Ray when its damaged ( below 20%hp ) for credit ; Rise and repeat 5 times, on here it doesn't work tho and the quest item doesn't do anything but a visual channeling. Furthermore, this is one of the few dailies for Sha'tari Skyguards and together with quests like  [An Apexis Relic] +  [Guardian of the Monument] which are also bugged, make the Ogri'la-Sha'tari Skyguards quest hub closed on this server. Thanks.

**Comment by roblockster** [comment]
2851 1305
