### ISSUE TITLE
llidan Stormrage

### ISSUE THREAD

**Issue by ovpavel** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3672]
http://wowwiki.wikia.com/Illidan_Stormrage_(tactics)

1.  Flame Crash runs for players
2. Parasitic Shadowfiend It does not disappear after eveid boss
3. When you start a single player boss, resulting in a call parasites endlessly, resulting in server load. Sow it is impossible to access the server because the server does not operate.

**Comment by ovpavel** [comment]
Our raid just dropped server.

**Comment by ovpavel** [comment]
Three pools of running after the tank, have hit the tank.
Boss became impossible to kill.

**Comment by ovpavel** [comment]
Boss moves as the demon phase, ran to the warlock tank and killed in melee

**Comment by Raynez** [comment]
Just did illidan on our t6 pug (Impulse) on this happening. I was told this kind of bug is on prince also, that the Infernals is moving when crashing down, i dont have proof on Prince part thought. Anyway, here is my stream showing that Illidan flame crash is randomly moving all over the place. 

Starting here: http://www.twitch.tv/g0lba/v/8727853?t=1h000m23s (1h00m00s)
Worst part where you can really see it, starts here: http://www.twitch.tv/g0lba/v/8727853?t=1h28m25s (1h28m25s)
OR at
http://www.twitch.tv/g0lba/v/8727853?t=1h36m06s (1h36m06s)

This has to be fixed. as i said, I have been told that illidan isn´t the only issue, aswell as prince in kara. Maybe even supremus too or other bosses that has stuff on ground. 
Please fix, thanks.

/regards Golba

**Comment by repae1f** [comment]
On demon phase Illidan come to tanking warlock and killing him by shadow blast in melee. Boss now unkillable.

**Comment by Forcy** [comment]
We are already looking in a solution for this issue. A fix for it will be applied in the upcoming hours.

**Comment by ovpavel** [comment]
When you start a single player boss, resulting in a call parasites endlessly, resulting in server load. Sow it is impossible to access the server because the server does not operate.

**Comment by Forcy** [comment]
Hotfix applied during the last restart
