### ISSUE TITLE
Droprates on Baron Rivendare

### ISSUE THREAD

**Issue by kildrazien** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3673]
I have farmed Baron Rivendare for something like 12 hours over the past 3 days. I have gotten every single item on his normal droplist save for Shadowcraft Pants. I kill him once every 15 minutes, about 50 kills. It is EXTREMELY unlikely that after all of this farming not getting the pants. Is the item actually on his loot table?

**Comment by devastator** [comment]
The item is on his loot table https://www.wow-one.com/database/?npc=10440 and has same chance to drop as the other leg parts. Bad luck just
