### ISSUE TITLE
Perception stealth detection

### ISSUE THREAD

**Issue by mondegoftw** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3682]
http://wowwiki.wikia.com/wiki/Stealth_(mechanic)

            previously activated for 50 points of stealth detection, equivalent to 10 levels.

I'm sure it doesn't do this. I doubt it gives any stealth detection at all.

Easiest way to test's probably to have two human rogues and giving stealth detection items to one of them - Elixir of the Searching Eye (22830) gives +15, Hyper Vision Goggles (23763) gives +30, assuming they work correctly. 

Drink elixir and equip helm on rogue A, stealth on rogue B. Walk to the max distance where rogue A can still see rogue B. Then stealth on rogue A (should be able to see rogue B, but B cant see A). Activate perception on rogue B, and he should be able to see A.

Slightly tricky to test, but it's doable, and CRUCIAL that stealth detection works properly for PvP.

**Comment by asdsha** [comment]
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ pls fix

**Comment by teddys** [comment]
https://github.com/FeenixServerProject/Archangel_2.4.3_Bugtracker/issues/2767

"closed" :))))))))

**Comment by devastator** [comment]
https://github.com/FeenixServerProject/Archangel_2.4.3_Bugtracker/issues/2551
