### ISSUE TITLE
Games crashes in Shattrah

### ISSUE THREAD

**Issue by gymno123** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3685]
After a WSG i got wow-error on my Shaman Shockerande in the loading screen after the game. It sais that the program is unable to read the files. When i tried to log back in after that the loading bar stopped half way thru and it crashed again.

I tried to use the unstuck feature on your website since it has helped me before but this time it did not.

Right now I cant log on my shaman at all cause it crashes every time. But my warrior is no problem.

Edit: After some time i could log back in on my Shaman, but then it was placed in Gadzetan, games crashed again when i used hearthstone to get to Shattrah. Still cant play.

**Comment by gymno123** [comment]
Works for now, Have no clue what happened. Will post if it happens again

**Comment by tekedot21** [comment]
Try deleting your cache and the WTF folder

**Comment by Nzzoth** [comment]
client sided issue, closed.
