### ISSUE TITLE
The line of sight

### ISSUE THREAD

**Issue by tekedot21** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3687]
Apparently, you fixed the line of sight issue, but HELL NO, you didn't do anything.
![1](https://cloud.githubusercontent.com/assets/1092091/9294797/613a275a-4458-11e5-804c-b02c3c200984.jpg)
![2](https://cloud.githubusercontent.com/assets/1092091/9294799/658bdca4-4458-11e5-9451-31e8b363f596.jpg)

What kind of a bug fix is this?

**Comment by Thetruecrow** [comment]
There are a few bad spots in Terokkar Forest that are bugged like this, but they are unrelated to the previous changes.

**Comment by devastator** [comment]
https://github.com/FeenixServerProject/Archangel_2.4.3_Bugtracker/issues/298
