### ISSUE TITLE
Mottled Drywallow Crocolisk never leash

### ISSUE THREAD

**Issue by deadman9001** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3692]
Horde side, 5th time I've had crocs chase me from thereamore to crossroads.

**Comment by devastator** [comment]
Should be fixed in mob_mottled_drywallow_crocolisk script

**Comment by devidao** [comment]
Fixed

**Comment by Nzzoth** [comment]
Fix confirmed on PTR.

**Comment by lajhar** [comment]
On live (15.4)
