### ISSUE TITLE
Timbal's Focusing Crystal

### ISSUE THREAD

**Issue by ohrerbohrer** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3693]
Timbal's Focusing Crystal does not do dmg, when the target is not in LoS! You can see the Animation for the shadow bolt, it also Triggers the icd of 15 sec but it does no dmg when the target is not in LoS. Blizzlike it should ignore LoS!

**Comment by Viikate** [comment]
Also it scales with spell power even it should not

**Comment by Pawx** [comment]
And is it normal that it procs when a person wearing it is dead?

**Comment by Viikate** [comment]
obviously not

**Comment by devidao** [comment]
Fixed, coming soon on PTR

**Comment by Nzzoth** [comment]
Fix deniedo n PTR.

**Comment by lajhar** [comment]
On live (15.6)
