### ISSUE TITLE
DR Groups

### ISSUE THREAD

**Issue by asdsha** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3697]
Currently there are no such DR categories as Managable Immobilizes and Random Immobilizes. Instead there's only Managable Roots group that includes all improved hamstring, improved wing clip, entangling roots, feral charge, imp hamstring, chastise and entrapment (?) which is totally wrong.
So as i said, normally, there should be four categories - Random/Manageable roots(entrapment, entangling roots) and Random/Manageable immobilizes (Imp hamstring, Imp wing clip / Feral charge, Chastise).

**Comment by devastator** [comment]
Please provide proofs.

**Comment by lajhar** [comment]
#3591
