### ISSUE TITLE
[Crash] whenever I go near felwood

### ISSUE THREAD

**Issue by Keldaan** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3700]
My wow.exe crashes every time I come near bashal aran (darkshore) or felwood.
This happened several times on 2 seperate accounts.
The feedback was "failed to read data", however I havent figured out what this refers to specificly.
I do not use any addons
Edit: One of the characters this has happened to is named Jandara.
Update: the bottom area of Felwood is safe, it does crash somewhere around irontree woods.

What I have tried to fix it:
Delete WTF and Cashe folders.
Restart my computer.

**Comment by Doppelmoral** [comment]
Google the crash number. I ahd something similar which caused a #134 error. After researching it I found data of my client was faulty /corrupted and had to reinstall

**Comment by zeus1s** [comment]
Did you download TBC From feenix official torrent?
