### ISSUE TITLE
High Warlord Naj'entus

### ISSUE THREAD

**Issue by Dorakrab** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3708]
High Warlord Naj'entus doesnt have his Needle Spine ability

Needle spine : 
Does 2,890 to 3,910 physical damage to three random targets in a cone shape and an additional 2,280 to 2,520 frost damage to anyone within six yards of the targets. 

http://wowwiki.wikia.com/wiki/High_Warlord_Naj'entus

With the removal of Black Temple attunement this means that new guilds get free t6 loot

**Comment by repae1f** [comment]
patch 2.1.1 video :/

**Comment by devidao** [comment]
Fixed, coming soon on PTR

**Comment by Dorakrab** [comment]
now Naj'entus is working properly on live

**Comment by Nzzoth** [comment]
We're aware thank you for the comment nontheless, Issue closed. Fix on live as of patch 15.1.
