### ISSUE TITLE
Illidan's Fireball ability

### ISSUE THREAD

**Issue by Dorakrab** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3710]
Right now Illidan uses his fireball ability slower than he should (every 5 seconds) but he should use it every 2 seconds. 

http://wowwiki.wikia.com/wiki/Illidan_Stormrage_%28tactics%29
Fireball: 2 second cast time, deals 3k-4k fire damage in a 10 yards radius. 

Seen here https://youtu.be/k8_JbDiALkY?t=7m28s

This makes phase 2 of the fight too easy

**Comment by repae1f** [comment]
patch 2.1.1 video :/

**Comment by devidao** [comment]
Fixed

**Comment by Nzzoth** [comment]
Live as of patch 14.19
