### ISSUE TITLE
Rogue Tier 6 not benefitting Hemorrhage

### ISSUE THREAD

**Issue by kildrazien** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3711]
Issue: Currently the 4 piece set bonus for Slayer's Armor does not increase the damage dealt by Hemorrhage by 6%.

Steps to reproduce:
Equip 4 pieces of Slayer's armor, make note of Armor pen and AP. Use a weak weapon and hemorrhage about 20 times on the target to get a base estimate of the damage dealt. Then remove one item of the set and add/change gear to get to the same AP/Armor pen values (or close enough). Then use hemorrhage 20 times and compare the first set to the second set.

**Comment by kildrazien** [comment]
The following screenshots show proof that hemorrhage is not receiving benefits from Slayer's Armor 4 piece set bonus.
![wowscrnshot_100215_163227](https://cloud.githubusercontent.com/assets/3773694/10259363/6189b856-6924-11e5-83c1-f92b3755d93c.jpg)\
This screenshot shows a test of damage done by hemorrhage without the set bonus at 1987 ap and 910 arp
![wowscrnshot_100215_164014](https://cloud.githubusercontent.com/assets/3773694/10259361/6188540c-6924-11e5-8033-3fbc65dc3255.jpg)
![wowscrnshot_100215_164020](https://cloud.githubusercontent.com/assets/3773694/10259362/61897706-6924-11e5-8985-b8bf795bfc4f.jpg)
These 2 screenshots show a test of damage done by hemorrhage WITH the set bonus at 1984 ap (the difference of 3 ap being negligible) and 910 armor pen. If this was increased by the set bonus, we would expect to see 459*1.06=487 damage average, but instead we see a 455 damage average.

**Comment by kildrazien** [comment]
Bump, this is really a huge nerf to Hemo raid rogues and NEEDS to be fixed

**Comment by devidao** [comment]
Fixed

**Comment by Nzzoth** [comment]
Fix confirmed on PTR.

**Comment by lajhar** [comment]
On live (15.4)
