### ISSUE TITLE
readme - Welcome to the Feenix 2.4.3 Bugtracker!

### ISSUE THREAD

**Issue by Radschpud** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3716]
"— Additional:

```
We encourage to submit screenshots, as this can help us investigate the reported issue
Any additional information that will help us investigating and solving the issue
Here is a form and sample on how to report a bug
```

"

If I click on Here I get an error message. which sounds nearly like this:

this file is going to be deletet soon. if you need it logg in, make a copy, or request access from the owner.

its not possible to make a copy. the error apears to fast.

**Comment by Involve** [comment]
can confirm bugtracker is bugged
