### ISSUE TITLE
[Shattrath Flask of Mighty Restoration] do not stack with [Redeemer's Alchemist Stone]

### ISSUE THREAD

**Issue by Lederi** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3720]
# Current situation
If you consume a [Shattrath Flask of Mighty Restoration](https://www.wow-one.com/database/index.php?item=32899) while the buff [Alchemist's Stone](https://www.wow-one.com/database/index.php?spell=17619) from [Redeemer's Alchemist Stone](https://www.wow-one.com/database/index.php?item=35750) is active, the buff form the stone disappears. The same applies in reverse.

# How it should be
Both, flask and stone, should stack.

**Comment by Fleischi** [comment]
[Shattrath Flask of Fortification](https://www.wow-one.com/database/index.php?item=32898) has the same problem.

**Comment by devidao** [comment]
Fixed, coming soon on PTR.

**Comment by Nzzoth** [comment]
Live as of patch 14.17, closed.
