### ISSUE TITLE
[Quest] The Second Trial

### ISSUE THREAD

**Issue by celyse** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3723]
Issue is with the quest The Second Trial: http://wow.gamepedia.com/Quest:The_Second_Trial

Once a BE paladin hits level 20 they can pick that quest up from Knight-Lord Bloodvalor in Silvermoon City. It tells you to go talk to Master Kelerun Bloodmourn in Eversong Woods. Once you get to Bloodmourn though, he has no question mark above his head nor any way to interact with him.

Abandoned quest, cleared cache and WTF with no improvement.

**Comment by devidao** [comment]
Could not reproduce this issue, i successfully completed this quest. Maybe there was any special cases?

![untitled](https://cloud.githubusercontent.com/assets/5411643/11864205/547f8928-a4a3-11e5-9310-e40113528454.png)

**Comment by devastator** [comment]
Most probably the issue is in npc_kelerun_bloodmourn script, many scripts cause creature failure after the scipt takes effect the first time, the npc does not restart properly once the script is completed.

**Comment by devidao** [comment]
Fixed. After fail/done quest 'Master Kelerun Bloodmourn' is correclty restarted.

**Comment by Nzzoth** [comment]
Fix denied on PTR.

**Comment by devidao** [comment]
Resolved quest stuck issue

**Comment by Nzzoth** [comment]
Fix confirmed on PTR.

**Comment by Kaiitothewai** [comment]
PLTR test soon?

**Comment by lajhar** [comment]
ON live (15.4)
