### ISSUE TITLE
[Rogue][Remorseless Attacks][Mutilate] Mutilate doesn't trigger Remorseless Attacks effect

### ISSUE THREAD

**Issue by Heeho** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3727]
Description says that Remorseless Attacks give 20% bonus crit chanse to Sinister Strike, Backstab, Mutilate, Hemorrhage, Ambush and Ghostly Strike. I've tested it with Sinister Strike, Backstab and Ambush and it worked, making the buff disappear. However, Mutilate doesn't seem to get 20% critical chanse bonus, nor it removes the buff.

**Comment by devidao** [comment]
Fixed, coming soon on the PTR

**Comment by Nzzoth** [comment]
Fix confirmed on PTR

**Comment by Nzzoth** [comment]
Fix confirmed on PTR.

**Comment by Nzzoth** [comment]
Fix confirmed on PLTR.

**Comment by Kaiitothewai** [comment]
ETA on applying to Live?

**Comment by lajhar** [comment]
On live (15.4)
