### ISSUE TITLE
Windfury

### ISSUE THREAD

**Issue by doffie** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3728]
Hello dear devs,

It seems that our windfury from weapon imbues gives us 1 swing instead of 2 swings per procc.
Here is the formula that you need, hope this helps. 

In full Enhance Build with Elemental Weapons (+40% WF Damage) and Weapon Mastery(+10% Melee Damage)
Put in an AP value that you will have when completely buffed with all procs and totems included.

MainHand Damage :
([Weapon Damage] + [Fully buffed AP]/14 * [Weapon Speed]) * 1.10

MainHand Windfury :
([Weapon Damage]+([Fully buffed AP] + WindfuryAP + [Totem of the Astral Winds AP])/14 * [Weapon Speed]) * 1.10 * 1.40

OffHand Damage :
([Weapon Damage] + [Fully buffed AP]/14 * [Weapon Speed])/2 * 1.10

OffHand Windfury (2.1 patch mechanic) :
(([Weapon Damage]+AP/14*[Weapon Speed])/2+(WindfuryAP + [Totem of the Astral Winds])/14 * [Weapon Speed])) * 1.10 * 1.40

Happy xmas.

**Comment by Delinquent1** [comment]
![](http://i.imgur.com/QPAv21k.jpg?1)

As you can see on my shaman has a static 1939 AP with unleashed rage.
Thanks to Tiffanyt that put some effort on making an awesome spreadsheet we can see how much a windfury should hit as well as the white attacks

![](http://i.imgur.com/90Ejsqz.jpg?1)

So my shaman according to the awesome spreadsheet should hit white attacks from mainhand  579-749 and offhand 289-375.
As you can see on my character sheet it is hiting from 526-682 main hand and 263-341offhand
 
Another interesting thing is the windfury damage.
As you see on my recount you can see in 10 minutes autohit rotation i got 224 windfuries (this number is tragic i will explain later what is wrong with that) which vary from 162-870 damage.
 
Again with that awesome spreadsheet we already mentioned one can clearly see that my hits should had been somewhere between 1458-3639 for main hand windfury and 845-2050 for offhand windfury for any target with 7700 armor like the dummy im hitting.

**Comment by Delinquent1** [comment]
Mind adding a comment here saying you look in it or that you have no clue so we can help you?
