### ISSUE TITLE
Old Hillsbrad Foothills (Last Boss) Bug

### ISSUE THREAD

**Issue by Drenwite** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3736]
in Old Hillsbrad Foothills on Last Boss Thrall wont attack on last boss, tried to re-combating Thrall, didnt work (pulled spiders and humans on him after 10min waiting).

**Comment by devastator** [comment]
https://github.com/FeenixServerProject/Archangel_2.4.3_Bugtracker/issues/2568
