### ISSUE TITLE
Attunement to the Core [Storm]

### ISSUE THREAD

**Issue by roblockster** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3740]
For MC attunement quest Attunement to the Core (7487)

Current situtation: quest item Core Fragment (18412) can only be looted by one person.

Expected situation: Core Fragment should be be able to be looted by whole party, or there should be multiple items like on 1.12 Warsong

**Comment by devastator** [comment]
Fixed. Soon on PTR

**Comment by devastator** [comment]
Applied to Live with Patch 1.2
