### ISSUE TITLE
Important Vanilla Enchants Unavailable Due to Patch Change [Storm]

### ISSUE THREAD

**Issue by roblockster** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3741]
A number of primarily AQ/Cenarion Vanilla enchants were changed in TBC and now have TBC material requirements, and thus are difficult or impossible for Storm players to still acquire (might be the case because many were also be available to learn from TBC reputation vendors).

-Enchant Gloves: Superior Agility (25080)
-Enchant Cloak: Dodge (25086)
-Enchant Cloak: Subtlety (25084)
-Enchant Cloak: Stealth (25083)

Other enchants are potentially possible to get by DEing extremely high level items:
-Enchant Cloak: Greater Fire Resistance (20732)
-Enchant Cloak: Greater Nature Resistance (20733)

**Comment by devastator** [comment]
Fixed. Soon on PTR

**Comment by devastator** [comment]
Cannot be fixed properly due to client side limitations
