### ISSUE TITLE
[Warsong 2.0] Hunter Talents and Pet talents

### ISSUE THREAD

**Issue by kove400** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3742]
The talent Spirit bond does not work at all, both ranks are broken giving no bonus healing per 10 secs.

As well the talents for pets; under beast training called Great Stamina does not work at all, in fact it negates the health instead of adding it.  I tested this and my pets stamina dropped +17 instead of going up.   :(

**Comment by Applescruffs** [comment]
Spirit bond does work.

![wowscrnshot_011516_182400](https://cloud.githubusercontent.com/assets/16367408/12368026/544f5518-bbb5-11e5-9c71-cb8179c1a2e2.jpg)

You can clearly see the healing done to my pet on my combat text.

**Comment by kove400** [comment]
I don't see any combat text heals, if you referring to the log.  I have had my pet get spirit bond 1/20 times I am online, assuming it is working at that moment anyways.  And as well this is level 60 vanilla patch I am speaking of, not the 70.

**Comment by Thorik** [comment]
I am having the same issue with my hunter where spirit bond isn't showing up on either my pet or myself. One thing I noticed with it is when I took the talent it showed up on my pet. However, the moment I dismissed my pet and recalled him the buff wasn't there anymore.

**Comment by lajhar** [comment]
Obsolete
