### ISSUE TITLE
[Item] Crystal Spire of Karabor - Proc bugged (receives bonus healing benefit)

### ISSUE THREAD

**Issue by davidbowieqt** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3746]
OVERVIEW
As stated in the title, the mace that drops of Illidan [Crystal Spire of Karabor] is bugged. The proc rate is supposed to heal for 180-220 additional healing when the target is below 50% health. The bug is that this little bonus/proc receives benefit from spell power, so it generally heals for about 800-1000, in addition to the actual heal being cast.

This is not blizz-like, and is being abused in arena by the few people that have it, namely holy paladins and resto shamans (because of the nature of their healing spells).

CURRENT SITUATION
The proc of +180-220 healing (when your target is below 50% health) receives benefit from bonus healing, causing it to heal for 800-1000 when used by a full-geared player.

DESIRED SITUATION
The proc of +180-220 healing (when your target is below 50% health) should only heal for +180-220, and should not receive benefit from spell power.

EVIDENCE
http://forums.elitistjerks.com/forums/topic/14933-item-crystal-spire-of-karabor-effect/
http://www.wowhead.com/item=32500/crystal-spire-of-karabor#comments

**Comment by devastator** [comment]
https://github.com/FeenixServerProject/Archangel_2.4.3_Bugtracker/issues/3718
