### ISSUE TITLE
[Warlock][Warsong 2.0] Soul link does not work

### ISSUE THREAD

**Issue by NormantasKudzma** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3749]
What: Spell soul link from demonology talents http://db.hellground.net/?spell=19028 (ID 19028)
What does not work: After casting soul link, neither the pet, neither the caster gets the Soul link buff.
How it should work: After casting the soul link, pet and caster should get a soul link buff.

Additional links:
http://wowwiki.wikia.com/wiki/Soul_Link

**Comment by lajhar** [comment]
Obsolete, works as intended
