### ISSUE TITLE
[Warlock][Warsong 2.0] Talent Demonic Knowledge

### ISSUE THREAD

**Issue by NormantasKudzma** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3750]
What: Talent Demonic Knowledge from demonology tree (https://www.wow-one.com/database/index.php?spell=35693) (ID 35693)
What does not work: The pet's owner does not get the buff when the pet is active.
How it should work: The owner should get a buff which increases pet owner's spell damage by 4/8/12% of the total of active demon's Stamina plus Intellect (as long as pet is alive).

Additional links:
Rank1 of talent: https://www.wow-one.com/database/index.php?spell=35691
Rank2 of talent: https://www.wow-one.com/database/index.php?spell=35692
http://wowwiki.wikia.com/wiki/Demonic_Knowledge

**Comment by lajhar** [comment]
Obsolete, works as intended
