### ISSUE TITLE
[Warlock][Warsong 2.0] Master demonologist

### ISSUE THREAD

**Issue by NormantasKudzma** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3751]
What: Talent Master demonologist from demonology tree (https://www.wow-one.com/database/index.php?spell=23825) (IDs 23825, 23824, 23823, 23822, 23785)
What does not work: Buff is not applied neither to the pet, neither to the owner.
How it should work: Pet's owner and the pet should receive a buff as long as the pet is active. Buff depends on the type of the demon.

**Comment by lajhar** [comment]
Obsolete, works as intended
