### ISSUE TITLE
[Item]  [IoQD Progression] Shattrath Flasks introduced with IoQD not available to players

### ISSUE THREAD

**Issue by Warlockbugs** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3752]
## Current situation:
The server has IoQD released, yet [Shattrath Flask of Pure Death](http://www.wow-one.com/database/index.php?item=35716) and [Shattrath Flask of Blinding Light](http://www.wow-one.com/database/index.php?item=35717) are not available for purchase.

## What is expected:
[Scryer](http://www.wow-one.com/database/index.php?npc=23483) and [Aldor](http://www.wow-one.com/database/index.php?npc=23484) Apothecaries should offer these flasks in exchange for Illidari Marks matching the 2.4.0 progression stage.

## Sources:
http://wowwiki.wikia.com/wiki/Shattrath_Flask_of_Pure_Death
http://wowwiki.wikia.com/wiki/Shattrath_Flask_of_Blinding_Light

**Comment by devastator** [comment]
Fixed. Soon on PTR

**Comment by anaaz** [comment]
Fix applied to Live with Patch 15.2
