### ISSUE TITLE
General Problem with Spell damage in Mobs and Npcs

### ISSUE THREAD

**Issue by Darksax** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3754]
Report ID:3754

Reporter Name: DARKSAX

Date/Time:  04:40 AM 27-01-2016

Error Severity: MEDIUM

Zone/Instance: OUTLAND

What type of error occurred?: INCORRECT SETTING OF VALUES IN SPELL DAMAGE FROM SOMES NPCS/MOBS TABS 

What was the actual result vs. the expected result?: 

NPCS LIKE ABYSSAL FLAMEWALKER ; WARP-RAIDER NESAAD and others should be hitting significantly less than their are doing. i've been playing in retail since aproximate 2008 and know very well theses mobs; plus wowhead and comments sections on it; shows that their should be doing lot less damage than what are they doing.
Both examples displayed can be easily corroborated; The IMMOLATION aura that abyssal flamewalker has; should be hitting around 250-350 dmg; in contrast to the 1700 - 3000 dmg now it's doing.
Same with Warp-raider Nesaad; his Energy Flux spell hits normally between the range of 383-400 on levels 70 with no arcane resistance; but here, he hits for around 2000 - 3000 dmg; which is a big difference.

To make this clear; this is not an isolated issue; these are just examples; there are plenty of MOBS and NPCS that have the same problem; which is very frustrating at the time of farming or doing quests. im going to keep trying to upload and recopilate every single mob/npc with problems;

ATTACHED COMES THE SS OF THE INFERNAL AURA DAMAGE.

Can the error be repeated? If so, what are the steps?:
The error is easily repeatable by engaging in combat with any of these mobs, or others. 

External/Related Links:
WARP-RAIDER NESAAD (http://www.wowhead.com/npc=19641/warp-raider-nesaad#comments)
ABBYSAL FLAMEWALKER (http://www.wowhead.com/npc=25001/abyssal-flamewalker)
IMMOLATION (http://www.wowhead.com/spell=12743/immolation)
ENERGY FLUX (http://www.wowhead.com/spell=35924/energy-flux)

Please detail your character’s race, class, and items (optional):

Darksax
Human
Warrior
Level 70
![wowscrnshot_012716_003543](https://cloud.githubusercontent.com/assets/16911129/12603336/83597b5c-c490-11e5-986c-8c0c49520716.jpg)

**Comment by devastator** [comment]
It is isolated issue based on the spell that the mobs are using. A fix for Abyssal Flamewalker is applied to PTR. If there is an issue with a certain mob please open a separate report
