### ISSUE TITLE
#[Shattrath Flask of Relentless Assault] do not stack with [Fel Mana Potion]

### ISSUE THREAD

**Issue by unfaithful** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3755]
# Current situation
If u consume a [Fel Mana Potion](https://www.wow-one.com/database/?item=31677) wich gives u the buff [Fel Mana](https://www.wow-one.com/database/?spell=38929)  while the buff [Relentless Assault of Shattrath](https://www.wow-one.com/database/?spell=41608) from [Shattrath Flask of Relentless Assault](https://www.wow-one.com/database/?item=32901) is active, the buff from the flask dissappears.
# How it should be
Both, flask and debuff, should stack.

**Comment by devidao** [comment]
Fixed, coming soon on PTR

**Comment by Nzzoth** [comment]
Fix confirmed on PTR.

**Comment by Nzzoth** [comment]
Fix confirmed on PLTR.

**Comment by Nzzoth** [comment]
Live as of patch 15.
