### ISSUE TITLE
[Thorns] and [Fire Shield] and [Crystal Spire] stack

### ISSUE THREAD

**Issue by Lederi** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3757]
# How it is

The damage shields [Thorns](https://www.wow-one.com/database/index.php?spell=26992) and [Fire Shield](https://www.wow-one.com/database/index.php?spell=27489) and [Crystal Spire](https://www.wow-one.com/database/index.php?item=11567) stack.
# How it should be

This damage shields should not stack.
# Proof

[wow wiki: Crystal Spire](http://wowwiki.wikia.com/wiki/Damage_shield#Enhancements)

> ...  (Cystal Spire does not stack with spells providing damage shields) ...

[wow wiki: Fire Shield](http://wowwiki.wikia.com/wiki/Fire_Shield?oldid=1466622)

> Does not stack with Thorns.

**Comment by devidao** [comment]
Fixed, coming soon on PTR.

**Comment by Nzzoth** [comment]
Fix confirmed on PTR.

**Comment by lajhar** [comment]
On live (15.3)
