### ISSUE TITLE
Archimonde Airburst radius 

### ISSUE THREAD

**Issue by Nifire** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3762]
Hi,

Air burst radius on Archimonde is not 13 yards, closer 20 yards.
https://www.wow-one.com/database/index.php?spell=32014

http://www.wowhead.com/npc=17968/archimonde#comments
"By RiceCake (3,862 – 15·24)  on 2008/03/02 (Patch 2.3.3)
Air Burst: He randomly targets a person and casts this on him/her. The person, as well as everyone within 13 yards of him"

Use DBM "/distance 13" to test

**Comment by devastator** [comment]
Tested. Works properly, the radius set in the database is also correct
