### ISSUE TITLE
[Shaman][Talent] Improved Weapon totems

### ISSUE THREAD

**Issue by kildrazien** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3764]
Currently the shaman talent Improved weapon totems (https://www.wow-one.com/database/index.php?spell=29193 and 29192) do not grant any bonuses to the effect of the windfury attack. According to the Windfury Attack information (https://www.wow-one.com/database/index.php?spell=25584), it grants a buff that increases attack power by 445 for 1.5s (or until the extra attack is made). This is visible in the character sheet, as evidenced by the following:

This is before the AP bonus from WF:
![wowscrnshot_021416_215231](https://cloud.githubusercontent.com/assets/3773694/13040435/40f62d5e-d369-11e5-9c0a-87fac8a0bfea.jpg)

This is after the AP bonus:
![wowscrnshot_021416_215232](https://cloud.githubusercontent.com/assets/3773694/13040439/4d7a1ef0-d369-11e5-8e70-352eb479f9b4.jpg)

The difference is 2845-2307=538, which is exactly 445_1.1(deadliness talent)_1.1(unleashed rage). This shows that the base number for Windfury totem, 445, is not being increased by the 30% that it should be.

**Comment by devidao** [comment]
I have just tested on Archangel PTR and it is working good

**Comment by kildrazien** [comment]
PTR might be correct, but whatever code was worked on for the PTR has not been migrated to the actual server

**Comment by lajhar** [comment]
Works as intended.
You are a Rogue, you should not benefit from this talent, only the shaman gains +30% AP till the next WF hit. If you disagree, please provide any evidence. /close
