### ISSUE TITLE
[Quest][OOX-09/HL Distress Beacon] no chance to drop

### ISSUE THREAD

**Issue by unfaithful** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3765]
# Current situation

All the Mobs in the Hinterlands wich should drop [OOX-09/HL Distress Beacon9](https://www.wow-one.com/database/?item=8704#dropped-by) are listed with a 100% dropchance, but infact it is a 0% dropchance. Killed and looted enough mobs to have a sure drop.
# How it should be

The Mobs should have dropchances of 0,9% - 0,16% to drop [OOX-09/HL Distress Beacon9](https://www.wow-one.com/database/?item=8704#dropped-by).
- Here is the [Link](http://www.wowhead.com/item=8704/oox-09-hl-distress-beacon) to WoWHead with correct dropchances.
- Here is the [Link](http://wowwiki.wikia.com/wiki/Mechanical_Chicken) to WoWWiki where it is explained.
- This Item starts [Find OOX-09/HL!](https://www.wow-one.com/database/?quest=485) wich is one of the Prequests for [An OOX of Your Own](https://www.wow-one.com/database/?quest=3721) and this Quest rewards you with [Mechanical Chicken](https://www.wow-one.com/database/?item=10398).

**Comment by devastator** [comment]
Fixed. Soon on PTR

**Comment by lajhar** [comment]
On live (15.8)
