### ISSUE TITLE
Final Lifebloom tick dont crit

### ISSUE THREAD

**Issue by tokash1337** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3766]
Hi there,

**Current situation:**
The last tick from Lifebloom never crits.

**How it should be:**
The last tick of Lifebloom can be critical.
It doesnt matter if the hot runs out or if its getting purged/dispelled. The last tick should be able to crit.

**Here is a video of the current Situation on Archangel:
https://sendvid.com/s9f6di5m

**WoW-Wiki 1**
http://wowwiki.wikia.com/wiki/Lifebloom
read "Notes" section.

**WoW-Wiki 2**
http://vanilla-wow.wikia.com/wiki/Lifebloom

There was a post about this Topic a few years ago. But it was closed without any comment from the development team.

thank you for taking care and kind regards,

Tokash

**Comment by devidao** [comment]
Fixed, coming soon on PTR

**Comment by Nzzoth** [comment]
Note: It has a crit chance but it doesn't scale with gear.

**Comment by tokash1337** [comment]
You guys need more evidence or informations? The last update is more than 3 months ago and devidao fixed it already?

Please give us an update about this fix because especially in arena this bug is gamebreaking.

kind regards,

Tokash

**Comment by lajhar** [comment]
On live (15.3)
