### ISSUE TITLE
[Shaman][Windfury Weapon] not working properly - half dmg and a little less chance of proc

### ISSUE THREAD

**Issue by Urshark** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3767]
Hi there,

many players (enha shamans) have problem with realy low dmg of Windfury.
here is the relevant link to see how it should work -
http://vanilla-wow.wikia.com/wiki/Windfury_Weapon  
(one difference - windfury should cost no 7% of mana, but 178 mana). Read tips and read notes.

**Current situation:**
1) Windfury doesn´t make additional damage equal to two extra attacks **with X extra attack power**. The situation now is it makes a ca. half dmg.
http://s29.postimg.org/jrwd9q2mf/Wo_WScrn_Shot_011916_171400.jpg
http://s29.postimg.org/6qox8gzbb/Wo_WScrn_Shot_011916_171613.jpg
Windfury attacks are lower then normal melee hit dmg. They absolutely ignore bonus attack power (475 bonus AP).

2) The proc chance is ca. **18-19%.** 
http://s12.postimg.org/6b2o0hb0t/Wo_WScrn_Shot_021516_140743.jpg
178:2= 89 Windfury procs (Recount addon counts 1 Windfury as 2 attacks)
477 is the count of normal melee hits.
So 477:100= 4,77
89:4,77= 18,658%

3) Windfury doesn´t offer **up to 40%** damage increase to a shaman's base melee DPS (if wielding a single three second or slower weapon). It makes half dmg.
http://s24.postimg.org/gx2ufybsl/Image00001.jpg
On the second screeshot you can see how low is the dmg of Windfury (my shocks made bigger dmg). Here I tried the classic pve rotation with one-hands, popped trinkets on CD, shocks on CD, stormstrikes on CD. Windfury is realy low.
http://s18.postimg.org/6v4sip56h/Image00002.jpg

**How it should be:**
See the link -
http://vanilla-wow.wikia.com/wiki/Windfury_Weapon

1) Each hit has a 20% chance of dealing additional damage equal to two extra attacks **with X extra attack power**. Lasts 30 minutes. In TBC is it 475 extra attack power (Windfury rank5). 

2) The proc chance should **be 20%**. Not 19%,18% or lower.

3) Windfury is the main enhancement shaman buff. It offers **up to 40%** damage increase to a shaman's base melee DPS (if wielding a single three second or slower weapon), not counting the attack power bonus granted on 2/7ths of all swings. 

In Pre-TBC, a lucky shaman was able to one-shot Clothies with slow two-handed weapon if Windfury proc'd.

It is 2 months now without any response, any answer and many players are frustrated because of it.
Please take a look on it.

Sorry for my complicated english :)
Thank you for taking care.

best regards,

Urshark.

**Comment by kildrazien** [comment]
You had a couple of missed/dodged attacks. Those cannot be counted in the calculations as a miss cannot proc a windfury attack. The real frequency is 89/448, which is 19.86%, or really damn close to the proposed procrate of 20%. 
As for the damage, yes, it is pitiful. The damage of regular swings average out to be roughly 389/swing. The damage of windfuries average out to be 280 damage/swing, which should be absolutely impossible if windfury was working properly.

**Comment by Applescruffs** [comment]
#3730

**Comment by Urshark** [comment]
Kildrazien, I know, I was not decided if I want to put the "proc chance" here or not. The proc chance is ca. OK, I put it here because if devs will work on WF they could take a look on whole WF.

**Comment by Urshark** [comment]
Hi, still the same. Could u tell us approximated time you need to fix it? Did u start with working on it yet or not?

Thank you.

Reason why I am asking is - I will move from my birth town soon and I will not have time for playin wow anymore and I want to know if I should waiting on fix or should I give it up. 

Thank you for your answer.

Bye.

**Comment by Brutalelite** [comment]
Any news on this issue ?? Enh shamans are useless now apart from popping down some totems.

**Comment by Urshark** [comment]
Guys, srsly it will be 3 months now (1/4 of the year). Still no answer, no response.

**Comment by Urshark** [comment]
Hi,
nothing new?
So let me tell you one BIG THANK for your "amazing" patch 14.15.1 and 14.15.2, which killed enhas...
http://www.wow-one.com/forum/topic/96852-project-archangel-243-patch-14/page-2

Thanks.

**Comment by Brutalelite** [comment]
Any news on this ? Because it wasn't "fixed" in december, it was simply rigged to do less damage and not to reflect how its supposed to work at all.

**Comment by Brutalelite** [comment]
Bump
