### ISSUE TITLE
Stealth ability sharing GCD (bug)

### ISSUE THREAD

**Issue by TOSMANOTA** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3770]
Reporter Name: Macgiver

Date/Time: 24 feb 2016 11:19 am

Zone/Instance: always it’s a bug spell

What type of error occurred?:  

Stealth ability (as well as Druid's Prowl) can't be casted during a GCD.
 i did video on this link : 

https://youtu.be/PKzNTNBfT1o

Reproduction guide:
Make a rogue
1. gm off
2. Gm visible on
3. learn 1787 and 31224
4. keybind to 1 shadow cap , keybind stealth to 2, and shadow cap in 3
5. cast shadow cap (31224)  spam they hotkey for stealth (you can't stealth)
6. Use stealth and keybind any spell (distract ID: 1725 or shadow cap : 31224 ) to 1
7. Use stealth and instantly cast distract (you will be able to while on gcd)

Druid:
1. Gm off
2. GM visible on
3. Learn all_myspells 
4. Enter cat form and keybind prowl to 1
4. reenter catform and spam prowl really fast notice how you wont be able to stealth until GCD is over.

Stealth and prowl are not supposed to share GCD it’s a Bug class or spell , it’s like shadow cap, and in this video i show that shadow cap do the same thgs

**Comment by teddys** [comment]
already reported
#3424

**Comment by Nzzoth** [comment]
That being said issue closed.
