### ISSUE TITLE
[Quest] [The Scryer's Scryer]

### ISSUE THREAD

**Issue by Sargs** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3772]
[The Scryer's Scryer](http://www.wowhead.com/quest=11490/the-scryers-scryer) does not work. When you activate Scrying Orb it just shows a movie and nothing happens, did it in normal.

**Comment by devidao** [comment]
it is already fixed - https://github.com/FeenixServerProject/Archangel_2.4.3_Bugtracker/issues/3654

**Comment by Nzzoth** [comment]
Duplicate and closed.
