### ISSUE TITLE
[Warlock][Mount] Dreadsteed Chain, Imp Delivery

### ISSUE THREAD

**Issue by katiosha** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3779]
I worked my way up to "Imp Delivery" Quest, its not appearing to me, i have handed in "Xorothian Stardust" already.

cleared cache, wtf, nothing changed.

![wowscrnshot_031816_185116](https://cloud.githubusercontent.com/assets/17931235/13883283/cc04ba66-ed39-11e5-9fcd-88189dfaf4e7.jpg)

**Comment by devastator** [comment]
The Quest Imp Delivery requires you to complete the both pre-quest chain lines, so you should also complete Mor'zul Bloodbringer > Rage of Blood > Wildeyes quests in order for Imp Delivery to be available
