### ISSUE TITLE
Healing Shaman Tier 6 4 piece does not work (Rehashed, more casts)

### ISSUE THREAD

**Issue by blackhodown** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3782]
[Here is a new album](http://imgur.com/a/8xVjW)

120 casts. It CLEARLY does not work. You can not explain this away by saying "random chance could do it".

In 120 casts of rank 1 chain heal, there is barely any difference at all between the two, when each cast in reality should be doing ONE HUNDRED more healing. I assume there is a difference between whatever test realm you use and what is live. To help you, I also tried this while untalented and there was still no effect of the t6.

**Comment by blackhodown** [comment]
I'm not just like, posting this for a laugh. There is a reason why no raiding shamans use 4 piece t6. It is frustrating not being able to use the gear you should be using because the server doesn't work correctly.

**Comment by Nzzoth** [comment]
Alright, I'll give you the benefit of doubt. I will retest it tomorrow on our PLTR (exactly the same as live minus the people) and will post results. To be clear unless you're doing it the way I did it. To get min and max values the minimum amount of samples is 10000 (not joking).

**Comment by devastator** [comment]
Issue confirmed and fixed. Soon on PTR

**Comment by lajhar** [comment]
Fix confirmed on PTR.
