### ISSUE TITLE
Windfury totem and warriors

### ISSUE THREAD

**Issue by twinkedup** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3789]
Windfury totem doesn't proc from Heroic Strike and Cleave.

**Comment by Dorakrab** [comment]
it does, just checked

**Comment by Nzzoth** [comment]
As far as I'm aware a fix to enable WF procs from heroic strike and cleave is live. However I can always be wrong, but please do present evidence to back up your claims (preferably more than 5 hits). Closed until proven otherwise.
