### ISSUE TITLE
All characters on my profile weapon skills woulnt level up

### ISSUE THREAD

**Issue by TrilPhil** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3798]
TrillPhil
4/18/16
Warsong 2.4.3 server
This is making some of my characters unplayable

My Characters from Feenix ,ED, and the Instant 60 server were transfered to the new Warsong 2.4.3 server but their weapon skills cannot be leveled up. I've tried changing weapon types and weapons multiple times, fighting all different level mobs, and buying a new weapon skill and trying to level it but nothing will work. other skills such as defense level normally from combat. 

Characters: Danklin, Therealgimli, Deadkids, Grumala, Undaro. Undaro is lvl 60 but his weapon skills are still 1 as he was from the instant 60 server, so is now unplayable.

I have tried everything to fix this aside from reinstalling the client, also have not found another source with this bug so it is very frustrating.

**Comment by Nzzoth** [comment]
Hello Trilphil, please make an ingame ticket and a GM will assist you.
