### ISSUE TITLE
[Mage][Item] Serpent-Coil Braid Mana Surge effect and Tirisfal Regalia 4 piece bonus(Arcane Madness) overwrite each other

### ISSUE THREAD

**Issue by corcaroli** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3803]
That's an old issue, but it's still unresolved. (#2693)
Upon using mana gem, the Mana Surge effect replaces Arcane Madness (if it's active), and vice versa, if the Mana Surge effect is active, then upon activation Arcane Madness effect replaces it.
These two effects should be independent from each other.
Here's a video proof:
https://sendvid.com/b7ybwnat

**Comment by devastator** [comment]
Dont create duplicate issues, fix for this is created and confirmed on PTR
