### ISSUE TITLE
Shutting Down Manaforge Duro

### ISSUE THREAD

**Issue by Tranken** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3806]
When you have killed Overseer Athanel and obtained the crystal you can't click the machine, like you have done on the previous quests that works the same way... its like the machine dosent exist, its not clickable to start the shutdown process

**Comment by devastator** [comment]
https://github.com/FeenixServerProject/Archangel_2.4.3_Bugtracker/issues/593
