### ISSUE TITLE
Archangel quest bugg

### ISSUE THREAD

**Issue by maginaw** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3807]
The quest "The foot of the Citadel" [http://www.wowhead.com/quest=10876/the-foot-of-the-citadel](url) 
can not be completed. 

This is because [Challange from the Hord], [http://www.wowhead.com/item=31702/challenge-from-the-horde](url), can not be used on Force-Commander Gorax's, [http://www.wowhead.com/npc=19264/force-commander-gorax](url), corpse.

So because of this error Hand of Kargath, [http://www.wowhead.com/npc=22374/hand-of-kargath](url) wont spawn. So you cant kill him and loot The Head of The Hand of Kargath, [http://www.wowhead.com/item=31706/the-head-of-the-hand-of-kargath](url).

Report ID: 
Reporter name: Maginaw
Date: 2016-05-22, this have been bugged for a while, asked ppl in world chat.
Error sensitivity: 
Zone: Hellfire Peninsula
What type of error occurred? Quest/ quest item dosent work as it should.
Can this error be repeated? Yes, for everyone that tries to do the quest. 
Character: Smnx, level 60, forsaken, rogue, [http://realmplayers.com/CharacterViewer.aspx?realm=ArA&player=Smnx](url)

**Comment by devidao** [comment]
Fixed, coming soon on PTR.

**Comment by maginaw** [comment]
Nice, thanks!
When will this fix be applied to "live"?

**Comment by devidao** [comment]
I guess together with next patch

**Comment by lajhar** [comment]
Fix confirmed on PTR.

**Comment by lajhar** [comment]
Fix confirmed on PreLive

**Comment by lajhar** [comment]
On live as 15.9
