### ISSUE TITLE
Look to the Stars quest Bug

### ISSUE THREAD

**Issue by Paraffine** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3808]
The Look to the Stars quest in Duskwood is not working because the Insane Ghoul NPC that should drop the Mary's Looking Glass item needed to complete the quest does not spawn.

http://www.wow-one.com/database/?quest=177 here's the quest link

**Comment by devastator** [comment]
Checked. The ghoul does spawn.

**Comment by Paraffine** [comment]
He was roaming around outside, confusing himself with the skeletal warrior the 4th time I checked and have a pretty long spawn time.
Sorry for wrong report
