### ISSUE TITLE
Kill Command

### ISSUE THREAD

**Issue by Ionex994** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3824]
Since of

Project Archangel 2.4.3 - Patch 15.2

 Kill Command does procs only on melee attacks.

**Comment by kauski** [comment]
maybe they want us to go melee hunter!

**Comment by Ionex994** [comment]
I sure hope not ^^

**Comment by Ionex994** [comment]
bump

**Comment by Ionex994** [comment]
bump

**Comment by nadramiaz** [comment]
Bump, quite a crucial bug

**Comment by Ionex994** [comment]
Bump, i know that developers are very busy and you have done an ultra awesome jobs in fixing things and making this server what it is today, but pls make hunters great again :)

**Comment by Daweedian** [comment]
Bump! Give us back our BM hunters!
