### ISSUE TITLE
The Sleeper has Awakened

### ISSUE THREAD

**Issue by Paraffine** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3829]
Taking the quest The Sleeper has Awakened from Kerlonian Evershade in Darkshore (I don't know if that's caused by the quest itself or the horn taken from the box near him required for the quest) makes the game freeze forever.

Even closing the game and relogging doensn't fix that because once you log back in after a few seconds it freeze again.

**Comment by lajhar** [comment]
Succesfully picked up the quest, the quest item, and completed the quest on PTR and on live.
