### ISSUE TITLE
[Priest] Empowered Healing's binding heal boost dosnt work.

### ISSUE THREAD

**Issue by s153047** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3832]
## What type of error occurred?:

Holy Priest Talent, Empowered Healing's binding heal 10% boost dosn't work. GH and Flash part works fine.
## What was the actual result vs. the expected result?:

I did the math;
### Formula:

('base healing' + 'HSE' \* 'Cast_time_coefficient' + 'Empowered Healing' \* 'HSE') \* 'Spiritual healing talent'
### Actual:

(1190 + 2466 \* 1.5 / 3.5)*1.1 = 2435 (+/- 163 range)
### Expected:

(1190 + 2466 \* 1.5 / 3.5 + 0.12466)1.1 = 2697 (+/- 163 range)

The 2471 is the one that matches with ingame testing. [Picture](http://i.imgur.com/VLWN9Wy.png)

**Comment by lajhar** [comment]
Issue confirmed.

The talent [Empowered Healing (33162)](http://db.hellground.net/?spell=33162) has no effect for [Binding Heal (32546)](http://db.hellground.net/?spell=32546).

Test: [Prntscr link](http://image.prntscr.com/image/935782816d7b4e09860157bdff75f743.png)

**Comment by devidao** [comment]
Fixed, coming soon on PTR.

**Comment by lajhar** [comment]
Fix confirmed on PTR.

**Comment by lajhar** [comment]
Fix confirmed on PreLive

**Comment by lajhar** [comment]
On live as 15.9
