### ISSUE TITLE
[Item] Aldor version of Shattered Sun Pendant of Restoration

### ISSUE THREAD

**Issue by s153047** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3833]
## What type of error occurred?:

Wrong internal CD on [Shattered Sun Pendant of Restoration](http://www.wow-one.com/database/index.php?item=34677) (Aldor version)
### Expected:

> - The Aldor proc rate is roughly 4% (tested empirically over several hundred attempts).
> - The Aldor effect does not stack; if it procs while a previous buff is still active, the buff refreshes back to 10 seconds.
> - The Aldor effect does not have an internal 'once per unit of time' cap. Procs have been observed while a previous proc was still in effect.
### Actual:

The Aldor version of the proc has a 35-40s internal cooldown.
### Source:

[WoW Wiki link](http://wowwiki.wikia.com/wiki/Shattered_Sun_Pendant_of_Restoration)

As for the Scryer version I have not been able to test it.

**Comment by lajhar** [comment]
Issue confirmed.

The item [(Shattered Sun Pendant of Restoration)](http://www.wowhead.com/item=34677/shattered-sun-pendant-of-restoration) wrongly has a 45 sec cooldown on the Aldor [effect](http://www.wowhead.com/spell=45484/sunwell-exalted-healer-neck).

**Reproduction guide:**

- Create a priest
- .gm off
- .mod rep 932 exalted
- .mod rep 1077 exalted
- .add 34677
- Equip the neck
- .mod mana 100000
- .cast 45813
- Cast Lesser heal rank1s
- Observe you can't trigger the effect twice in 45 sec.

The Scryers effect works properly.

**Comment by devidao** [comment]
Fixed, coming soon on PTR.

**Comment by lajhar** [comment]
Fix confirmed on PTR

**Comment by lajhar** [comment]
On live (15.6)
