### ISSUE TITLE
Error #132 When i log in on my char. on Archangel

### ISSUE THREAD

**Issue by Myladykell** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3835]
Dear,

I have been playing today without problem. I took a break to eat and logged off. When i try to log in on my Char Mladykell on Archangel i get an error. I can log in on another char on Archangel and i can make new ones. I can also log in on Storm without any problem. 
I cannot log in on that specific Character even on another computer or on Windows.

![schermafbeelding 2016-07-28 om 23 25 08](https://cloud.githubusercontent.com/assets/20712464/17230428/7b5602c8-551c-11e6-823e-7172f48d603d.png)
![schermafbeelding 2016-07-28 om 23 30 03](https://cloud.githubusercontent.com/assets/20712464/17230432/7d3734ea-551c-11e6-9b8e-5488fb66f77b.png)

**Comment by lajhar** [comment]
Where did you logged off?
Did you try unstuck your character on the website?

**Comment by Myladykell** [comment]
I logged of in Silithus just next to the guy that allows you to fly. 
No i did not try unstuck since the application blocks as soon as i log in on that character. I don't see myself and cannot puch any button. So i get an error as soon a i try to log in on that character, i get an error and the app closes as soon as i click ok on the error.

**Comment by Myladykell** [comment]
Issue is somehow Solved. Thanks!
