### ISSUE TITLE
[Warlock] [Pet] Succubus won't follow after a dismount

### ISSUE THREAD

**Issue by orgasmix** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3839]
When mounting and dismounting off a **flying** mount, a succubus on "Follow" mode will stay in place instead. Note that you actually have to fly for the bug to reproduce. If you drive your flying mount on the ground only, then the succubus will follow as intended.

The Warlock may hit Stay, or even command his succubus to Attack a target and then hit Follow again, and that Follow will still act like a Stay.

The succubus has to actually **enter combat** and participate (which is different from briefly going towards a target without aggroing it) and it will follow again... till the next time the Warlock flies up.

In addition, Seduction doesn't work on humanoids (PvE).

**Comment by lajhar** [comment]
Couldn't reproduce it.
On PTR/PTRL it is working as intended, the Succubus followed me everytime I mounted up and dismounted after flying around.
Can you provide us additional informations about the issue?
What kind of mount did you use?
Did you try with different mounts or just with one?
What distance shoud the warlock travel on flying mount to trigger the issue?
A video proof maybe?
