### ISSUE TITLE
Infernal's in Hesingwary's Expedition

### ISSUE THREAD

**Issue by TheRealHoboo** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3842]
Pretty sure that there shouldn't be 4 Infernal's chilling in that camp. Also not sure if these warlocks nearby have something to do with it?

![](https://i.gyazo.com/eb778c167d77b119efda2206aa2cbed3.jpg)

![](https://i.gyazo.com/fb6d3a9b0114db3a0d5a2558dee75e4d.jpg)

**Comment by lajhar** [comment]
Probably all the warlocks used Inferno ability.

**Comment by TheRealHoboo** [comment]
If this isn't abusing that ability then i don't know what is.
