### ISSUE TITLE
Demonology Warlock Felguard has no spell tab

### ISSUE THREAD

**Issue by smashbug** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3847]
While leveling up I switched my talents from Destruction to Demonology to get the Felguard summon-able pet. But after buying the spells for the Felguard I noticed that there is no tab in the "Spellbook & Abilities" for its spells. So i cleared my cache and "WTF" folder also uninstalling my addons and to no avail the problem still persisted.  
           Was wondering if this is my own problem or a sever-wide issue that needed to be addressed?

**Comment by lajhar** [comment]
I spent several hours on PTR trying to reproduce it, but I couldn't.
However, there was a similar report before #2265
If you'd provide me your ingame **character name** (strictly no other informations) I could catch you for an ingame conversation to find it out.

**Comment by smashbug** [comment]
Whitewarcow is my in-game name.

**Comment by Nzzoth** [comment]
@lajhar such cases are player sided issues. On a 3+ year running server nobody noticed this so far?

@smashbug Please check all your addons and turn them off, in case the pet bar reappears find the addon causing it.

Issue closed until I get evidence to prove this to be an issue.
