### ISSUE TITLE
[Quest][BEM] Showdown (A)

### ISSUE THREAD

**Issue by DonTooTall** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3848]
First of all, I'll admit that this post will be a shameless copy-paste, but the details in the bug report filed on February 8th, 2013 are the same.
You get to the last part of the chain, "Showdown" and proceed to find Goc's altar, with Goc wandering about, being all friendly-like (/insult didn't make him hostile!) and Sabellian just standing there, doing, well, nothing.

Copy paste part: 
"Issue Confirmed.
NPC Goc (ID: 20555) should be made hostile.
Another issue is that at the moment Goc and Sabellian (lvl 71 elite dragonkin) ID: 22496 are constantly spawned in the area.
Using the quest item Sableman's Signet ID: 31808 at the altar should summon Baron Sablemane http://www.wowhead.com/npc=22103 and Goc. Baron Sablemane should attack Goc. When Goc is at 15% Baron Sablemane should transform to his Dragonkin form and turn into Sabellian.

The event goes with the following dialogue:

At summon:
Goc yells: Who dares rouse Goc from his restful slumber? 
Baron Sablemane yells: It's only right that you know the name of the one who will take your life. 
Baron Sablemane yells: Baron Sablemane. It will be on your lips as you gasp you dying breath. 
Goc yells: Your name is as insignificant to me as the names of the thousands who have died under the might of Goc. I will crush you and ! 
Baron Sablemane yells: Let us begin. 
Fight starts

Once Goc is down to 15% health:
Baron Sablemane yells: Your father destroyed my children and left their bodies impaled upon the rocky blades at Dragons' End. For this, you will die! Enough of this farce. Prepare to face my full wrath! 
(emote) Baron Sablemane begins emanating immense power. (emote)
Baron Sablemane changes into his true form, revealing himself to be Sabellian, a mature dragon of the Black dragonflight. He gains 110,000 HP.

After Goc dies, Sabellian returns to his Baron Sablemane guise.
Baron Sablemane yells: We will speak again, but away from here. 
Baron Sablemane despawns.

Video: http://www.youtube.com/watch?v=GJ1L050Cmn4"

Would be nice if you guys had another look at it, as the quest rewards are rather nice pre-raid blues etc.

Thanks in advance!

**Comment by DonTooTall** [comment]
A screenshot showing Goc flagged as friendly and Sabellian standing idle.

https://s4.postimg.org/ynclgel9p/Wo_WScrn_Shot_081516_113053.jpg

**Comment by lajhar** [comment]
Not necessary to repost known issues. #2358
