### ISSUE TITLE
Combat bug, dead on relog

### ISSUE THREAD

**Issue by dab2110** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3850]
I was farming in Eastern Plaguelands, and I got stuck in combat. I ran around a few minutes and couldn't shake it after killing a couple other mobs. I relogged to see if that would fix it, and was dead when I came back. There were no mobs around me when I relogged, and I wasn't gone long enough to have really died.

This happened twice. The third time I was stuck in combat, I moved some stuff around my inventory to make sure I was connected, still. Relogged, and came back dead again.

**Comment by devastator** [comment]
Please specify the creature that you were tagged in combat with.
Dying when logging out in combat is intended.
