### ISSUE TITLE
Long Forgotten Memories

### ISSUE THREAD

**Issue by Ver2N** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3854]
Archangel 2.4.3 Error Report Form

Report ID:VILL71

Reporter Name:Villadzen

Date/Time:6.09.16 - 7:22 PM

Error Severity:I can not complete the quest

Zone/Instance:Silitus

What type of error occurred?:Crystalline tear

What was the actual result vs. the expected result?:Crystal teardrop must complete the quest [Long Forgotten Memories] when I went up to her, a question mark lights dimmed, can not complete the quest

Can the error be repeated? If so, what are the steps?:----

Link to Video Evidence:http://www.pictureshack.ru/images/41464_WoWScrnShot_090616_201149.jpg

External/Related Links:

Please detail your character’s race, class, and items (optional):Rogue,Blood Elf.

**Comment by Ver2N** [comment]
Please help

**Comment by lajhar** [comment]
I'm gonna reopen the old report, because seems like it is not working again.
You can find it under #2455 
Thank you for your report!
