### ISSUE TITLE
Victory rush / pvp

### ISSUE THREAD

**Issue by teddys** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3857]
Expected situation : Victory rush becomes available to you after you land a killing blow on an enemy that yields honor/experience and can be used within 20seconds after that killing blow.

Current situation : When you use charge or intercept, you can no longer use victory rush even if it's still within that 20 second window.

**Comment by teddys** [comment]
in fact it's not only after charge and intercept .. it's after using any abillity or even autoattack

**Comment by lajhar** [comment]
#3831
