### ISSUE TITLE
stunned with divine shield

### ISSUE THREAD

**Issue by soda09** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3859]
one can be stunned, when using divine shield. But it should make immune to any spell.

**Comment by lajhar** [comment]
Couldn't reproduce it. I tried with several type of stun effects, but the paladin was immune to all of them. Can you give me additional details, what kind of item/spell/NPC ability stunned you while you were using Divine Shield?

**Comment by soda09** [comment]
I was stunned by an meele NPC at the tower on the road up to hearthglen.

**Comment by lajhar** [comment]
Tested the NPC ability, works as intended (Divine shielded targets were immune).
Closing until evidence's provided
