### ISSUE TITLE
Seal of Command procc delayed

### ISSUE THREAD

**Issue by soda09** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3860]
I opened this Issue because #3240 was still not fixed.

Seal of Command procc has a 3 Sec delay but it should only be delayed by 0.5 sec.

I found this:
Seal of Command critical hits can now trigger Vengeance.
Since Patch 1.11, Seal of Command proc will have approximately 0.5 second delay before the animation begins and the Holy damage is incurred, instead of having the proc occur instantly with the swing of the attack. This is considered a good change, since if the normal swing is a critical strike and Vengeance is triggered, the Seal of Command proc will be affected by the buff.
(http://wowwiki.wikia.com/wiki/Seal_of_Command_(old))

And maybe, while fixing this issue, you can have a look at #3858, aswell.
Both bugs make the core ability of Retri-Palas worthless.

**Comment by lajhar** [comment]
Issues are on bugtracker.
