### ISSUE TITLE
stunned while blessing of freedom is active

### ISSUE THREAD

**Issue by soda09** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3861]
Paladin can be stunned while blessing of freedom is active. I used blessing of freedom and a warri stunned me with his charge.
"Places a Blessing on the friendly target, granting immunity to movement impairing effects for 10 sec"
(http://wowwiki.wikia.com/wiki/Blessing_of_Freedom?oldid=1631776)

**Comment by AnonXS** [comment]
Movement impairing effects refers to snare effects like harmstring, not stun effects. http://wowwiki.wikia.com/wiki/Snare

**Comment by lajhar** [comment]
Working as intended.

**Comment by soda09** [comment]
Sorry. I missunderstod the ability of that spell.
