### ISSUE TITLE
[Hunter][Pet] - Pet special abilities not scaling with Unleashed Fury 

### ISSUE THREAD

**Issue by meowmewo** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3864]
Unleashed Fury - https://tbc-twinhead.twinstar.cz/?spell=19620 

Special skills such as Gore, Claw, Bite and Screech scale with 4 things - Unleashed Fury, Pet Mood, Pet family bonus and Ferocious Inspiration talent (3%dmg), ive found that they dont scale with Unleashed fury at all.

Bug - The talent affects only pet "white" attacks but doesnt affect skills like Gore, Claw, Bite etc. resulting in a neat dps loss for BM hunters and funny hits by Claw and Gore down to 20-30, unstead of averaging 60-70

How it should work - Should affect special skills as well.

here is a good video from SK gaming hunter pov - https://youtu.be/_gAQjX1oK6E?t=100, ive copied the exact time where u can see a hunter with a cat doing Claws averaging 70-90++. On Feenix a claw wont hit more then 50, unless u get bestial warth.

Something to add for Gore -  Gore = (Rank dmg) * pet family(+10% for ravagers) * happiness * dmg modifiers(Unleashed fury * Ferocious inspiration*))*(1-armor reduction%)

On Archangel it seems no DMG motifier is added.

**Comment by lajhar** [comment]
#3124
