### ISSUE TITLE
[Quest] The Foot of the Citadel still bugged

### ISSUE THREAD

**Issue by Bugthis** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3868]
Posting this again as it's still bugged after declared fixed.
Important end-of-quest-chain that is robbing me of 1000 rep points!

What : Quest - The Foot of the Citadel
http://wow-one.com/database/?quest=10876

Links : Challenge from the horde http://wow-one.com/database/?item=31702
Force-Commander Gorax http://wow-one.com/database/index.php?npc=19264
Hand of Kargath http://wow-one.com/database/?npc=22374
Gorax's Corpse http://wow-one.com/database/index.php?object=185223

How it works: you cannot use the Challenge from the horde banner on Gorax's corpse after killing Force-Commander Gorax.

How it should work: you should be able to use the item on Gorax's corpse to summon Hand of Kargath.

Screenshot : http://prnt.sc/c23ig4

**Comment by lajhar** [comment]
#3807 
The fix has not yet been implemented to live.
