### ISSUE TITLE
Fear

### ISSUE THREAD

**Issue by Wienerlord** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3869]
Fear doesn't work properly in PvP the player feared moves in all kinds of directions and in pve mobs move back and forth

**Comment by devidao** [comment]
how it should work properly?

**Comment by Wienerlord** [comment]
The mob and player should be running in fear in a straight line 

Try fear a player and a mob on live servers and see how its bugged

**Comment by Wienerlord** [comment]
The mob and player should be running in fear in a straight line 

Try fear a player and a mob on live servers and see how its bugged

**Comment by Wienerlord** [comment]
Sorry for the double reply was a mistake

**Comment by Wienerlord** [comment]
So umm this is a confirmed issue?

**Comment by devidao** [comment]
I think it is not a bug. Can you give any evidence that feared players should running in fear in a straight line ?

**Comment by lajhar** [comment]
Works as intended

**Comment by Applescruffs** [comment]
Fear does not work as intended, check the video in #3882 for proof.

When you fear something, the mob doesn't move naturally where you can see it.
It "freezes" in place but the actual location is somewhere else. There is some sort of de-sync between the mob's actual location and where it appears to you as the character than feared it.

**Comment by tokash1337** [comment]
Are you serious? "works as intended" and close?
Who gave this guy admin rights? He dont has any clue what he is talking about.

This issue has been reported nearly a year ago and I also described exactly whats the problem.
there were already several posts with video evidence.

All answers we get is "works as intendet", " cant reproduce" " its not as easy as you think"

All you need to do is log into archangel. Play any class that can fear. And fear anything.
That will take you maximum 5 minutes and you have enough evidence.


https://github.com/FeenixServerProject/Archangel_2.4.3_Bugtracker/issues/3739

**Comment by lajhar** [comment]
**This** issue is not about you two are talking about.
The reporter says that feared players should run away in a straight line instead of running in random directions. But since this is not true, **in case of the report** fear works as intended. What you guys are talking about is a general problem of CC mechanisms, which is a known issue, and needed to be fixed. You can leave your comments under the right issue if you have anything new to say, instead of blaming me for closing a pointless report.

**Comment by Wienerlord** [comment]
It breaks every single time

**Comment by Wienerlord** [comment]
Sorry for the miscommunication caused when I was posting the issue I really did not know how to report the issue properly
When I said the player/mob is supposed to move in a straight line what I meant was to say what applescruffs said

**Comment by Zerixx** [comment]
Fixed 12-04-16.
