### ISSUE TITLE
Righteous weapon coating!

### ISSUE THREAD

**Issue by Daweedian** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3874]
This is a minor bug, but still, this item:

http://www.wowhead.com/item=34539/righteous-weapon-coating

doesn't work on ranged attacks. Me and friend from a guild tested it for some 30 minutes on the isle and it didn't proc once on a ranged attacks while on melee it had pretty decent proc rate. This is not that of an important issue for now, just pointing it out so you know.

Krvavica

**Comment by lajhar** [comment]
#3760
