### ISSUE TITLE
[critical issue]People are unable to create new arena teams

### ISSUE THREAD

**Issue by teddys** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3880]
How to reproduce : buy 2v2 arena charter, have your second character sign it, turn it in and notice your team wasn't created

2v2 3v3 and 5v5 too

**Comment by ByteKiller** [comment]
Priority issue I am working on. It's affecting all charters (guild included).

**Comment by stekeen** [comment]
any update on this? how is it going? when is it working again? u are resetting points tommorow, second week without points cuz of u havent fixed it.. kinda losing players on this

**Comment by ByteKiller** [comment]
Current status is, petitions and charters are not "lost" or "missing"; players still have them even if they can't use them. Based on my investigations, we are performing a database cleanup operation and testing the results this morning during maintenance to resolve the charter problem.

**Comment by ByteKiller** [comment]
@stekeen @teddys testing was successful. Solution found. Scheduling when to apply it to Live. Thanks for your patience.
