### ISSUE TITLE
lifebloom final tick major issue

### ISSUE THREAD

**Issue by teddys** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3883]
after this fix
https://github.com/FeenixServerProject/Archangel_2.4.3_Bugtracker/issues/3766

lifebloom final tick went from ~1300-1400 healing to 2300-2400 NON CRIT
it crits for 3300-3400 ... those values are ridiculous

this is a major issue that makes druid teams almost unkillable in arenas

**Comment by teddys** [comment]
https://youtu.be/yFnVshE8uKU?t=55
1700 healing

**Comment by deathstreal** [comment]
Can confirm, druids in T6 gear critting for nearly 5k. LB should be critting for ~2k in PvP gear.

**Comment by tometo000** [comment]
The HoT and final heal gain roughly 52% and 34% of your +healing respectively.
Patch 2.4.0: The spell coefficient on the bloom is reduced by 20% (from approx 42% to approx 34%). The talent  [Empowered Rejuvenation] now applies to the bloom.

2000BH +  [Empowered Rejuvenation]x2 and  [Gift of Nature]x5
Should heal for: (600+(0.34*2000))*1.1*1.08 = 1520
Currently heals for: 2350

Source: http://wow.gamepedia.com/index.php?title=Lifebloom&diff=1406552&oldid=1285380

**Comment by lajhar** [comment]
**According to my tests, the Bloom has ~77,1% bh coefficient.** after the fix #3766 

Originally the bloom direct heal had ~ 43% (1.5/3.5 = 0,429) bonus healing coefficient. It was nerfed in patch 2.4.0:

> _**Patch 2.4.0** (25-Mar-2008): The spell coefficient on the bloom is reduced by 20% (from approx 42% to approx 34%)._ 

It was nerfed by 20% to approximately 34% (34,3% to be accurate).

Can be coincidence, but seems like the [bloom effect](https://www.wow-one.com/database/?spell=33778) recieves double coefficients: One from its base coefficient, and a second from the nerfed coefficient (DB value) which should overwrite the base coefficient. Therefore 43% + 34% = 77% which equals to my tests.
Similar issue might have happened to crits aswell.

**Comment by peterparkerx** [comment]
http://www.wow-one.com/forum/topic/19678-lifebloom-level-70/ currently x3 lifeblooms final heal increases on stack amount of lifeblooms, which should not happen

**Comment by lajhar** [comment]
@peterparkerx  Can you provide me any evidence? Becuase it does not increase on PTR/PLTR.

**Comment by Javas-Lal** [comment]
It doesn't on live. 
http://sendvid.com/wskyb7g7

**Comment by Zerixx** [comment]
http://imgur.com/a/tCPjg - Yeah, this is definitely botched. Will look at it now.

**Comment by teddys** [comment]
I don't think you understood what's wrong, because you posted a screenshot without any bonus healing gear, where lifebloom heals you for the correct value shown on the tooltip(600)???

read the previous comments please

**Comment by Zerixx** [comment]
> I don't think you understood what's wrong, because you posted a screenshot without any bonus healing gear, where lifebloom heals you for the correct value shown on the tooltip(600)???
> 
> read the previous comments please

First off, wrong SS. I took 12 of them. That was not the one I meant to add. 

Seems like a douchey response for someone trying to fix an issue for you, doesn't it? Regardless, there is  an issue that I have to find, and if you have a better way of doing it, please do educate me.

As far as I can tell, as of now, with 5x Gift & Empowered Rejuv x2 @ 1052 BH.

```
Initial heal, before getting bonus damage calculation: 1087.

With the formula (600 + (0.3428 * 1052)) * 1.1 * 1.08 = ~1141.22
```
What the core responds with: 1537. So, something is definitely not right if that is indeed the formula.

**Comment by Zerixx** [comment]
Fixed: https://github.com/ServerProject/TBC-DB/commit/1e2cdfbc4b97f1bc64344b23856f1546d52cc368

**Comment by teddys** [comment]
don't want to be rude or anything, but when exactly is this fix going to be applied to live?

**Comment by Zerixx** [comment]
Trying to figure that out @teddys - So many updates are waiting for Live, we're just trying to get it organized.

**Comment by lajhar** [comment]
Fix confirmed on PTR.

**Comment by lajhar** [comment]
Fix confirmed on PreLive

**Comment by lajhar** [comment]
On live as 15.9
