### ISSUE TITLE
Quest's container is absent.

### ISSUE THREAD

**Issue by RainbowCarrot** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3888]
https://www.wow-one.com/database/?object=19906 — this container for this quest: https://www.wow-one.com/database/?quest=1166

Other containers for that quest are fine both.

**Comment by lajhar** [comment]
The mentioned container can be found at the end of the cave as intended.
Picture:
![image](https://cloud.githubusercontent.com/assets/20255946/20804815/a593fd8e-b7f4-11e6-80c0-f3764502d828.png)
/close
