### ISSUE TITLE
[Database] Missing Patterns from SWP trash

### ISSUE THREAD

**Issue by Dorakrab** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3889]
Gloves of immortal dusk recipe seems to not be on the loot table

**Comment by roblockster** [comment]
Leatherworking Pattern: Gloves of the Immortal Dusk (35214) is not in the database.

Leatherworking Pattern: Sun-Drenched Scale Chestguard (35219) and Pattern: Fletcher's Gloves of the Phoenix (35213) are in the database, but do not appear to be on loot tables.

**Comment by Dorakrab** [comment]
add Plans: Hard Khorium Battlefists (35209) to that list also

**Comment by lajhar** [comment]
**The following patterns are missing from SWP trash:**

- Design: Amulet of Flowing Life [(35202)](https://www.wow-one.com/database/index.php?item=35202) _- Pattern is missing from loot tables_
- Pattern: Sun-Drenched Scale Chestguard [(35219)](https://www.wow-one.com/database/index.php?item=35219) _- Pattern is missing from loot tables_
- Pattern: Hands of Eternal Light [(35205)](https://www.wow-one.com/database/index.php?item=35205) _- Pattern is missing from DB_
- Pattern: Gloves of Immortal Dusk [(35214)](https://www.wow-one.com/database/index.php?item=35214) _- Pattern and item are missing from DB_
- Pattern: Fletcher's Gloves of the Phoenix [(35213)](https://www.wow-one.com/database/index.php?item=35213) _- Pattern is missing from loot tables_
- Plans: Hard Khorium Battlefists [(35209)](https://www.wow-one.com/database/index.php?item=35209) _- Pattern is missing from loot tables_

**Comment by lajhar** [comment]
Fix confirmed on PTR.

**Comment by twinkedup** [comment]
Any idea when this is gonna be on live?

**Comment by ghost** [comment]
@Forcy What's the ETA?

@twinkedup

**Comment by lajhar** [comment]
Already on live (15.7)
