### ISSUE TITLE
Steady Shot

### ISSUE THREAD

**Issue by Cadwalader** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3891]
Steady shot says "Weapon damage + 595"  My average with Valenos Longbow (damage 130-242) is 510 (min 455 max 548)

How can the maximum damage be less that the modifier? The minimum should be 130+595=725 * any RAP modifiers
I do less damage as an almost purple hunter @ 70 that a level 67 Mage

The original post stated that auto shot does the same amount of damage as steady shot.  This is true. Steady shot has no value.

This has been reported before and it has been claimed that steady shot is working correctly.  If that is the case you should remove it as it has no value., it serves no purpose. It does not increase damage over auto shot. It makes Hunters a joke, which is a shame

**Comment by Qingle** [comment]
Steady Shot should cause Weapon Damage + 150, not 595.
I have no idea of which orifice you pulled that number out from but you're completely wrong on every aspect of your post (excluding that Steady Shot isn't scaling on Feenix, this is a known bug).

It's just a spell scaling bug, they will get around to it. Meanwhile, you adding duplicate issues does not get it done any quicker, it just fills the issue tracker with useless shit that's already been posted.

**Comment by Cadwalader** [comment]
Thank you for your well thought out and considered response.

I assume you are 11 years old.

**Comment by Cadwalader** [comment]
Incidentally, I was asked to post it by a GM

**Comment by lajhar** [comment]
It was discussed several times, Steady Shot works as intended, seems like you are unfamiliar with the calculation math.
If you disagree, provide us sufficient proofs about your theory.

**Comment by Cadwalader** [comment]
I'm assuming the calculation is 

 

SteadyShotDamage = DamageModifiers*(150 + (WeaponDamage/WeaponSpeed)*2.8 + 0.2*RAP + [Dazed: 175])

 

if we ignore the component for dazed targets

 

then comparing with auto shot which is 

 

AutoShotDamage = DamageModifiers*(AmmoDPS*WeaponSpeed + (RAP/14)*WeaponSpeed + WeaponDamage + ScopeDamage)

 

then for a level 70 Hunter using a Valenos longbow with a +12 damage scope and Adamantite stingers with a RAP of  (691+1971)

 

Steady shot will give an approximately 4% increase  over auto shot.

 

This means the Hunters main shot is 4% better than doing nothing at all.

 

I'm not clear why 0.2 was selected as the modifier for RAP but it negates the ability of MM hunters to do meaningful DPS. Was it a BODMAS error?If this is Steady Shot working as intended it should be reconsidered.

 

Calculations attached

 

Regards
