### ISSUE TITLE
Stunned/dazed mobs visual bug

### ISSUE THREAD

**Issue by Daweedian** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3892]
I have no idea how to search for this bug (and I'm pretty sure that this has already been reported so someone please reference it), but stunned/dazed mobs appear to be running from place they are being tanked at. This results in melees not being able to use their special abilities while still being able to melee swing at them. This can result in aggro loss on that mob and slower killing of it. Sometimes they appear to run even for about 30 yards and it is really annoying. I wouldn't say that it is a major bug but it can cause some troubles.

Regards,
Krvavica

**Comment by Porshia** [comment]
#3882   Pathing

Bytekiller had assigned himself to address this issue. :+1: 
Let's hope this issue gets fixed soon as this is a gamebreaking issue  :)

**Comment by ghost** [comment]
@Porshia will do my best. Thanks for linking the issues btw

**Comment by Daweedian** [comment]
No problem guys, I will link whatever I encounter. I guess I might ease up on some smaller things but will link anything that I consider major. Thanks for quick response and for all your work!!

**Comment by teddys** [comment]
this is one of the most annoying issues I've encountered in quite some time

**Comment by lajhar** [comment]
Closing this one as a repost, discussion in #3882

**Comment by Zerixx** [comment]
Fixed 12-04-16.
