### ISSUE TITLE
Thrown weapon durability bug.

### ISSUE THREAD

**Issue by RainbowCarrot** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3893]
I have **Merciless Gladiator's War Edge** with **285** base durability.

Each time after relogin (with full durability) I get **29**/285 durability. Each time, always 29.

Before offline I can:
a) repair him. And I'll get damaged thrown with 29 durability only again after login
b) or not repair him. And I'll still be have 29 count during all time (even with relogins) till new repair.

**This weapon really bugged for all.**
And it seems bugged only with this weapon because other thrown weapons with another durability haven't a same trouble.

**Comment by lajhar** [comment]
#3836
