### ISSUE TITLE
Sunwell recipe & righteous weapon coatin weapon oil

### ISSUE THREAD

**Issue by kauski** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3894]
Righteous weapon coatin does not proc from ranged attacks at all, procs on melee attacks.

To test it, create hunter give it weapons, use the item on melee weapon and shoot arrows, doesnt proc.

Sunwell leatherworkin recipe: Gloves of the immortal dusk does not drop

on wowhead http://www.wowhead.com/item=35214/pattern-gloves-of-immortal-dusk

**Comment by lajhar** [comment]
#3760 
#3889
