### ISSUE TITLE
[Quest][Hunter] Taming the Beast

### ISSUE THREAD

**Issue by deficineiron** [FeenixServerProject/Archangel_2.4.3_Bugtracker#390]
This quest is required for hunters to be able to tame and use pets.  Important to note that this is a race-specific quest (in this case Dwarf), but that most races have a version of this quest and some of those may also not work right.  The quest is called Taming the Beast for all races, to the best of my knowledge.

In the quest in Dun Morogh, you are required to tame in succession a boar, leopard, and bear.  In BC live, as you brought back each pet to the quest giver, they would despawn when you completed the turn-in.  The quest pets are not despawning, and the player does not have the dismiss pet tool.

The only way i have found to remove the pet to allow me to train the next pet in the chain is to go get the pet killed.  The pet doesn't despawn with distance.  This problem is with all 3 pets, and the third (when you have been given the dismiss pet skill) you cannot dismiss, as you are told 'You do not have a pet'

**Comment by Salce** [comment]
Going to close this as it seems outdated
Please reply if it's still bugged.
