### ISSUE TITLE
[mechanic] Windfury not proccing from warrior on-next-swing abilities heroic strike or cleave

### ISSUE THREAD

**Issue by Tiglet1** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3900]
This has been a historic issue on this server. It was fixed recently but has started happening again.

**Comment by Tiglet1** [comment]
#3546 #3789 #

**Comment by teddys** [comment]
not happening for me .. wf procs from hs/cleave all the time

**Comment by Tiglet1** [comment]
Definitely an issue on alliance side. I guess it must be isolated to us

**Comment by teddys** [comment]
The spell windfury totem has same id for alliance and horde ... get MSBT and test it again .. it works correctly

**Comment by Tiglet1** [comment]
I think you should test it again. I've tested 4-5 times now, and also conversed with other raiding warriors on alliance (fury). As arms, windfury is not proccing from heroic strike/cleave however sword spec procs are. As fury the issue is the same (however the lack of sword spec procs make it more noticable). I think you are perhaps getting mixed up with sword spec procs?

**Comment by teddys** [comment]
sword spec is bugged here and doesn't proc instantly .. it queues the doubleattack for when the next melee swing lands .. so it can't be sword spec .. it's windfury
last time I checked was on sunday's raid .. we have raid today again .. I will check without sword spec, but I am 100% sure wf procs from hs/cleave for me

**Comment by teddys** [comment]
u are right #3534

**Comment by lajhar** [comment]
We are aware of the issue, and devs are working on it. Discussion & feedback at #3534
