### ISSUE TITLE
wrong cd on Brutallus "Burn" ability 

### ISSUE THREAD

**Issue by repae1f** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3902]
must be used every 20 sec
2.4.3 video proof
https://www.youtube.com/watch?v=e2rSmAiX7wo

**Comment by androidwk** [comment]
Yes. On Feenix it casts every 1 min instead of 20 sec.
https://www.youtube.com/watch?v=_gAQjX1oK6E
https://www.youtube.com/watch?v=NqORheQREkI

**Comment by Dorakrab** [comment]
combined with a soon to come radiance fix (i hope) this change would change the fight DRASTICALLY, since you would need a lot more healing while keeping the same amount of dps to beat the enrage timer, so id say this is a huge one

**Comment by Zerixx** [comment]
Fixed. Coming to PTR soon.

**Comment by Zerixx** [comment]
Fix confirmed on PTR @lajhar .

**Comment by androidwk** [comment]
Still casts every 1 min.

**Comment by lajhar** [comment]
It hasn't applied to live yet.

**Comment by lajhar** [comment]
Fix confirmed on PreLive

**Comment by lajhar** [comment]
On Live as 15.9
