### ISSUE TITLE
Brutallus Meteor Slash - Slightly too frequently

### ISSUE THREAD

**Issue by WarriorTSW** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3903]
Hey,

Sorry for spam.

Brurallus is currently using Meteor Slash every 10 seconds without fail.
Proof: http://imgur.com/a/LGdg0
And on all the retail footage Ive seen so far, it happens 11 seconds apart.

With Meteor Slash as it is now, tanks who are taunting off are about to refresh their stacks. But only just arent.

This is a very minor thing. As it does not refresh the stacks. But is worth noting.
Thanks

**Comment by deathstreal** [comment]
Apparently a guild actually did get the 7th Meteor Slash before the stacks from the 1st, 2nd, 3rd dropped off.

**Comment by Zerixx** [comment]
Fixed. Coming to PTR soon.

**Comment by WarriorTSW** [comment]
Just to confirm, there are times when you cant avoid receiving a third stack. This happens infrequently but I didn't mention it before.

**Comment by Chuchote0321** [comment]
Video Proof https://www.youtube.com/watch?v=UQALp46tIw8  
The debuff should despawn at that time, but in the video it refresh to 4th stacks.

**Comment by Zerixx** [comment]
Fix confirmed on PTR @lajhar .

**Comment by lajhar** [comment]
Fix confirmed on PreLive

**Comment by lajhar** [comment]
On live as 15.9
