### ISSUE TITLE
Druid Lifebloom (final tick heal)

### ISSUE THREAD

**Issue by Ariyana86** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3904]
Greetings, 
I wasnt sure if someone started this kind of issue allready, but anyway, even if exist allready, its not fixed yet, so I decide to make fresh one! The final lifebloom healing tick on Feenix is a way higher than should be. Average (non-crit) final tick, depends of talents that druid use, and BH he have, should be ~1300, and curently is over ~2100 (crit ~4000+). I post you a link, so you guys can see the Lifebloom formula for patch 2.4, and I hope u gonna fix the bugg asap. http://wow.gamepedia.com/index.php?title=Lifebloom&diff=1406552&oldid=1285380

**Comment by Porshia** [comment]
#3883

**Comment by lajhar** [comment]
Repost. Closing
