### ISSUE TITLE
Kalecgos Health.

### ISSUE THREAD

**Issue by pucko91** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3912]
Report ID: Titum004

Reporter Name: Titum

Date/Time:161128 00:09ST

Error Severity: Major

Zone/Instance: Sunwell Plateau

What type of error occurred?: Kalecgos health is about 2 mil then it should be to be equvalent to pre nerf retail even with the improved dmg output on feenix servers.

What was the actual result vs. the expected result?: Hype having more problem killing him than anything else and it seems unbalanced to need fully crafted gears from sunwell and trash drops in order too kill him.

Can the error be repeated? If so, what are the steps?: Look at his health and fight occuring on kalecgos with guilds on feenix.

Link to Video Evidence: Don't have any although there is only the health pool to look at.

External/Related Links: see answer above.

Please detail your character’s race, class, and items (optional):

**Comment by lajhar** [comment]
Kalecgos' health pool has already reduced on live. /close
