### ISSUE TITLE
Hurricane Does Not Reduce Attack Speed of NPCs

### ISSUE THREAD

**Issue by dangreenberggit** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3919]
Current situation: Druid spell Hurricane ([27012](https://www.wow-one.com/database/index.php?spell=27012)) does not reduce attack speed of NPCs.

Desired situation: Hurricane reduces attack speed by 25%, as described in the tooltip.

This is a very useful Druid spell for big AOE pulls or spawns, and an important aspect of Boomkin utility.

**Comment by Zerixx** [comment]
Pretty sure this is working on PTR. 
@lajhar .

**Comment by lajhar** [comment]
Yeah, my bad, it's working on live aswell. Test with 4 sec speed weapon. 
![image](https://cloud.githubusercontent.com/assets/20255946/21034570/10bce84a-bdb9-11e6-924d-decabb79df4a.png)
Closing until counter proof

**Comment by dangreenberggit** [comment]
My mistake. Edited title of report to reflect the issue is regarding NPCs, not player characters.
