### ISSUE TITLE
Windfury not proccing from Heroic Strike or Cleave

### ISSUE THREAD

**Issue by Tiglet1** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3920]
Since it was deleted without comment, I'm going to repost.

This is an issue that has been affecting dps warriors since sunwell release.

I've tested this numerous times, and confirmed with other warriors on alliance side, so this is definitely an issue - especially for fury warriors.

A horde warrior, teddys, argues this isnt occuring however I've sat and heroic striked a dummy with windfury totem up 100+ times and had 0 windfury procs. I've not only done this multiple times but other alliance warriors are having the same issues.

Please at-least address the issue before deleting bug reports.

**Comment by lajhar** [comment]
You don't need to repost existing issues again and again, it won't speed up the fixing process.
As I told before closing your previous issue

> We are aware of the issue, and devs are working on it. Discussion & feedback at #3534
