### ISSUE TITLE
Lifebloom not working correctly.

### ISSUE THREAD

**Issue by Thedream69** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3921]
http://imgur.com/Yj9ZwTW            non-critical Lifebloom final tick 2300 (that's suppose to be the critical value of lifebloom)

 

http://imgur.com/9QUYBl6            Critical Lifebloom final tick 3500(the current state of lifebloom is the critical value is actually the critical of the normal scripted critical value) A normal lifebloom final tick should be healing per say, 1200-1500 (depending on bonus healing) and critting for 2100-2300.

**Comment by repae1f** [comment]
https://github.com/FeenixServerProject/Archangel_2.4.3_Bugtracker/issues/3883

**Comment by Zerixx** [comment]
I have this fixed locally, though hasn't made its way to PTR yet. Closing.. re-post.
