### ISSUE TITLE
Hunter pet abilities recieve 0 Scaling from Attack Power

### ISSUE THREAD

**Issue by Detox92** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3924]
How to replicate: Use a Cat pet with Claw ability, unequip all items and see it hit for approx 40 damage. 
Now equip all items for Ap increase to pet and watch same Claw still hit for 40. This is the case for all pets and its why so many hunters use Wind Serpents.

**Comment by Qingle** [comment]
#3124
#3825
