### ISSUE TITLE
Righteous Weapon Coating not working for Hunters

### ISSUE THREAD

**Issue by Detox92** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3925]
Righteous Weapon Coating should proc on ranged attacks when applied to melee weapon as Hunter yet it does not.

How to replicate: Apply Righteous Weapon Coating to melee weapon and shoot a dummy for a time. Result: 0 Righteous Weapon Coating procs.

**Comment by Qingle** [comment]
Already fixed #3760

**Comment by Detox92** [comment]
Oh ok, last time i replicated it was at SWP release, *Edit* So im testing it out right now on Isle of Quel'danas  using 2x Coatings and it is NOT proccing on ranged attacks.

**Comment by lajhar** [comment]
We are aware of this issue, thanks for the report. Feedback & discussion at #3760
