### ISSUE TITLE
Players with multiple professions!

### ISSUE THREAD

**Issue by Pawx** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3928]
Okay let me address the elephant in the room now that one player was reported on the forum having (at least) 3 professions and has received 30 day suspension + professions removed.

Are we expecting to fix this? :)

**Comment by repae1f** [comment]
Was reported month ago. Report i think in closed section.

**Comment by lajhar** [comment]
Report has already made, devs are aware of the issue.
