### ISSUE TITLE
Sunwell Plateau Trash Mobs Stunnable

### ISSUE THREAD

**Issue by Applescruffs** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3931]
Current situation: All trash mobs can be fully crowd controlled including stuns.
Expected result: Most should be immune stuns.

http://wowwiki.wikia.com/wiki/Sunwell_Plateau
Scroll down to the "Encounters" section. 
Each npc's individual page lists how each mob should be able to be crowd controlled.

**Comment by lajhar** [comment]
Sunwell Plateau trash mob issues (including this one) have been collected in private section.
Thank you for your report anyway.
