### ISSUE TITLE
Ice block/divine shield after patch

### ISSUE THREAD

**Issue by teddys** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3941]
All spells go through ice block and divine shield at the moment. It does not provide an immunity.
http://imgur.com/a/HhMIm
http://imgur.com/a/0TSUL

**Comment by lajhar** [comment]
According to my tests, Ice Block works properly against:

- Nature spells
- Fire spells
- Frost spells

Not working properly against:

- Holy spells
- Shadow spells
- Arcane spells
- Physical spells

In addition, DoTs from the last 4 spellschools get applied on the Mage with Ice Block, but they don't tick until the Ice Block fades.

Can the community confirm these tests?

**Comment by teddys** [comment]
http://imgur.com/a/HhMIm

**Comment by lajhar** [comment]
I'm trying to figure out the connection between spells that Ice Block/Divine Shield immune against:

IB/DS immune against:

- Fireball
- Frostbolt
- Arcane Missiles
- Lightning Bolt
- Wrath
- Pyroblast
- Frost Nova
- Ice Lance
- Shadow Bolt
- Soul Fire
- Incinerate
- Death Coil
- Hammer of Wrath
- Hammer of Justice

IB/DS not immune against:

- Blast Wave
- Chain Lightning
- Starfire
- Moonfire
- Mind Blast
- Holy Nova
- Smite
- Immolate
- Fire Blast
- Searing Pain
- Earth Shock
- Dragon's Breath
- Cone of Cold
- Shadow Word: Death
- Holy Fire
- Crusader Strike
- Seals
- Fears (really funny)
- Scorch

Against periodic damage (DoTs, channeling, etc) DS/IB don't immune, but the mage/paladin don't recive damage until block/shield fades

**Comment by teddys** [comment]
hmm I hear that people get slowed while under the effects of bestial wrath .. so I guess that and blessing of freedom are fked aswell?

**Comment by lajhar** [comment]
Probably yes.
Cyclone, banish has broken aswell.
@Zerixx will revert a fix from patch 15.9 tonight which caused these issues until we find a solution.

**Comment by repae1f** [comment]
also after patch all demons can be enslaved
bosses too

**Comment by Qingle** [comment]
@lajhar @Zerixx 
Maybe the spell flag system and how they interact with each other?
I would put in an application to help on the website, but from where I do my work it's blocked..

**Comment by Zerixx** [comment]
@Qingle Well, the issue was more or less that the system was incomplete due to a few things that were barred from live at 15.9.. it'll just be a few more weeks till we see it ^^
