### ISSUE TITLE
Treeants damage too low

### ISSUE THREAD

**Issue by Liebeskrank** [FeenixServerProject/Archangel_2.4.3_Bugtracker#466]
Treeants, summoned by a balance druid spell Force of Nature, are hitting too low, their damage is not blizzlike. They hit for about 40-60 and crit +80 with each hit, while blizzlike damage would be more than one time higher. Their damage was correct before core swap.

Source: http://www.wowhead.com/spell=33831/force-of-nature - those comments, written in retail BC, speak of them hitting for 150 or higher (depending on spellpower which they scale with).

How to reproduce: Spec Force of Nature, use Force of Nature on a level 70 enemy, observe the damage.

**Comment by dangreenberggit** [comment]
Treant damage still appears to be incorrect--and too low. [EJ](http://elitistjerks.com/f47/t21687-druid_balance/#Discussion_of_FoN_usage) indicates around 9,000 damage with good usage by a well-geared Druid, but using FoN currently only nets 3-4k.

 It is notable that Treants appear to have a high miss chance--10%, 12% or more during use. This is likely not the correct hitcap, but it indicates that Treant damage is not scaling correctly.
