### ISSUE TITLE
[NPC][Netherstorm] Warp Chaser issue

### ISSUE THREAD

**Issue by Bwayzoe** [FeenixServerProject/Archangel_2.4.3_Bugtracker#48]
The [Warp Chaser](http://old.wowhead.com/npc=18884)s go out of combat / evade / reset when they use their [Phasing Invisibility](http://old.wowhead.com/spell=32942) ability.

Thanks to Aksi for reporting.

**Comment by lajhar** [comment]
Already fixed on live
