### ISSUE TITLE
[Quest] [BEM] Gorgrom the Dragon-Eater

### ISSUE THREAD

**Issue by Psykosa** [FeenixServerProject/Archangel_2.4.3_Bugtracker#493]
After placing the trap at the alter and spawning Gorgrom, he does not trigger the trap and proceeds to kill you.

**Comment by devastator** [comment]
Fix went Live with patch 12.0

**Comment by Psykosa** [comment]
Thank you, the quest is now finally completable, whoever, when clicking on the alter, instead of it creating a flame effect, it spawns [Misha, Rexxar's pet](https://www.wow-one.com/database/index.php?npc=10204). http://imgur.com/51k00GF

**Comment by devastator** [comment]
Yes, its how it's supposed to work, you can check on some videos around internet. There should be also flame effect but there isn't much info on the spell that should be used
