### ISSUE TITLE
[Spells][Warrior] Victory Rush bug

### ISSUE THREAD

**Issue by Groshar** [FeenixServerProject/Archangel_2.4.3_Bugtracker#592]
If Victory Rush misses, is dodged, or is parried it can be used again and again until it hits or the 20 second timer wears off.

**Comment by devidao** [comment]
Fixed, coming soon on PTR

**Comment by anaaz** [comment]
Fix denied [url=http://www.wow-one.com/forum/topic/103570-243-ptr-february/?p=759444]link[/url]

**Comment by Zerixx** [comment]
Fixed. Waiting on PTR.

**Comment by anaaz** [comment]
Fix applied to live with Patch 15.2
