### ISSUE TITLE
[Quest Bug]  The Soul Cannon of Reth'hedron

### ISSUE THREAD

**Issue by crotchrot** [FeenixServerProject/Archangel_2.4.3_Bugtracker#612]
Quest Name: The Soul Cannon of Reth'hedron

Bug: The 'Flawless Arcane Essence' item is obtained from an NPC in terrokar, however when you talk to the NPC he doesnt reply, and he doesnt summon elementals for you to kill and loot the quest item.

**Comment by ByronRageQuit** [comment]
Tried march 2016. Not working.

**Comment by devidao** [comment]
Fixed, coming soon on PTR.
