### ISSUE TITLE
[Quest]  Whispers of the Raven God

### ISSUE THREAD

**Issue by YonatanJ** [FeenixServerProject/Archangel_2.4.3_Bugtracker#687]
http://www.wowhead.com/quest=10607
http://www.wowwiki.com/Quest:Whispers_of_the_Raven_God

It seems like none of the Grishna give you the buff, and therefore you caanot complete the quest.

**Comment by ByronRageQuit** [comment]
Still not working (02.18.2014)

**Comment by moshamaniac** [comment]
3 sept 2015 still bugged.

**Comment by devidao** [comment]
Fixed, coming soon on PTR.

**Comment by Cadwalader** [comment]
9/9/16  Still bugged

**Comment by devidao** [comment]
because it is still not applied
