### ISSUE TITLE
[Quest] [Terokkar] Missing friends

### ISSUE THREAD

**Issue by gupostalgu** [FeenixServerProject/Archangel_2.4.3_Bugtracker#717]
Problem with <a href="http://old.wowhead.com/quest=10852">this</a> quest.
<a href="http://wow.zamimg.com/uploads/screenshots/normal/115298.jpg">Kids in cages</a> don't respawn after rescue, only after server restart.

**Comment by beaten** [comment]
Still not working.  Cages remain empty till restart.  Also:  only 1 child per ground cage, and 2 children per tree cage, where wowhead comments (http://www.wowhead.com/quest=10852/missing-friends) state 2 children per ground cage, and 4 children per cage in the trees.
