### ISSUE TITLE
[Item] Dartol's Rod of Transformation

### ISSUE THREAD

**Issue by Groshar** [FeenixServerProject/Archangel_2.4.3_Bugtracker#744]
From the quest http://www.wowwiki.com/Quest:Raene%27s_Cleansing_%286%29

Whenever somebody heals you or buffs you, it dispells your furbolg form.  You should normally only lose your furbolg form if you right click the buff or if you take damage.

Edit:  Other players (friendly or hostile) can also simply use Dispell Magic, Purge, etc. to remove furbolg form as well.

**Comment by devidao** [comment]
could not reproduce, maybe issue not available already
