### ISSUE TITLE
[Quest][Netherstorm] Creatures of the Eco-Domes

### ISSUE THREAD

**Issue by Srodri** [FeenixServerProject/Archangel_2.4.3_Bugtracker#78]
When using the quest item Talbuk Tagger on Talbuk Sire or Talbuk Doe mobs that are beneath 20% hp you don't get quest counter increased.

Links:
http://old.wowhead.com/quest=10427/creatures-of-the-eco-domes
http://old.wowhead.com/item=29817#provided-for
http://old.wowhead.com/npc=20610
http://old.wowhead.com/npc=20777

**Comment by dlehman12** [comment]
It appears this quest is broken again
