### ISSUE TITLE
[Quest][Searing Gorge] Suntara Stones

### ISSUE THREAD

**Issue by deficineiron** [FeenixServerProject/Archangel_2.4.3_Bugtracker#819]
http://old.wowhead.com/quest=3367

This is the first quest of this name,  you have to escort an injured dwarf NPC from the Grimeslit digsite in Eastern Searing Gorge. 

I can accept the quest, but the NPC doesn't activate or move from there.  This locks out a chain starting from this quest.

**Comment by devidao** [comment]
Fixed, coming soon on PTR.
