### ISSUE TITLE
[NPC] Daggerfen Assassin/Muckdweller

### ISSUE THREAD

**Issue by Groshar** [FeenixServerProject/Archangel_2.4.3_Bugtracker#833]
Both of these mobs found at Daggerfen Village in Zangarmarsh don't use some of their abilities properly.

1. **[Fixed on Live]** The Daggerfen Assassins should use their Sneak (stealth) ability when out of combat.  http://www.wowhead.com/npc=18116#abilities

2.  The Daggerfen Muckdwellers use their ability Paralytic Poison but it does not stun you after it expires.  http://www.wowhead.com/npc=18115#abilities

*I don't know why the tooltip says 15 seconds on wowhead when it's actually 30 seconds.

**Comment by devastator** [comment]
Fixed with patch 15.0
