### ISSUE TITLE
[Quest] Bladespire Kegger (H)

### ISSUE THREAD

**Issue by Midgie** [FeenixServerProject/Archangel_2.4.3_Bugtracker#852]
http://old.wowhead.com/quest=10545
Obtained in Blade's Edge Mountains from <a href="http://old.wowhead.com/npc=21349">T'chali the Witch Doctor</a> in Bloodmaul Outpost.

The quest requires you to place <a href="http://old.wowhead.com/item=30353">Bloodmaul Brutebane Keg</a> on the ground to attract the Bladespire ogres and get them drunk.  Placing kegs on the ground does not count toward quest completion, regardless of the distance from the ogre.

Alliance version of the quest is #355.  (Different questgivers, same mechanic.)

**Comment by devidao** [comment]
Fixed, coming soon on PTR.
