### ISSUE TITLE
[Quest] On Spirit's Wings (H)

### ISSUE THREAD

**Issue by Midgie** [FeenixServerProject/Archangel_2.4.3_Bugtracker#853]
http://www.wowhead.com/quest=10714
Obtained in at Thunderlord Stronghold in Blade's Edge Mountains.

Quest requires you to find a <a href="http://www.wowhead.com/npc=22160">Bloodmaul Taskmaster</a> and <a href="http://www.wowhead.com/npc=22384">Bloodmaul Soothsayer</a> engaged in conversation and use the quest item provided to summon an owl named Spirit.  

Hitting both mobs with the green circle AoE mark does not summon the owl to complete the quest.

Tried relogging/clearing cache, abandoning/reobtaining the quest, and also killing the two mobs to make them respawn and nothing seems to work.

**Comment by ByronRageQuit** [comment]
Broken still Feb 2015

**Comment by devidao** [comment]
Fixed, coming soon on PTR.
